import { pageMetadata } from '@/lib/seo/metadata'
import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Camera, Check, ChevronDown, Clock3, FileCheck2, Globe2, MapPin, MessageSquare, Phone, Search, ShieldCheck, Store, UsersRound } from 'lucide-react'
import { ServiceHero } from '@/components/sections/services/ServiceHero'
import { BusinessSectionHeading, ServiceReveal } from '@/components/sections/services/BusinessService'
import { BusinessProfileDemo } from './_components/BusinessProfileDemo'
import './google-business-profile.css'

const title = 'Google Business Profile : création, optimisation & gestion | Litus'
const description = 'Une fiche Google claire et suivie : informations, catégories, services, photos et avis. Litus vous accompagne sur Google Business Profile, anciennement Google My Business.'
const url = 'https://www.litus.fr/google-business-profile'
const contact = '/contact?objet=Google%20Business%20Profile'
export const metadata: Metadata = pageMetadata("/google-business-profile", {
  title: { absolute: title }, description, alternates: { canonical: url },
  openGraph: { title, description, url, siteName: 'Litus', locale: 'fr_FR', type: 'website', images: [{ url: '/litus-og-social.png', width: 1200, height: 630, alt: 'Litus — Votre agence web pour développer votre activité.' }] },
  twitter: { card: 'summary_large_image', title, description, images: ['/litus-og-social.png'] },
})
const pillars = [
  { icon: Store, title: 'Les bonnes informations', text: 'Nom réel, catégorie pertinente, coordonnées, horaires habituels et exceptionnels : nous passons en revue les informations qui permettent de comprendre votre activité.', deliverable: 'Une base cohérente et documentée.' },
  { icon: Camera, title: 'Une présentation fidèle', text: 'Vos lieux, vos prestations et votre accueil méritent des photos authentiques. Nous organisons les contenus disponibles et identifions ce qu’il reste à préparer.', deliverable: 'Des éléments utiles avant la visite.' },
  { icon: MessageSquare, title: 'Une relation entretenue', text: 'Des avis à lire, des réponses à préparer et des informations à actualiser. Nous définissons avec vous une manière de suivre la fiche dans la durée.', deliverable: 'Un rythme et des responsabilités clairs.' },
]
const method = [
  { title: 'Faire le point', text: 'Nous vérifions la fiche existante, les accès, l’activité représentée et les informations publiées. En cas de création, nous examinons d’abord l’éligibilité.' },
  { title: 'Renseigner avec justesse', text: 'Nous préparons les informations et les contenus avec votre équipe. Les justificatifs ou étapes de validation demandés par Google sont traités avec vous.' },
  { title: 'Organiser le suivi', text: 'Nous définissons les mises à jour, la gestion des avis et les personnes qui valident les réponses ou les changements importants.' },
  { title: 'Relire les observations', text: 'Les interactions disponibles et vos retours terrain éclairent les ajustements. Nous gardons une trace des changements réalisés sur la fiche.' },
]
const faqs = [
  { question: 'Google Business Profile et Google My Business, est-ce la même chose ?', answer: 'Google Business Profile est le nom actuel de l’outil autrefois appelé Google My Business. Il permet aux établissements éligibles de gérer leur fiche sur la recherche Google et Google Maps. Notre prestation porte sur la préparation, l’optimisation et le suivi de cette fiche, en lien avec les informations réelles de votre activité.' },
  { question: 'Une fiche Google est-elle adaptée à mon activité ?', answer: 'L’éligibilité dépend notamment de la manière dont vous rencontrez vos clients et de la réalité de votre établissement ou de votre zone de service. Une activité exclusivement en ligne ne répond pas nécessairement aux critères. Nous examinons votre situation au regard des consignes Google avant de créer ou de modifier la fiche.' },
  { question: 'Faut-il payer Google pour créer une fiche ?', answer: 'La fiche Google Business Profile est proposée gratuitement par Google. L’accompagnement Litus correspond au travail de préparation, de configuration, de contenu et de suivi convenu avec vous. Il est distinct d’une campagne Google Ads. Son périmètre et son budget sont précisés dans la proposition.' },
  { question: 'Pouvez-vous garantir une première place sur Google Maps ?', answer: 'Non. Google indique que les résultats locaux reposent notamment sur la pertinence, la distance et la notoriété. Une fiche complète aide à présenter votre entreprise, mais ne supprime pas ces critères. Nous travaillons les éléments que vous pouvez maîtriser, sans vendre une position garantie.' },
  { question: 'Comment accompagnez-vous la gestion des avis ?', answer: 'Nous pouvons préparer une méthode pour solliciter des retours authentiques et répondre de manière adaptée. Les avis doivent refléter une expérience réelle ; les contreparties en échange d’un avis sont interdites par Google. Les réponses sensibles sont validées avec vous. Un avis négatif légitime ne peut pas être supprimé simplement parce qu’il déplaît.' },
  { question: 'Qui garde la propriété et les accès à la fiche ?', answer: 'Votre entreprise doit conserver la maîtrise de ses accès. Nous définissons les rôles nécessaires à notre intervention et travaillons avec les autorisations convenues. Les contenus, les validations et les modalités de suivi sont documentés. Si un problème de propriété ou de validation existe déjà, il est examiné avant de poursuivre les changements.' },
  { question: 'Quelle différence avec un accompagnement SEO local ?', answer: 'La fiche Google est un point de contact sur Google Search et Maps. Le SEO local couvre un ensemble plus large : votre site, ses pages locales, les informations qui présentent votre entreprise et leur cohérence. Selon votre besoin, nous pouvons travailler la fiche seule ou l’intégrer à un accompagnement local plus complet.' },
]
const structuredData = { '@context': 'https://schema.org', '@graph': [
  { '@type': 'Service', '@id': `${url}#service`, name: 'Création, optimisation et gestion de Google Business Profile', description, url, serviceType: 'Accompagnement de fiche d’établissement Google', provider: { '@type': 'Organization', name: 'Litus', url: 'https://www.litus.fr' }, areaServed: { '@type': 'Country', name: 'France' } },
  { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: 'https://www.litus.fr' }, { '@type': 'ListItem', position: 2, name: 'Google Business Profile', item: url }] },
  { '@type': 'FAQPage', mainEntity: faqs.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
] }

export default function GoogleBusinessProfilePage() {
  return <div className="business-service gbp-service-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, '\\u003c') }} />
    <ServiceHero id="google-business-profile-title" eyebrow="Google Business Profile · Votre établissement" title={'Votre fiche Google, bien tenue.\nVotre entreprise, bien présentée.'} accent="Votre entreprise, bien présentée." description="Avant un appel ou une visite, votre fiche Google présente votre activité. Nous travaillons ses informations, ses photos et son suivi pour donner aux clients des repères fiables et une bonne première impression." primaryAction={{ label: 'Parlons de votre fiche', href: contact }} secondaryAction={{ label: 'Voir l’accompagnement', href: '#accompagnement-fiche' }} visual={<BusinessProfileDemo />} proof={<ul className="business-hero-proof"><li><MapPin aria-hidden="true" /><span>Une présence bien renseignée</span></li><li><Camera aria-hidden="true" /><span>Une image fidèle à l’activité</span></li><li><UsersRound aria-hidden="true" /><span>Vous gardez vos accès</span></li></ul>} />
    <div className="business-content">
      <section className="business-section gbp-service-intro" aria-labelledby="gbp-visit-title"><div className="business-container"><BusinessSectionHeading eyebrow="Le premier contact commence souvent ici" id="gbp-visit-title" description="Un horaire, une photo, un service ou un avis peuvent orienter une décision. Votre fiche doit aider la personne à comprendre qui vous êtes et comment vous joindre.">Avant de pousser la porte,<br /><em>on vous découvre sur Google.</em></BusinessSectionHeading><ServiceReveal className="gbp-service-questions">{[
        { icon: Search, question: 'Est-ce le bon professionnel ?', answer: 'Une activité et des services décrits avec précision.' },
        { icon: Clock3, question: 'Puis-je venir ou appeler ?', answer: 'Des horaires et des coordonnées à jour.' },
        { icon: Camera, question: 'À quoi dois-je m’attendre ?', answer: 'Des photos réelles et une présentation cohérente.' },
      ].map(({icon:Icon,question,answer})=><article key={question}><span className="business-icon"><Icon aria-hidden="true" /></span><h3>{question}</h3><p>{answer}</p></article>)}</ServiceReveal></div></section>
      <section className="business-section business-section-soft" aria-labelledby="gbp-support-title"><div className="business-container"><BusinessSectionHeading eyebrow="Créer, reprendre ou entretenir votre fiche" id="gbp-support-title" description="Nous accompagnons les commerces, artisans et entreprises de services qui rencontrent leurs clients. Chaque intervention part de votre situation réelle, des accès disponibles et des règles de Google.">Une fiche complète.<br /><em>Un fonctionnement clair.</em></BusinessSectionHeading><ServiceReveal className="business-grid">{pillars.map(({icon:Icon,title:itemTitle,text,deliverable})=><article className="business-card gbp-service-card" key={itemTitle}><span className="business-icon"><Icon aria-hidden="true" /></span><h3>{itemTitle}</h3><p>{text}</p><div><Check aria-hidden="true" /><span>{deliverable}</span></div></article>)}</ServiceReveal></div></section>
      <section className="business-section" aria-labelledby="gbp-review-title"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">La cohérence, dans les détails</p><h2 id="gbp-review-title">Votre activité évolue.<br /><em>La fiche doit suivre.</em></h2><p>Un nouvel horaire, une fermeture exceptionnelle, un service ajouté ou un changement de téléphone peuvent rendre une ancienne information trompeuse. Nous organisons le suivi autour de ces moments de votre activité.</p><p>Le bon niveau de détail dépend de l’établissement. Nous examinons les catégories, les services et les informations utiles à vos clients, puis rapprochons la fiche de votre site et de vos supports existants.</p><Link href="/seo-local" className="business-text-link">Construire une présence locale cohérente<ArrowRight size={17} aria-hidden="true" /></Link></div><div className="gbp-service-checklist"><div><FileCheck2 aria-hidden="true" /><strong>Votre fiche, point par point</strong></div>{[
        ['Identité', 'Nom réel, catégorie et description de l’activité.'],['Contact', 'Téléphone, site et moyen de prise de contact.'],['Accueil', 'Adresse ou zone desservie, horaires et exceptions.'],['Présentation', 'Services, photos et informations pertinentes.'],['Suivi', 'Accès, avis, changements et points à vérifier.'],
      ].map(([label,text])=><article key={label}><span><Check aria-hidden="true" /></span><h3>{label}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="business-section business-section-warm" aria-labelledby="gbp-human-title"><div className="business-container business-split"><figure className="gbp-service-photo"><div className="business-photo"><Image src="/blog/photos/commerce-vitrine.webp" alt="Une passante regarde une vitrine de boutique" fill sizes="(max-width:850px) 100vw, 48vw" /><div className="business-photo-note"><strong>Une présence fidèle à votre accueil.</strong><span>Vos vrais lieux, vos services, votre manière de travailler.</span></div></div><figcaption>Photographie d’illustration — Gyorgy Bakos, CC0.</figcaption></figure><div className="business-copy"><p className="business-kicker">Votre réputation se construit avec vos clients</p><h2 id="gbp-human-title">Des photos authentiques.<br /><em>Des réponses humaines.</em></h2><p>Votre fiche est une vitrine de l’activité réelle. Nous privilégions les images de vos lieux, de votre travail et de votre offre, accompagnées d’informations précises et utiles.</p><p>Les avis appellent une attention adaptée : comprendre le retour, répondre avec votre ton et traiter les sujets sensibles avec discernement. Nous pouvons préparer des réponses et une méthode de suivi à valider avec vous.</p><ul className="business-check-list"><li><Check aria-hidden="true" /><span>Des demandes d’avis liées à de vraies expériences.</span></li><li><Check aria-hidden="true" /><span>Des réponses personnalisées, sans exposer de données privées.</span></li><li><Check aria-hidden="true" /><span>Une validation pour les situations délicates.</span></li></ul></div></div></section>
      <section className="business-section business-section-dark" aria-labelledby="gbp-context-title"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">La bonne place dans votre présence en ligne</p><h2 id="gbp-context-title">Une fiche et un site,<br /><em>au service du même accueil.</em></h2><p>La fiche permet de trouver rapidement les informations essentielles. Votre site apporte le détail : prestations, démarche, réalisations et moyens d’échanger sur un projet.</p><p>Nous veillons à leur cohérence pour que la personne retrouve la même entreprise tout au long de son parcours. Si votre site doit évoluer, nous pouvons coordonner les interventions.</p><Link className="business-text-link" href="/creation-site-internet">Présenter votre activité sur votre site<ArrowUpRight size={17} aria-hidden="true" /></Link></div><div className="gbp-service-journey"><article><span><MapPin aria-hidden="true" /></span><div><h3>La fiche Google</h3><p>Vous situer et préparer le contact.</p></div></article><ArrowRight aria-hidden="true" /><article><span><Globe2 aria-hidden="true" /></span><div><h3>Votre site internet</h3><p>Comprendre votre offre et votre expertise.</p></div></article><ArrowRight aria-hidden="true" /><article><span><Phone aria-hidden="true" /></span><div><h3>L’échange avec vous</h3><p>Poser les questions et préciser le besoin.</p></div></article></div></div></section>
      <section className="business-section" id="accompagnement-fiche" aria-labelledby="gbp-method-title"><div className="business-container"><BusinessSectionHeading eyebrow="Notre accompagnement" id="gbp-method-title" description="Un interlocuteur, des accès définis et un périmètre lisible. Vous savez quelles informations sont préparées, qui les valide et comment la fiche sera entretenue.">Une fiche bien préparée.<br /><em>Un suivi dans la durée.</em></BusinessSectionHeading><ServiceReveal className="gbp-service-method">{method.map((item,index)=><article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</ServiceReveal><div className="gbp-service-ownership"><ShieldCheck aria-hidden="true" /><p><strong>Votre entreprise garde la maîtrise de sa fiche.</strong> Les rôles, les validations et les modalités de suivi sont convenus dès le départ. Notre prestation est chiffrée selon les actions nécessaires ; la fiche Google elle-même est gratuite.</p></div></div></section>
      <section className="business-section business-section-soft" aria-labelledby="gbp-faq-title"><div className="business-container"><BusinessSectionHeading eyebrow="Vos questions" id="gbp-faq-title">Google Business Profile,<br /><em>en toute clarté.</em></BusinessSectionHeading><div className="business-faq">{faqs.map(item=><details key={item.question}><summary>{item.question}<ChevronDown aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></div></section>
      <section className="business-section" aria-labelledby="gbp-contact-title"><div className="business-container business-final"><div><p className="business-kicker">Votre premier point de contact</p><h2 id="gbp-contact-title">Votre fiche reflète-t-elle<br /><em>vraiment votre entreprise ?</em></h2><p>Partagez votre fiche actuelle ou présentez-nous votre activité. Nous ferons le point sur les informations, les accès et l’accompagnement adapté à votre situation.</p></div><div className="business-final-actions"><Link href={contact} className="site-cta-primary">Parlons de votre fiche Google<ArrowRight size={18} aria-hidden="true" /></Link><span>Premier échange · Périmètre sur mesure</span><a href="tel:+33744985521">07 44 98 55 21</a></div></div><nav className="business-container gbp-service-related" aria-label="Expertises complémentaires"><Link href="/seo-local">Référencement local<ArrowUpRight /></Link><Link href="/referencement-naturel">Référencement naturel<ArrowUpRight /></Link><Link href="/google-ads">Google Ads<ArrowUpRight /></Link></nav></section>
    </div>
  </div>
}
