export const applicationContactHref = '/contact?objet=Application%20web%20sur%20mesure'

export const applicationFaq = [
  { question: 'Quelle différence entre un site internet et une application web ?', answer: 'Un site présente généralement une activité ou des contenus. Une application web permet aussi d’accomplir des tâches : gérer des dossiers, partager des documents, attribuer des actions ou suivre un processus. Elle fonctionne depuis un navigateur, avec une interface et des accès adaptés à chaque utilisateur.' },
  { question: 'Faut-il développer sur mesure ou choisir un logiciel existant ?', answer: 'Nous commençons par examiner votre besoin et les solutions disponibles. Un logiciel existant peut suffire ; une intégration ou une extension peut aussi être pertinente. Le sur-mesure prend son sens lorsque vos processus, vos accès ou vos échanges de données nécessitent un fonctionnement spécifique.' },
  { question: 'Pouvez-vous reprendre nos fichiers Excel et nos données ?', answer: 'Oui, après avoir vérifié les formats, la qualité et les droits d’utilisation des données. Nous préparons les règles de correspondance, les contrôles et des essais d’import. La migration définitive se planifie avec votre équipe pour préserver la continuité de l’activité.' },
  { question: 'L’application peut-elle se connecter à notre CRM ou à notre ERP ?', answer: 'Nous étudions les API, les possibilités d’export, les droits d’accès et les limites de vos logiciels. Selon ces possibilités, l’application peut lire ou mettre à jour des informations et déclencher des actions. Le périmètre des connexions et leur suivi sont définis avant le développement.' },
  { question: 'L’application sera-t-elle utilisable sur mobile ?', answer: 'Les écrans sont conçus pour les appareils et les usages prioritaires : bureau, tablette ou téléphone. Nous adaptons la navigation, les formulaires et la consultation des dossiers. Les besoins particuliers, comme le fonctionnement hors connexion ou une application native, sont étudiés séparément.' },
  { question: 'Quel budget et quel délai prévoir ?', answer: 'À titre indicatif, un outil métier simple démarre autour de 5 000 € et une première version fonctionnelle peut demander 4 à 8 semaines. Ces repères dépendent du périmètre, des intégrations et des données à reprendre. Le cadrage permet de préciser le devis et le calendrier ; une plateforme plus complète demande un budget et un délai adaptés.' },
  { question: 'Comment sont prévus les droits d’accès et la sécurité ?', answer: 'Nous définissons les rôles et les informations accessibles à chacun. Les choix d’authentification, d’hébergement, de sauvegarde et de journalisation sont adaptés au projet. Les contrôles et les tests font partie de la conception, puis du suivi convenu pour l’application.' },
  { question: 'Que se passe-t-il après la mise en ligne ?', answer: 'Nous préparons la prise en main, la documentation et les modalités de suivi. Maintenance, corrections, mises à jour et nouvelles fonctionnalités font l’objet d’un périmètre clair. Les conditions d’accès au code, aux données et à l’hébergement sont précisées dans les documents du projet.' },
] as const
