export const landingContactHref = '/contact?objet=Cr%C3%A9ation%20de%20landing%20page'
export const landingFaq = [
  { question: 'Qu’est-ce qu’une landing page ?', answer: 'Une landing page, ou page d’atterrissage, accueille un visiteur après une annonce, un email ou un lien de campagne. Elle développe une offre précise et facilite une action : demander un devis, réserver un échange, s’inscrire ou découvrir un produit. Elle peut faire partie de votre site existant.' },
  { question: 'Quelle différence avec la page d’accueil de mon site ?', answer: 'La page d’accueil présente plusieurs facettes de votre entreprise et permet de s’orienter. Une landing page répond à une intention plus ciblée, avec un message et une prochaine étape cohérents avec la campagne. Elle conserve les informations nécessaires pour comprendre l’offre et vous identifier.' },
  { question: 'Peut-on créer une landing page pour Google Ads ?', answer: 'Oui. Nous rapprochons l’offre, le message de l’annonce et les informations de la page. Le visiteur doit retrouver ce qui lui a été présenté et comprendre comment poursuivre. La création de la page et la gestion des campagnes sont deux périmètres que nous précisons dans le devis.' },
  { question: 'Rédigez-vous les textes et choisissez-vous la structure ?', answer: 'Nous travaillons le message, la hiérarchie et les appels à l’action avec vous, à partir de votre offre et des questions de vos clients. Les preuves, témoignages, visuels et conditions doivent être réels et validés. Le travail de rédaction et de production de contenus est défini au cadrage.' },
  { question: 'Comment mesure-t-on les résultats de la page ?', answer: 'Nous définissons les actions utiles à suivre : formulaire effectivement reçu, appel ou réservation, selon votre parcours. Les événements et les outils sont configurés puis testés dans le cadre convenu et selon les choix de consentement. Le suivi distingue les simples clics des demandes qui aboutissent.' },
  { question: 'Faut-il faire des tests A/B ?', answer: 'Ils peuvent aider à comparer deux versions quand le trafic et le nombre de conversions permettent une lecture utile. Pour une page peu visitée, mieux vaut commencer par vérifier le message, le parcours et la mesure. Nous choisissons une méthode proportionnée à votre campagne, sans annoncer de gain à l’avance.' },
  { question: 'La landing page sera-t-elle adaptée au mobile ?', answer: 'Oui, les textes, boutons et formulaires sont conçus pour la consultation sur téléphone. Nous vérifions aussi le chargement, la stabilité des éléments et les étapes de contact sur les écrans prioritaires. Les images et les intégrations sont adaptées au contenu de la page.' },
  { question: 'Combien coûte une landing page et quand peut-elle être publiée ?', answer: 'Le budget et le calendrier dépendent des contenus, du design, du formulaire, des connexions et du suivi demandé. Nous établissons un devis après avoir défini l’objectif et les éléments disponibles. Les dépenses publicitaires et la gestion des campagnes sont précisées séparément.' },
] as const
