import { pageMetadata } from '@/lib/seo/metadata'
import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, ChevronDown, Crosshair, FileCheck2, Gauge, Mail, MessageSquareText, PanelTop, Phone, Search, ShieldCheck, Smartphone, Target } from 'lucide-react'
import { ServiceHero } from '@/components/sections/services/ServiceHero'
import { BusinessSectionHeading, ServiceReveal } from '@/components/sections/services/BusinessService'
import { LandingHeroDemo } from './_components/LandingHeroDemo'
import { landingContactHref, landingFaq } from './landing-content'
import './landing.css'

const title = 'Création de landing page sur mesure & conversion | Litus'
const description = 'Litus crée des landing pages adaptées à vos campagnes : offre claire, design sur mesure, formulaires et suivi des demandes. Google Ads, lancement ou prise de rendez-vous.'
const url = 'https://www.litus.fr/creation-landing-page'
export const metadata: Metadata = pageMetadata("/creation-landing-page", { title: { absolute: title }, description, alternates: { canonical: url }, openGraph: { title, description, url, siteName: 'Litus', locale: 'fr_FR', type: 'website', images: [{ url: '/litus-og-social.png', width: 1200, height: 630, alt: 'Litus — Votre agence web pour développer votre activité.' }] }, twitter: { card: 'summary_large_image', title, description, images: ['/litus-og-social.png'] } })
const schema = { '@context': 'https://schema.org', '@graph': [
  { '@type': 'Service', '@id': `${url}#service`, name: 'Création de landing page sur mesure', description, url, serviceType: 'Conception de pages d’atterrissage et optimisation du parcours de conversion', provider: { '@type': 'Organization', name: 'Litus', url: 'https://www.litus.fr' }, areaServed: { '@type': 'Country', name: 'France' } },
  { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: 'https://www.litus.fr' }, { '@type': 'ListItem', position: 2, name: 'Création de landing page', item: url }] },
  { '@type': 'FAQPage', '@id': `${url}#faq`, mainEntity: landingFaq.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
] }

export default function LandingPage() {
  return <div className="business-service landing-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} />
    <ServiceHero id="landing-title" eyebrow="Landing pages · Lorient & Le Mans" title={'Création de landing page.\nDonnez une suite à vos clics.'} accent="Donnez une suite à vos clics." description="Une offre claire, une page ciblée et une prochaine étape évidente. Nous créons des landing pages pour vos campagnes, vos lancements et vos prises de contact, avec un parcours pensé pour être mesuré." primaryAction={{ label: 'Parlons de votre landing page', href: landingContactHref }} secondaryAction={{ label: 'Découvrir notre approche', href: '#approche-landing' }} visual={<LandingHeroDemo />} visualBackground="/blog/photos/planning-bureau.webp" proof={<ul className="business-hero-proof"><li><Target aria-hidden="true" /><span>Un objectif précis</span></li><li><Smartphone aria-hidden="true" /><span>Un parcours mobile</span></li><li><FileCheck2 aria-hidden="true" /><span>Des actions mesurables</span></li></ul>} />
    <div className="business-content">
      <section className="business-section landing-opening" aria-labelledby="landing-opening-title"><div className="business-container business-split"><div><p className="business-kicker">Après l’annonce, la bonne page</p><h2 id="landing-opening-title">Le clic est un début.<br /><em>La page fait la suite.</em></h2></div><div className="business-copy"><p>Votre visiteur arrive avec une attente : comprendre un service, comparer une offre ou obtenir une réponse. Il doit retrouver immédiatement le sujet qui l’a fait cliquer.</p><p>Nous relions la campagne à une page d’atterrissage dédiée, avec <strong>un argumentaire lisible, des informations utiles et un contact facile.</strong> Le travail porte sur l’ensemble du parcours.</p></div></div></section>

      <section className="business-section" aria-labelledby="landing-uses-title"><div className="business-container"><BusinessSectionHeading id="landing-uses-title" eyebrow="Des pages pour des moments précis">La bonne page,<br /><em>pour la bonne intention.</em></BusinessSectionHeading><ServiceReveal className="business-grid">{[
        { icon: Search, title: 'Une campagne Google Ads', text: 'Une page centrée sur le service recherché, la zone concernée et l’action attendue. Le message prolonge celui de votre annonce.', label: 'Annonce → offre → demande' },
        { icon: Crosshair, title: 'Une nouvelle offre', text: 'Présenter un lancement, une prestation ou un événement avec les réponses nécessaires avant de demander un engagement.', label: 'Découverte → intérêt → échange' },
        { icon: Mail, title: 'Une campagne ciblée', text: 'Donner une destination claire à vos emails, liens de partenaires ou prises de parole, sans renvoyer vers une page trop générale.', label: 'Message → information → action' },
      ].map(({ icon: Icon, title: itemTitle, text, label }) => <article className="business-card landing-use" key={itemTitle}><span className="business-icon"><Icon aria-hidden="true" /></span><h3>{itemTitle}</h3><p>{text}</p><span>{label}</span></article>)}</ServiceReveal></div></section>

      <section className="business-section business-section-soft" id="approche-landing" aria-labelledby="landing-structure-title"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">Un argumentaire qui se lit naturellement</p><h2 id="landing-structure-title">Comprendre. Être rassuré.<br /><em>Pouvoir agir.</em></h2><p>Le design accompagne la décision. Nous travaillons la promesse, les bénéfices, les preuves et les réponses aux objections pour que chaque section ait une utilité.</p><p>Une action principale reste visible, avec une navigation qui permet de retrouver les informations nécessaires. Le formulaire demande ce qui est utile à la suite de l’échange.</p><Link href={landingContactHref} className="business-text-link">Travaillons votre message<ArrowRight size={17} aria-hidden="true" /></Link></div><div className="landing-outline" aria-label="Structure possible d’une landing page">{[
        ['01', 'L’offre en quelques mots', 'Ce que vous proposez, pour qui et dans quel contexte.'], ['02', 'Les raisons d’avancer', 'Bénéfices concrets, fonctionnement et preuves vérifiables.'], ['03', 'Les réponses qui rassurent', 'Conditions, questions fréquentes et interlocuteur identifié.'], ['04', 'Une prochaine étape simple', 'Demande de devis, réservation ou contact adapté à l’offre.'],
      ].map(([number, itemTitle, text]) => <details key={number} open={number === '01'}><summary><span>{number}</span><strong>{itemTitle}</strong><ChevronDown aria-hidden="true" /></summary><p>{text}</p></details>)}</div></div></section>

      <section className="business-section" aria-labelledby="landing-deliverables-title"><div className="business-container"><BusinessSectionHeading id="landing-deliverables-title" eyebrow="La page, dans les détails" description="L’expérience doit rester cohérente entre votre campagne, votre identité et les outils qui reçoivent les demandes. Le périmètre est défini avec vous avant la réalisation.">Une page conçue<br /><em>jusqu’au dernier clic.</em></BusinessSectionHeading><ServiceReveal className="landing-deliverables">{[
        { icon: MessageSquareText, title: 'Message & contenus', text: 'Un angle défini, une hiérarchie claire et des textes cohérents avec votre offre.' }, { icon: PanelTop, title: 'Design sur mesure', text: 'Une direction visuelle adaptée à votre marque et à la lecture sur chaque écran.' }, { icon: Gauge, title: 'Confort & performance', text: 'Des images adaptées, une interface stable et des interactions vérifiées sur mobile.' }, { icon: Phone, title: 'Contact & connexions', text: 'Un formulaire, un appel ou une réservation reliés au bon interlocuteur.' },
      ].map(({ icon: Icon, title: itemTitle, text }) => <article key={itemTitle}><span className="business-icon"><Icon aria-hidden="true" /></span><h3>{itemTitle}</h3><p>{text}</p></article>)}</ServiceReveal></div></section>

      <section className="business-section business-section-dark" id="mesure-landing" aria-labelledby="landing-measure-title"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">Une mesure qui répond à vos questions</p><h2 id="landing-measure-title">Les clics se comptent.<br /><em>Les demandes se suivent.</em></h2><p>Nous définissons ce qui compte pour votre activité : une demande reçue, un rendez-vous confirmé ou un appel. Les événements sont vérifiés avant de lire les résultats.</p><p>Les données de visite se rapprochent ensuite de la qualité des demandes. Cela permet de discuter du message, du ciblage et des étapes à améliorer, selon le trafic réellement disponible.</p><Link href="/google-ads" className="business-text-link">Relier la page à vos campagnes<ArrowRight size={17} aria-hidden="true" /></Link></div><div className="landing-measure-list">{[
        ['Visite', 'D’où vient la personne et quelle offre consulte-t-elle ?'], ['Intérêt', 'Quelle action choisit-elle sur la page ?'], ['Demande', 'Le formulaire ou la réservation aboutit-il ?'], ['Qualité', 'La demande correspond-elle à votre activité ?'],
      ].map(([itemTitle, text], index) => <div key={itemTitle}><span>0{index + 1}</span><strong>{itemTitle}</strong><p>{text}</p></div>)}<p><ShieldCheck aria-hidden="true" />Un suivi défini selon les outils et les choix de consentement.</p></div></div></section>

      <section className="business-section" aria-labelledby="landing-method-title"><div className="business-container business-split"><figure className="business-photo landing-method-photo"><Image src="/blog/photos/bureau-notes-analyse.webp" alt="Des notes surlignées, un crayon et un clavier sur un bureau" width={1400} height={933} sizes="(max-width: 850px) 100vw, 45vw" /><figcaption className="business-photo-note"><strong>Votre offre, avant la maquette.</strong><span>Poser les bons messages pour construire le bon parcours.</span></figcaption></figure><div className="business-copy"><p className="business-kicker">Une réalisation avec vous</p><h2 id="landing-method-title">Du cadrage au lancement,<br /><em>des choix concrets.</em></h2><ol className="landing-method-list"><li><strong>Cadrer</strong><span>Offre, cible, source de trafic et action attendue.</span></li><li><strong>Concevoir</strong><span>Messages, structure et maquette à valider ensemble.</span></li><li><strong>Intégrer & tester</strong><span>Responsive, contact, connexions et événements de mesure.</span></li><li><strong>Publier & ajuster</strong><span>Mise en ligne, premières observations et suites convenues.</span></li></ol><p className="landing-credit">Illustration — <a href="https://commons.wikimedia.org/wiki/File:Working_at_office_(Unsplash).jpg" target="_blank" rel="noopener noreferrer">Javier Quesada</a> · CC0.</p></div></div></section>

      <section className="business-section business-section-warm" id="faq" aria-labelledby="landing-faq-title"><div className="business-container"><BusinessSectionHeading id="landing-faq-title" eyebrow="Vos questions">Votre landing page,<br /><em>avec les bons repères.</em></BusinessSectionHeading><div className="business-faq">{landingFaq.map(item => <details key={item.question}><summary>{item.question}<ChevronDown size={17} aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></div></section>

      <section className="business-section" aria-labelledby="landing-contact-title"><div className="business-container business-final"><div><p className="business-kicker">Une campagne, une offre, un projet</p><h2 id="landing-contact-title">Votre prochain clic<br /><em>mérite une bonne page.</em></h2><p>Présentez-nous votre offre et la façon dont vous souhaitez attirer vos visiteurs. Nous définirons une page et un parcours adaptés à votre objectif.</p></div><div className="business-final-actions"><Link href={landingContactHref} className="site-cta-primary">Parlons de votre landing page<ArrowRight size={18} aria-hidden="true" /></Link><span>Premier échange · Devis sur mesure</span><a href="tel:+33744985521">07 44 98 55 21</a></div></div><nav className="business-container landing-related" aria-label="Services complémentaires"><Link href="/google-ads">Campagnes Google Ads<ArrowUpRight size={16} aria-hidden="true" /></Link><Link href="/creation-site-internet">Création de site internet<ArrowUpRight size={16} aria-hidden="true" /></Link><Link href="/referencement-naturel">Référencement naturel<ArrowUpRight size={16} aria-hidden="true" /></Link></nav></section>
    </div>
  </div>
}
