import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, CalendarDays, Check, CheckCheck, CreditCard, FileText, Heart, HeartHandshake, Mail, MapPin, Megaphone, Network, PenLine, ShieldCheck, ShoppingBag, Ticket, UsersRound } from 'lucide-react'
import './association.css'

const url = 'https://www.litus.fr/association'
const description = 'Création et refonte de site pour association : HelloAsso, dons, adhésions, événements et espace membres. Litus simplifie le quotidien de vos bénévoles.'
export const metadata: Metadata = {
  title: 'Création de site internet pour association | Litus', description,
  alternates: { canonical: url },
  openGraph: { title: 'Un site qui facilite la vie de votre association | Litus', description, url, type: 'website', locale: 'fr_FR', images: [{ url: '/association/action-collective-nettoyage-plage.webp', width: 1200, height: 800, alt: 'Des adultes et des enfants participent ensemble au nettoyage d’une plage' }] },
  twitter: { card: 'summary_large_image', title: 'Création de site internet pour association | Litus', description, images: ['/association/action-collective-nettoyage-plage.webp'] },
}

const faq = [
  ['Quel est le prix d’un site internet pour association ?', 'Le budget dépend des parcours à créer, des contenus à reprendre et des connexions nécessaires. Un site de présentation avec formulaires HelloAsso intégrés ne demande pas le même travail qu’un espace adhérents privé relié à un CRM. Notre devis distingue création ou refonte, intégrations, formation, hébergement et maintenance. Nous pouvons prioriser une première version utile, puis prévoir les évolutions.'],
  ['Peut-on intégrer HelloAsso à notre site actuel ?', 'Oui, sous réserve des possibilités techniques du site. Nous pouvons intégrer vos formulaires existants avec des widgets ou préparer un parcours plus spécifique avec HelloAsso Checkout et les API. L’objectif est de choisir l’intégration la plus simple qui répond au besoin, pas de développer une connexion complexe sans raison.'],
  ['Les dons en ligne ont-ils un coût ?', 'HelloAsso annonce ses outils de collecte sans frais ni commission pour les associations. Son financement repose sur une contribution volontaire proposée aux personnes qui paient, modifiable ou refusable. La conception du site, l’intégration et sa maintenance sont des prestations Litus distinctes, chiffrées dans le devis. Les conditions du service choisi sont vérifiées avant la mise en ligne.'],
  ['Peut-on garder notre compte HelloAsso et nos campagnes ?', 'Oui. Le compte reste celui de votre association. Nous partons de vos campagnes, formulaires et droits d’accès existants, puis vérifions leur configuration avec vous. L’association doit notamment disposer d’un compte autorisé à recevoir les paiements. Vous conservez la maîtrise de vos accès et des fonds collectés.'],
  ['Comment gérer les adhérents et les renouvellements ?', 'Un formulaire d’adhésion peut présenter vos catégories de membres, options et cotisations. Nous définissons ensuite où conserver la fiche adhérent et comment suivre les renouvellements. Une synchronisation avec votre CRM est possible si les outils et leurs API le permettent ; elle doit éviter de créer des doublons et limiter les données partagées.'],
  ['Peut-on ajouter des événements et une billetterie ?', 'Oui : page événement, date, lieu, jauge, modalités d’inscription et lien ou formulaire de billetterie. Un club sportif peut ainsi ouvrir les inscriptions à un stage ; une association culturelle, réserver des places pour un spectacle. Nous vous formons à ajouter les événements suivants depuis votre administration.'],
  ['Peut-on créer un espace membre privé ?', 'Oui, lorsque des informations ont réellement besoin d’être réservées aux adhérents : documents internes, comptes rendus ou ressources. Les droits, l’inscription, la récupération d’accès et la fermeture des comptes sont définis au cadrage. Un simple lien difficile à deviner ne constitue pas une protection.'],
  ['Pourrons-nous modifier le site sans savoir coder ?', 'Oui. Des modèles de pages et des champs simples permettent de publier une actualité, ajouter un événement, remplacer une photo ou mettre à jour un document. Nous prévoyons une formation sur votre propre site et des consignes pour le prochain bureau, avec des accès adaptés aux rôles de chacun.'],
  ['Quel délai prévoir pour la création ou la refonte ?', 'Le calendrier est fixé après le cadrage : il dépend du volume de contenus, des validations du bureau, de la disponibilité des accès et des intégrations. Si une rentrée associative ou une collecte approche, nous pouvons étudier un lancement par étapes, en donnant la priorité aux inscriptions ou aux dons.'],
  ['Les reçus fiscaux et paiements en plusieurs fois sont-ils possibles ?', 'Les reçus fiscaux concernent uniquement les associations et versements éligibles. Leur émission se paramètre sur les formulaires HelloAsso compatibles ; un paiement via Checkout ne génère pas automatiquement de reçu fiscal et nécessite une organisation distincte. Le paiement échelonné dépend du service et du paramétrage retenus. Ces points sont validés avec votre trésorerie avant l’ouverture.'],
  ['Comment prenez-vous en compte le RGPD et les données des membres ?', 'Nous limitons les champs au nécessaire, clarifions les destinataires et prévoyons les mentions d’information, droits d’accès et durées de conservation avec l’association. Les traceurs non nécessaires nécessitant un consentement restent désactivés avant le choix de la personne. Les photos, données de mineurs et éventuelles informations sensibles demandent une attention particulière. La conformité s’organise dans la durée, pas avec une simple case à cocher.'],
  ['Notre association peut-elle bénéficier de Google Ad Grants ?', 'Le programme est soumis aux critères de Google pour les associations et à ses règles de maintien. Toutes les structures ne sont pas éligibles et l’acceptation n’est pas automatique. Nous pouvons étudier votre situation, préparer les pages d’arrivée et suivre les actions utiles : adhésions, demandes de bénévolat ou dons, sans promettre une subvention ni un volume de résultats.'],
]
const schema = { '@context': 'https://schema.org', '@graph': [
  { '@type': 'WebPage', '@id': url, url, name: 'Création de site internet pour association', description, inLanguage: 'fr-FR' },
  { '@type': 'Service', name: 'Création et refonte de site internet pour association', serviceType: 'Site associatif et intégrations numériques', provider: { '@type': 'Organization', name: 'Litus', url: 'https://www.litus.fr' }, areaServed: { '@type': 'Country', name: 'France' }, url },
  { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: 'https://www.litus.fr' }, { '@type': 'ListItem', position: 2, name: 'Associations', item: url }] },
  { '@type': 'FAQPage', mainEntity: faq.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) },
] }
function Cta({ children, subject = 'Création du site de mon association', secondary = false }: { children: ReactNode; subject?: string; secondary?: boolean }) {
  return <Link className={secondary ? 'asso-text-link' : 'asso-button'} href={`/contact?objet=${encodeURIComponent(subject)}`}>{children}<ArrowRight size={18} aria-hidden="true" /></Link>
}
function Heading({ label, title, children }: { label: string; title: string; children?: ReactNode }) {
  return <div className="asso-heading"><p className="asso-eyebrow">{label}</p><h2>{title}</h2>{children && <p>{children}</p>}</div>
}
const collections = [
  { icon: Heart, title: 'Dons ponctuels ou réguliers', text: 'Un parcours lisible pour soutenir une action, choisir un montant et comprendre à quoi le don contribue.' },
  { icon: UsersRound, title: 'Adhésions & cotisations', text: 'Les bonnes catégories de membres, les informations utiles et un renouvellement plus facile à retrouver.' },
  { icon: Ticket, title: 'Billetterie & inscriptions', text: 'Stages sportifs, ateliers, spectacles ou rencontres : réunir les informations et la réservation au même endroit.' },
  { icon: Megaphone, title: 'Financement participatif', text: 'Présenter un projet concret, son budget, ses étapes et les moyens de contribuer à son financement.' },
  { icon: ShoppingBag, title: 'Petite boutique associative', text: 'Vendre les articles de votre club ou de votre association, avec des modalités de retrait ou de livraison explicites.' },
  { icon: CreditCard, title: 'Paiements bien intégrés', text: 'Widgets, Checkout ou API selon le parcours. Le paiement en plusieurs fois se prévoit lorsque le service le permet.' },
]
const functions = [
  { icon: CalendarDays, title: 'Faire vivre vos rendez-vous', text: 'Agenda, inscriptions, lieux, horaires, carte et informations pratiques. Une fiche claire par événement, puis un retour en images après l’action.' },
  { icon: HeartHandshake, title: 'Accueillir de nouveaux bénévoles', text: 'Un formulaire « Devenir bénévole » avec missions, disponibilités et contact référent. Les candidatures arrivent aux bonnes personnes.' },
  { icon: ShieldCheck, title: 'Rassembler vos adhérents', text: 'Espace privé, ressources et annuaire de membres si nécessaire. Documents, statuts et comptes rendus d’AG avec une visibilité adaptée.' },
  { icon: PenLine, title: 'Raconter ce que vous faites', text: 'Actualités, blog, galeries photos et vidéos, actions réalisées et impact documenté. Vos projets deviennent compréhensibles, pas seulement visibles.' },
  { icon: UsersRound, title: 'Donner un visage au collectif', text: 'Présentation du bureau, de l’équipe et des antennes. Partenaires, sponsors, appels à projets et espace presse trouvent leur place.' },
  { icon: Mail, title: 'Garder le lien', text: 'Newsletter, réseaux sociaux et formulaires adaptés aux demandes : partenariat, adhésion, presse ou aide. Chaque public sait comment vous joindre.' },
]
const ecosystem = [
  { icon: Heart, title: 'HelloAsso', detail: 'Dons · adhésions · événements', href: '#helloasso', className: 'is-helloasso' },
  { icon: Mail, title: 'Newsletter', detail: 'Informer avec le bon accord', href: '#connexions' },
  { icon: HeartHandshake, title: 'Bénévoles', detail: 'Missions & disponibilités', href: '#fonctionnalites' },
  { icon: Network, title: 'CRM associatif', detail: 'Une fiche, pas trois doublons', href: '#connexions' },
  { icon: CalendarDays, title: 'Agenda', detail: 'Les rendez-vous partagés', href: '#connexions' },
  { icon: Megaphone, title: 'Réseaux sociaux', detail: 'Faire circuler vos actions', href: '#visibilite' },
]

export default function AssociationPage() {
  return <div className="asso-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} />
    <section className="asso-hero asso-container" aria-labelledby="association-title">
      <div className="asso-hero-copy">
        <nav className="asso-breadcrumb" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span aria-hidden="true">/</span><span aria-current="page">Associations</span></nav>
        <p className="asso-eyebrow">Du temps pour votre cause. Pas pour la technique.</p>
        <h1 id="association-title">Création de site internet <span>pour association.</span></h1>
        <p className="asso-hero-promise">Un site qui facilite réellement la vie de votre association.</p>
        <p>Réunir les adhésions, les dons, les événements et les bonnes informations. Nous construisons le site et les outils qui vont avec, pour que votre équipe passe moins de temps à gérer et plus de temps à agir.</p>
        <div className="asso-actions"><Cta>Créer le site de mon association</Cta><a className="asso-text-link" href="#helloasso">Découvrir les intégrations <ArrowRight size={17} aria-hidden="true" /></a></div>
        <ul className="asso-hero-proof">{['HelloAsso intégré', 'Administration simple', 'Vos outils connectés'].map(text => <li key={text}><Check size={16} aria-hidden="true" />{text}</li>)}</ul>
      </div>
      <figure className="asso-hero-photo">
        <Image src="/association/benevoles-plantation-collective.webp" alt="Cinq bénévoles de différentes générations plantent un arbre ensemble en extérieur" width={1400} height={2100} sizes="(max-width: 760px) 92vw, (max-width: 1100px) 48vw, 560px" priority />
        <div className="asso-photo-note"><HeartHandshake aria-hidden="true" /><span>Moins d’administratif.<br /><strong>Plus de collectif.</strong></span></div>
        <figcaption>Photographie d’illustration · Pexels</figcaption>
      </figure>
    </section>
    <div className="asso-container">
      <section className="asso-audiences" aria-label="Les associations que nous accompagnons"><p>Votre engagement, votre façon de fonctionner.</p><ul>{['Associations loi 1901', 'Clubs sportifs', 'Culture & loisirs', 'Solidarité & humanitaire', 'Vie étudiante', 'Actions caritatives'].map(name => <li key={name}>{name}</li>)}</ul></section>

      <section id="helloasso" className="asso-section asso-helloasso">
        <div className="asso-split"><Heading label="HelloAsso, à sa juste place" title="Un soutien, une adhésion, une place réservée. Sans parcours compliqué.">Le site explique votre action. HelloAsso prend en charge la collecte. Litus relie les deux pour que les visiteurs puissent agir au bon moment, depuis les pages de votre association.</Heading><div className="asso-hello-note"><span>HelloAsso</span><h3>Vous gardez votre compte.<br />Nous soignons le parcours.</h3><p>Nous réutilisons vos campagnes quand elles conviennent, vérifions les accès et choisissons l’intégration adaptée. Vos fonds restent gérés par votre association, pas par l’agence.</p><a href="https://info.helloasso.com/" className="asso-text-link">Découvrir les outils HelloAsso <ArrowUpRight size={15} aria-hidden="true" /></a></div></div>
        <div className="asso-collection-grid">{collections.map(({ icon: Icon, title, text }) => <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div>
        <div className="asso-payment-note"><ShieldCheck aria-hidden="true" /><div><h3>Les bons réglages avant le premier paiement.</h3><p>Les outils de collecte HelloAsso sont annoncés sans frais ni commission pour l’association ; une contribution volontaire, modifiable ou refusable, est proposée au payeur. Notre prestation d’intégration est distincte. Les reçus fiscaux sont réservés aux associations et versements éligibles : <strong>Checkout ne déclenche pas leur génération automatique</strong>. Nous définissons le circuit adapté avec votre trésorerie.</p><a href="https://dev.helloasso.com/docs/guide-dint%C3%A9gration">Consulter les conditions d’intégration HelloAsso</a></div></div>
        <div className="asso-actions"><Cta subject="Faciliter les adhésions de mon association">Faciliter les adhésions</Cta><Cta secondary subject="Mettre en place les dons en ligne pour mon association">Mettre en place les dons en ligne</Cta></div>
      </section>

      <section id="fonctionnalites" className="asso-section">
        <Heading label="Bien plus qu’une vitrine" title="Le point de rencontre de toute votre vie associative.">Chaque association a son rythme. Un club prépare sa rentrée et ses stages ; une association culturelle annonce sa programmation ; une structure solidaire mobilise ses bénévoles et ses donateurs. Nous partons de ces usages, pas d’une liste de modules à empiler.</Heading>
        <div className="asso-function-grid">{functions.map(({ icon: Icon, title, text }) => <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div>
        <div className="asso-photo-pair"><figure><Image src="/association/collecte-solidaire-dons-alimentaires.webp" alt="Des bénévoles masqués réceptionnent des dons alimentaires dans des boîtes lors d’une collecte solidaire" width={1000} height={667} sizes="(max-width: 760px) 92vw, 45vw" loading="lazy" /><figcaption>Faire connaître une action. Donner envie d’y participer.</figcaption></figure><figure><Image src="/association/action-collective-nettoyage-plage.webp" alt="Un groupe d’adultes et d’enfants ramasse les déchets sur une plage avec des sacs de collecte" width={1200} height={800} sizes="(max-width: 760px) 92vw, 55vw" loading="lazy" /><figcaption>Du premier contact à l’action sur le terrain.</figcaption></figure></div>
      </section>

      <section id="connexions" className="asso-section asso-ecosystem-section">
        <Heading label="Moins de doubles saisies" title="Tout votre écosystème associatif connecté.">Le bon outil au bon endroit, et des informations qui circulent avec mesure. Nous identifions la source de référence de chaque donnée avant de relier vos services.</Heading>
        <div className="asso-ecosystem"><div className="asso-ecosystem-center"><Image src="/brand/litus-mark.webp" alt="" width={42} height={48} /><strong>Votre site associatif</strong><span>Conçu par Litus</span></div>{ecosystem.map(({ icon: Icon, title, detail, href, className }) => <a key={title} href={href} className={`asso-ecosystem-node ${className ?? ''}`}><Icon aria-hidden="true" /><strong>{title}</strong><span>{detail}</span><ArrowUpRight size={14} aria-hidden="true" /></a>)}</div>
        <div className="asso-split asso-connection-copy"><div><h3>Un exemple concret : la nouvelle adhésion.</h3><ol className="asso-workflow"><li>Le membre remplit le formulaire et règle sa cotisation.</li><li>Le paiement confirmé met à jour la fiche du CRM, si la connexion le permet.</li><li>Le référent est informé et le membre reçoit les informations d’accueil.</li><li>La newsletter reste un choix distinct, jamais une inscription forcée.</li></ol></div><div><h3>Nous partons aussi de ce que vous utilisez déjà.</h3><p>Outil d’emailing, CRM associatif, comptabilité, Google Calendar ou Google Drive : nous étudions les API, droits d’accès et exports disponibles. Une synchronisation utile doit prévoir les erreurs, les doublons et la reprise manuelle, pas seulement le scénario idéal.</p><div className="asso-links"><Link href="/automatisation">Automatisations <ArrowUpRight size={14} /></Link><Link href="/integrations-api">Intégrations API <ArrowUpRight size={14} /></Link><Link href="/expertise/google-workspace">Google Workspace <ArrowUpRight size={14} /></Link><Link href="/creation-outils-ia">IA lorsque pertinente <ArrowUpRight size={14} /></Link></div><p className="asso-small">Aucune donnée sensible d’adhérent n’est envoyée à un outil d’IA sans cadrage spécifique et garanties adaptées.</p></div></div>
      </section>

      <section id="administration" className="asso-section asso-split asso-admin">
        <div><Heading label="Vous gardez la main" title="Ajouter une actualité ne devrait pas devenir une mission informatique.">Un titre, une date, une photo, un bouton publier. Nous préparons des modèles simples pour les opérations que votre équipe fait vraiment, même lorsque les bénévoles ou le bureau changent.</Heading><ul className="asso-checklist">{['Ajouter un événement et mettre à jour ses informations.', 'Remplacer un document, une photo ou un contact.', 'Préparer un brouillon avant validation par le responsable.', 'Transmettre les accès et les bonnes pratiques au prochain bureau.'].map(text => <li key={text}><CheckCheck size={18} aria-hidden="true" />{text}</li>)}</ul><p>La formation se fait sur votre site. Nous choisissons <Link href="/expertise/wordpress">WordPress</Link> pour les besoins éditoriaux adaptés, ou <Link href="/expertise/nextjs">Next.js avec une administration dédiée</Link> lorsqu’un développement spécifique le justifie. Vous n’avez pas à choisir une technologie avant de nous expliquer vos besoins.</p></div>
        <figure className="asso-admin-demo"><div className="asso-demo-top"><span>Votre espace association</span><PenLine size={18} aria-hidden="true" /></div><div className="asso-demo-body"><p className="asso-eyebrow">Nouvel événement</p><h3>Une rencontre à partager.</h3><div className="asso-demo-field"><small>Titre</small><span>La journée des bénévoles</span></div><div className="asso-demo-row"><div className="asso-demo-field"><small>Date & horaire</small><span>À renseigner</span></div><div className="asso-demo-field"><small>Lieu</small><span>Maison des associations</span></div></div><div className="asso-demo-field"><small>Votre contenu</small><p>Présentez le programme, les informations pratiques et la façon de s’inscrire.</p></div><div className="asso-demo-status"><Check size={17} aria-hidden="true" />Un brouillon, une relecture, une publication.</div></div><figcaption>Exemple de présentation, adapté ensuite à vos usages.</figcaption></figure>
      </section>

      <section id="visibilite" className="asso-section asso-visibility"><Heading label="Être trouvé, puis donner envie d’agir" title="Votre cause mérite d’être découverte.">La visibilité se travaille autour de vos activités et de vos publics : rejoindre un club près de chez soi, trouver un atelier, soutenir une action ou proposer du temps. Pas autour de visites sans suite.</Heading><div className="asso-three"><article><MapPin aria-hidden="true" /><h3>Un ancrage local. Ou un réseau national.</h3><p>Pages d’activités, événements et antennes locales, informations pratiques cohérentes et Google Business Profile lorsque votre structure remplit les conditions. Nous construisons un référencement utile aux personnes que vous cherchez à toucher.</p><Link href="/referencement-naturel">Référencement naturel <ArrowUpRight size={15} /></Link><Link href="/seo-local">SEO local <ArrowUpRight size={15} /></Link></article><article><Megaphone aria-hidden="true" /><h3>Des campagnes au service de votre mission.</h3><p>Google Ads et, pour les structures éligibles, étude de Google Ad Grants. Nous travaillons les pages d’arrivée et les conversions importantes, sans promettre l’obtention du programme ni confondre budget publicitaire et accompagnement.</p><Link href="/google-ads">Notre accompagnement Google Ads <ArrowUpRight size={15} /></Link><a href="https://www.google.com/intl/fr/nonprofits/eligibility/">Critères officiels Ad Grants <ArrowUpRight size={15} /></a></article><article><Network aria-hidden="true" /><h3>Un suivi compréhensible par le bureau.</h3><p>Search Console pour le référencement, Analytics lorsque son déploiement est retenu et correctement paramétré, suivi des clics et inscriptions lorsque mesurables. Un don confirmé ne se confond pas avec une simple visite de formulaire.</p><Cta secondary subject="Visibilité du site de mon association">Parler de vos objectifs</Cta></article></div></section>

      <section id="reference" className="asso-section asso-reference"><div><Heading label="Une référence associative Litus" title="Femmes des Territoires : faire vivre un réseau.">Une refonte WordPress pour mieux orienter vers les événements, les antennes locales et les différentes façons de rejoindre l’association.</Heading><p>Navigation réorganisée et portes d’entrée plus accessibles : adhésion, bénévolat, partenariat et découverte du réseau. Un exemple de site pensé autour de la vie de l’association, avec un périmètre détaillé dans la réalisation.</p><Link href="/realisations/femmes-des-territoires" className="asso-button">Découvrir la réalisation <ArrowUpRight size={18} aria-hidden="true" /></Link></div><figure><div className="asso-browser-bar"><i /><i /><i /><span>Femmes des Territoires</span></div><Image src="/realisations/clients/femmes-des-territoires/reseau-entrepreneuses.webp" alt="Le site Femmes des Territoires présente ses rencontres d’entrepreneuses et ses réseaux local et digital" width={1920} height={709} sizes="(max-width: 900px) 92vw, 58vw" loading="lazy" /><figcaption>Refonte WordPress · Réseau associatif</figcaption></figure></section>

      <section id="confiance" className="asso-section"><Heading label="Un socle sérieux, sans jargon" title="Prendre soin de vos membres, aussi en ligne.">Les données d’adhérents ne sont pas un simple fichier de contacts. Nous intégrons les questions de protection, d’inclusion et d’exploitation dès le cadrage.</Heading><div className="asso-three"><article><ShieldCheck aria-hidden="true" /><h3>Données & sécurité</h3><p>Champs limités, droits par rôle, HTTPS, sauvegardes et maintenance définie. Durées de conservation et procédure d’accès ou de suppression sont convenues avec votre association. Les données de mineurs, photos et informations sensibles font l’objet d’un examen particulier.</p></article><article><UsersRound aria-hidden="true" /><h3>Accessibilité & mobile</h3><p>Navigation clavier, contrastes, intitulés de champs et erreurs compréhensibles. Nous prévoyons les exigences applicables à votre organisme et les évaluations nécessaires, sans présenter un module d’accessibilité comme une certification.</p></article><article><FileText aria-hidden="true" /><h3>Performance & cookies</h3><p>Images dimensionnées et compressées, pages légères, formulaires testés sur mobile. Les services tiers sont inventoriés et les traceurs soumis à consentement restent bloqués avant accord, avec une possibilité de refus et de retrait.</p></article></div><p className="asso-source">Un repère pour votre bureau : <a href="https://cnil.fr/fr/mon-quotidien/associations">les ressources de la CNIL pour les associations</a>.</p></section>

      <section id="projet" className="asso-section asso-project-plan"><Heading label="Avancer à votre rythme" title="Un projet clair, compatible avec votre réalité associative.">Le temps des bénévoles est précieux. Nous prévoyons des validations simples et un périmètre lisible, en tenant compte de vos temps forts et de vos moyens.</Heading><ol className="asso-method"><li><span>01</span><h3>Écouter le terrain</h3><p>Publics, missions, difficultés actuelles, outils existants et décisions du bureau.</p></li><li><span>02</span><h3>Choisir les priorités</h3><p>Arborescence, parcours, contenus, intégrations et budget détaillé. Une première version utile avant les options.</p></li><li><span>03</span><h3>Construire & transmettre</h3><p>Design, développement, reprise des contenus, tests des parcours et formation de vos responsables.</p></li><li><span>04</span><h3>Faire vivre le site</h3><p>Mise en ligne, redirections en cas de refonte, suivi et maintenance selon le cadre convenu.</p></li></ol><div className="asso-budget"><h3>Création, refonte, maintenance : on distingue les postes.</h3><p>Nombre de contenus, espace privé, connexions spécifiques, reprise des données et formation déterminent le devis. Le nom de domaine, l’hébergement, les éventuels services tiers et la maintenance sont explicités séparément. Vous savez ce qui est inclus et ce qui reste une option.</p><div className="asso-links"><Link href="/creation-site-internet">Création de site internet <ArrowUpRight size={14} /></Link><Link href="/refonte-site-internet">Préparer une refonte <ArrowUpRight size={14} /></Link><Link href="/ressources/cahier-des-charges">Préparer votre cahier des charges <ArrowUpRight size={14} /></Link></div></div></section>

      <section id="questions" className="asso-section asso-faq"><Heading label="Les questions du bureau" title="Avant de vous lancer.">Budget, autonomie, HelloAsso et données : des réponses concrètes pour préparer votre projet de site associatif.</Heading><div>{faq.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="asso-final asso-section"><div className="asso-final-mark"><Image src="/brand/litus-mark.webp" alt="Litus" width={56} height={64} /></div><div><p className="asso-eyebrow">Votre engagement mérite les bons outils.</p><h2>Parlons de votre association.</h2><p>Ce qui fonctionne, ce qui vous prend du temps, ce que vous aimeriez simplifier. Commençons par là.</p></div><Cta subject="Projet de site et outils pour mon association">Échanger sur mon projet</Cta></section>
      <p className="asso-credits">Scènes d’illustration sous licence Pexels, sans affiliation des personnes photographiées avec Litus : <a href="https://www.pexels.com/photo/people-planting-plant-together-5029923/">plantation collective</a>, <a href="https://www.pexels.com/photo/people-donating-food-to-a-charity-6995220/">collecte solidaire</a>, <a href="https://www.pexels.com/photo/people-cleaning-the-beach-9037222/">action sur le littoral</a>.</p>
    </div>
  </div>
}
