import { expertiseImage, expertiseScenes } from '@/lib/expertise/visuals'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight } from 'lucide-react'
import { BusinessSectionHeading, ServiceReveal } from '@/components/sections/services/BusinessService'
import { ExpertiseBreadcrumb } from '@/components/expertise/ExpertiseArticle'
import { expertiseTools, expertisePath } from '@/lib/expertise/catalog'
import { expertiseMetadata, expertiseSchema } from '@/lib/expertise/seo'

export const metadata = expertiseMetadata('Expertises technologiques : acquisition & infrastructure | Litus', 'Next.js, React, TypeScript, Tailwind, Framer, Vercel, Stripe, Shopify et WordPress : les expertises Litus pour créer, connecter et reprendre vos outils digitaux.', '/expertise')

export default function ExpertiseHub() {
  return <div className="business-service expertise-page expertise-hub">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(expertiseSchema()).replace(/</g, '\\u003c') }} />
    <ExpertiseBreadcrumb />
    <header className="business-container ex-hub-hero"><div><p className="business-kicker">Acquisition & infrastructure digitale</p><h1>Les bons outils.<br /><em>Pour les vrais sujets.</em></h1></div><div><p>Créer une interface. Reprendre une boutique. Débloquer un déploiement. Relier un paiement au CRM.</p><p>Nos technologies ne sont pas une fin en soi. Voici ce que nous pouvons concrètement en faire pour votre entreprise, et les limites à connaître avant de choisir.</p><a href="#outils" className="business-text-link">Trouver votre environnement<ArrowRight size={18} aria-hidden="true" /></a></div></header>
    <div className="business-content ex-content"><section className="business-section ex-hub-tools" id="outils" aria-labelledby="tools-title"><div className="business-container"><BusinessSectionHeading id="tools-title" eyebrow="Nos outils de travail">Neuf expertises. Des interventions précises.</BusinessSectionHeading><ServiceReveal className="ex-hub-grid">{expertiseTools.map((tool, index) => <Link href={expertisePath(tool.slug)} className="ex-hub-card" data-tool={tool.slug} key={tool.slug}><div><Image src={tool.logo} alt={`Logo ${tool.name}`} width={42} height={42} unoptimized loading={index < 4 ? 'eager' : 'lazy'} /><span>{String(index + 1).padStart(2, '0')}</span></div><p className="ex-hub-category">{tool.category}</p><figure className="ex-hub-media"><Image src={expertiseImage(expertiseScenes[tool.slug][0].file + '-thumb')} alt={expertiseScenes[tool.slug][0].alt} width={480} height={Math.round(expertiseScenes[tool.slug][0].height * 480 / expertiseScenes[tool.slug][0].width)} unoptimized loading="lazy" /><figcaption>{expertiseScenes[tool.slug][0].source ? 'Démonstration officielle' : 'Maquette illustrative'}</figcaption></figure><h3>{tool.name}</h3><p>{tool.summary}</p><span className="ex-hub-link">Découvrir l’expertise<ArrowUpRight size={18} aria-hidden="true" /></span></Link>)}</ServiceReveal></div></section>
    <section className="business-section business-section-soft" aria-labelledby="hub-needs-title"><div className="business-container ex-prose-grid"><BusinessSectionHeading id="hub-needs-title" eyebrow="Vous partez d’un besoin, pas d’un outil">On peut aussi commencer par ce qui bloque.</BusinessSectionHeading><div className="ex-prose"><p>Votre site ne reçoit pas les bonnes demandes ? Nous regardons son <Link href="/referencement-naturel">référencement</Link>, vos <Link href="/google-ads">campagnes d’acquisition</Link> et le parcours de contact, pas uniquement le CMS.</p><p>Vos équipes ressaisissent les mêmes données ? Le sujet peut être une <Link href="/integrations-api">connexion entre logiciels</Link>, une <Link href="/automatisation">automatisation</Link> ou une <Link href="/creation-application-web">application métier</Link>.</p><p>Votre présence en ligne doit repartir sur une base claire ? Nous comparons les solutions pour une <Link href="/creation-site-internet">création de site</Link>, une <Link href="/refonte-site-internet">refonte</Link> ou une <Link href="/creation-site-ecommerce">boutique e-commerce</Link>. Aucune technologie n’est imposée avant de comprendre votre fonctionnement.</p><p>Nous accompagnons les entreprises à <Link href="/agence-web-lorient">Lorient</Link>, au <Link href="/agence-web-le-mans">Mans</Link> et à distance dans toute la France.</p></div></div></section>
    <section className="business-section ex-final-section"><div className="business-container business-final"><div><p className="business-kicker">Parlons du fonctionnement</p><h2>Votre outil est connu.<br />Ou le problème est encore flou.</h2><p>Montrez-nous le site, l’application ou les étapes qui prennent du temps. Nous vous aidons à définir le bon point de départ.</p></div><div className="business-final-actions"><Link className="site-cta-primary" href="/contact?objet=Acquisition%20et%20infrastructure%20digitale">Présenter mon besoin<ArrowRight size={18} aria-hidden="true" /></Link><a href="tel:+33744985521">07 44 98 55 21</a></div></div></section></div>
  </div>
}
