import type { ExpertiseSlug } from './types'
import { businessDefinitions } from './connected-business'

export type ConnectedDefinition = {
  slug: ExpertiseSlug; name: string; logo: string; color: string; category: string
  title: string; description: string; headline: string; accent: string; intro: string
  service: { href: string; label: string }; deliverables: [string, string, string]
  cases: [string, string][]; context: [string, string]; process: [string, string][]
  fit: string[]; limits: string[]; faq: [string, string][]
  connections: { slug: ExpertiseSlug; reason: string }[]; sources: { label: string; href: string }[]
  visual: { kind: 'assistant' | 'code' | 'flow' | 'documents' | 'campaign' | 'workspace' | 'editor'; title: string; input: string[]; output: string[] }
}

export const connectedDefinitions: ConnectedDefinition[] = [
  ...businessDefinitions,
  {
    slug: 'openai', name: 'ChatGPT / OpenAI', logo: '/brands/openai-official.svg', color: '#202020', category: 'Assistants métier & API IA',
    title: 'Intégration ChatGPT & API OpenAI pour entreprise | Litus',
    description: 'Litus conçoit des assistants métier avec OpenAI : qualification de leads, analyse de documents, rapports et IA connectée à votre CRM ou application.',
    headline: 'Une IA qui connaît son rôle.', accent: 'Et les limites de son action.',
    intro: 'Lire une demande, retrouver une information dans vos documents ou préparer un compte rendu : nous intégrons OpenAI là où une étape de compréhension manque à votre processus. L’objectif est un résultat exploitable par votre équipe, pas un chatbot ajouté pour la vitrine.',
    service: { href: '/creation-outils-ia', label: 'Concevoir un assistant IA métier' }, deliverables: ['Un usage prioritaire cadré', 'Des données et accès délimités', 'Des réponses évaluées sur vos cas'],
    cases: [
      ['Qualifier une demande entrante', 'Votre formulaire reçoit un texte libre. L’assistant en extrait le type de projet, les contraintes et les informations manquantes, puis prépare une fiche dans le CRM. Une demande ambiguë passe en revue humaine ; l’IA ne promet ni prix ni délai au prospect.'],
      ['Répondre avec votre documentation', 'Un collaborateur pose une question sur un produit ou une procédure. Le système recherche dans les documents autorisés et présente une réponse accompagnée de ses références. Si les sources ne permettent pas de conclure, le parcours propose une escalade au lieu d’inventer une réponse.'],
      ['Préparer un rapport depuis des fichiers', 'Des exports CSV ou Excel sont contrôlés et agrégés par du code déterministe. OpenAI aide ensuite à expliquer les variations et à rédiger une synthèse. Les montants et indicateurs restent calculés, traçables et accessibles à la personne qui valide le rapport.'],
    ],
    context: ['ChatGPT est une interface de travail ; une intégration applicative passe généralement par les API et des accès propres au projet. Un abonnement de conversation ne remplace pas le budget API. Nous choisissons les documents, les actions autorisées et le format de réponse avant le modèle. La restitution peut vivre dans votre [application web](/creation-application-web), un CRM ou un scénario [n8n](/expertise/n8n).', 'Nous préparons un jeu de demandes représentatives, incluant les questions sans réponse, les documents contradictoires et les tentatives de détournement. Le dispositif limite ce qui peut être lu et exécuté. Les secrets restent côté serveur ; les actions sensibles demandent une confirmation. Le coût par traitement et les erreurs observées servent à décider si le pilote mérite d’être étendu.'],
    process: [['Délimiter', 'Choisir un utilisateur, une tâche, les sources autorisées et ce qui reste hors périmètre. Définir le résultat attendu avant de connecter des outils.'], ['Connecter', 'Préparer la recherche documentaire ou les appels de fonctions et contrôler les entrées. Relier la sortie structurée aux champs réellement attendus par le système cible.'], ['Évaluer', 'Comparer les réponses à des exemples validés par votre équipe. Mesurer les oublis, les erreurs et les cas où une réponse doit être refusée.'], ['Déployer', 'Mettre en service sur un périmètre restreint, avec quotas, traces utiles et validation humaine. Prévoir le suivi quand les documents ou les modèles évoluent.']],
    fit: ['Des demandes variées arrivent en texte libre et leur première lecture mobilise votre équipe.', 'Vos documents de référence sont identifiables, à jour et accessibles selon des droits explicites.', 'Une personne peut contrôler les sorties et définir ce qui constitue une réponse acceptable.'],
    limits: ['Une réponse probabiliste ne remplace pas une règle comptable, une décision réglementée ou un calcul exact.', 'Un assistant documentaire ne garantit pas à lui seul l’absence d’erreurs ou de divulgation de données.', 'Les coûts API, la conservation et les engagements contractuels dépendent du service et de la configuration retenus.'],
    faq: [['ChatGPT et l’API OpenAI sont-ils la même chose ?', 'Non. ChatGPT est une application, tandis que les API servent à intégrer les capacités des modèles dans un autre logiciel. Les accès, la facturation et les conditions du service sont à étudier séparément.'], ['Peut-on connecter un assistant OpenAI à notre CRM ?', 'Oui si le CRM propose un connecteur ou une API adaptée. Nous définissons les champs accessibles, les actions autorisées et les validations nécessaires avant toute écriture.'], ['L’assistant peut-il travailler uniquement sur nos documents ?', 'Nous pouvons limiter les sources accessibles au périmètre convenu et demander des références. Cela ne dispense pas d’évaluer la qualité des réponses ni de contrôler les droits documentaires.'], ['Comment éviter les réponses inventées dans un chatbot métier ?', 'Avec des sources identifiables, des formats de sortie contrôlés, des évaluations sur vos exemples et un mécanisme d’abstention. Aucun réglage unique ne garantit une exactitude absolue.'], ['Faut-il envoyer tous nos fichiers à OpenAI ?', 'Non. Nous sélectionnons les seules données nécessaires et examinons les conditions de traitement avant l’intégration. Les secrets et informations inutiles au cas d’usage sont exclus.']],
    connections: [{ slug: 'n8n', reason: 'Orchestrer la qualification, l’enregistrement CRM et la notification à un responsable.' }, { slug: 'react', reason: 'Créer une interface métier pour relire, corriger et approuver les propositions.' }, { slug: 'python', reason: 'Calculer et contrôler les données avant de demander une synthèse en langage naturel.' }, { slug: 'claude', reason: 'Comparer une autre approche sur le même jeu de documents et les mêmes critères.' }],
    sources: [{ label: 'OpenAI : recherche dans les fichiers', href: 'https://developers.openai.com/api/docs/guides/tools-file-search' }, { label: 'OpenAI : appels de fonctions', href: 'https://developers.openai.com/api/docs/guides/function-calling' }, { label: 'OpenAI : données et contrôles', href: 'https://developers.openai.com/api/docs/guides/your-data' }],
    visual: { kind: 'assistant', title: 'La demande devient une fiche exploitable.', input: ['Formulaire : projet de boutique', 'Budget indiqué : à préciser', 'Source : demande du prospect'], output: ['Type : e-commerce', 'Question à poser : catalogue ?', 'Validation humaine avant réponse'] },
  },
  {
    slug: 'codex', name: 'OpenAI Codex', logo: '/brands/openai-official.svg', color: '#202020', category: 'Agents de développement',
    title: 'OpenAI Codex : agents de développement & maintenance | Litus', description: 'Intégrer Codex à vos workflows de développement : reprise de code, refactoring, tests et maintenance, avec revue humaine et accès maîtrisés.',
    headline: 'Déléguer une tâche de code.', accent: 'Garder la maîtrise de la livraison.', intro: 'Une anomalie à reproduire, un module à clarifier ou une série de tests à préparer : Litus utilise Codex comme un agent de développement supervisé. Nous organisons le contexte, les permissions et la revue pour que le résultat puisse être compris, maintenu et livré par votre équipe.',
    service: { href: '/developpement-web-sur-mesure', label: 'Organiser votre développement sur mesure' }, deliverables: ['Des tâches et règles explicites', 'Une revue du code proposé', 'Une livraison sous votre contrôle'],
    cases: [['Reprendre un module fragile', 'Sur une branche dédiée, l’agent peut explorer un parcours, proposer une simplification et préparer les changements associés. Litus contrôle les règles métier, les dépendances et les différences de comportement. Le refactoring ne devient pas un prétexte à réécrire une application qui fonctionne.'], ['Préparer une couverture de tests utile', 'À partir d’un scénario métier et de ses cas limites, Codex aide à écrire des tests de non-régression. Nous évaluons ce qu’ils prouvent réellement : un test qui reproduit aveuglément une erreur existante ne protège pas le produit. Les données de test restent séparées de la production.'], ['Automatiser une maintenance répétitive', 'Une tâche technique récurrente peut préparer un diagnostic, une proposition de mise à jour ou un correctif isolé. Le workflow crée un résultat à relire, pas une publication aveugle. Les changements de dépendances, migrations et déploiements gardent leurs propres étapes d’approbation.']],
    context: ['Codex intervient sur le travail de développement : compréhension d’un dépôt, propositions de modifications, commandes autorisées et préparation des vérifications. Ce rôle diffère d’un assistant client intégré avec [OpenAI](/expertise/openai). Pour votre produit, le point de départ est une tâche dont on peut décrire le résultat, les fichiers concernés et les critères de validation.', 'Nous définissons les consignes du dépôt, les environnements autorisés et les commandes à soumettre à validation. L’agent ne reçoit pas par défaut les clés de production ni un droit de publication général. Un développeur reste responsable de la revue, des arbitrages d’architecture et de la livraison. Les changements sur [Next.js](/expertise/nextjs) ou [.NET](/expertise/dotnet) suivent les contraintes de leur application, pas une recette universelle.'],
    process: [['Préparer le dépôt', 'Identifier les conventions, scripts et zones sensibles. Fournir un contexte utile sans exposer les secrets ni des exports clients dont la tâche n’a pas besoin.'], ['Définir la tâche', 'Formuler un objectif limité, un comportement attendu et des cas de validation. Séparer une correction de bug des améliorations non indispensables au même travail.'], ['Superviser la proposition', 'Observer les fichiers modifiés, comprendre les choix et contrôler les commandes. Refuser les changements hors périmètre et les dépendances ajoutées sans justification.'], ['Relire et livrer', 'Revoir le diff, exécuter les vérifications autorisées et documenter les limites. La publication suit le circuit de validation prévu pour le produit.']],
    fit: ['Votre dépôt est accessible et une personne connaît les règles métier à préserver.', 'Des tâches répétitives ou bornées peuvent être décrites avec des critères de résultat précis.', 'L’équipe souhaite accélérer la préparation des changements sans supprimer la revue technique.'], limits: ['Un agent ne garantit pas un code correct, sécurisé ou conforme au besoin sans revue.', 'Une base sans documentation ni environnement reproductible demande d’abord un travail de préparation.', 'Les tâches autonomes doivent être bornées en accès, durée et dépenses ; la production reste un environnement distinct.'],
    faq: [['Codex remplace-t-il le développeur Litus ?', 'Non. Il aide à réaliser des tâches de code et de maintenance. Le développeur garde la responsabilité du cadrage, de la revue, de la sécurité et de la livraison.'], ['Peut-on utiliser Codex sur un projet existant ?', 'Oui, après examen du dépôt et de ses contraintes. Nous commençons par une tâche réduite et vérifiable, sans imposer une migration globale de la stack.'], ['Codex peut-il publier directement en production ?', 'Ce n’est pas notre fonctionnement par défaut. Les permissions et les validations de déploiement sont définies explicitement ; un changement de code ne vaut pas autorisation de publication.'], ['Quels travaux déléguer à un agent de développement ?', 'Une correction ciblée, une exploration de code, la préparation de tests, une documentation technique ou un refactoring limité sont des points de départ possibles.'], ['Comment protéger nos secrets avec Codex ?', 'Nous séparons les environnements, limitons les accès et contrôlons les fichiers et commandes disponibles. Les conditions du service et les règles internes sont examinées avant de connecter un dépôt.']],
    connections: [{ slug: 'typescript', reason: 'S’appuyer sur des contrats de données explicites pendant une modification.' }, { slug: 'vercel', reason: 'Présenter une préproduction avant la validation et la mise en ligne.' }, { slug: 'nextjs', reason: 'Maintenir les routes, composants et parcours d’une application React.' }, { slug: 'n8n', reason: 'Relier une tâche technique aux notifications et étapes d’approbation de l’équipe.' }],
    sources: [{ label: 'Documentation officielle Codex', href: 'https://developers.openai.com/codex/' }, { label: 'Cas d’usage Codex', href: 'https://developers.openai.com/codex/use-cases' }, { label: 'Dépôt officiel Codex', href: 'https://github.com/openai/codex' }],
    visual: { kind: 'code', title: 'Une proposition. Une revue. Une livraison.', input: ['Issue : validation du formulaire', 'Branche : correction ciblée', 'Contexte : règles du dépôt'], output: ['Diff de code à relire', 'Tests de non-régression', 'Publication après validation'] },
  },
  {
    slug: 'claude', name: 'Claude / Anthropic', logo: '/brands/claude-official.png', color: '#c15f3c', category: 'Analyse documentaire & assistants IA', title: 'Intégration Claude & API Anthropic pour entreprise | Litus', description: 'Analyse de documents, extraction de données et assistants métier avec Claude : Litus intègre l’API Anthropic à vos outils et processus.',
    headline: 'Des documents à comprendre.', accent: 'Des décisions à préparer.', intro: 'Dossiers fournisseurs, comptes rendus, procédures ou pièces jointes : nous construisons des usages Claude qui extraient et structurent l’information utile. L’assistant prépare une lecture ; votre équipe conserve les références, les exceptions et le dernier mot sur les décisions importantes.',
    service: { href: '/creation-outils-ia', label: 'Cadrer votre analyse documentaire IA' }, deliverables: ['Une grille de lecture métier', 'Des réponses reliées aux sources', 'Des cas ambigus signalés'],
    cases: [['Extraire les champs d’un dossier', 'Une série de documents contient les coordonnées, dates et références à reprendre dans un outil métier. Claude propose une extraction selon un schéma défini. Les valeurs absentes ou contradictoires restent signalées ; une règle de contrôle empêche de remplir une donnée obligatoire avec une supposition.'], ['Comparer plusieurs propositions', 'Votre équipe veut lire des offres fournisseurs selon les mêmes critères : périmètre, délais, exclusions et conditions. Nous préparons une grille comparative avec les passages à consulter. Le résultat facilite la lecture mais ne remplace ni une analyse juridique ni la décision d’achat.'], ['Préparer une synthèse quotidienne', 'Un flux de messages et comptes rendus est regroupé par dossier avant analyse. L’assistant prépare les actions, échéances et questions ouvertes. La diffusion respecte les destinataires autorisés et ne donne pas accès à des documents qu’ils ne devraient pas consulter.']],
    context: ['L’application Claude et l’API Anthropic répondent à des usages différents. Pour un processus récurrent ou une fonctionnalité dans votre SaaS, nous cadrons une intégration serveur avec format de sortie, règles d’accès et budget de traitement. La lecture de documents longs ne supprime pas les limites de contexte : nous choisissons les pièces utiles et conservons leur provenance.', 'Le pilote compare les sorties à une lecture humaine sur des dossiers représentatifs. Les scans difficiles, tableaux incomplets et pièces incohérentes font partie des exemples à traiter. Nous pouvons associer [Python](/expertise/python) pour les calculs et [n8n](/expertise/n8n) pour les dépôts de fichiers et notifications. Les critères de sélection entre Claude et [OpenAI](/expertise/openai) restent la qualité observée, les conditions de données, les coûts et l’intégration.'],
    process: [['Définir la grille', 'Lister les informations à extraire et les décisions qui ne doivent pas être déléguées. Choisir le format et les références attendues dans le résultat.'], ['Préparer les pièces', 'Contrôler les formats, les droits et la qualité des fichiers. Écarter les données inutiles et identifier les documents qui nécessitent un traitement préalable.'], ['Confronter les réponses', 'Tester les dossiers simples, longs, ambigus et incomplets. Comparer les champs extraits et les références aux éléments validés par votre équipe.'], ['Intégrer la relecture', 'Transmettre un résultat à approuver dans le bon outil. Prévoir la correction, le rejet et le suivi des versions de la grille d’analyse.']],
    fit: ['Votre équipe relit souvent les mêmes types de documents selon des critères identifiables.', 'Les sources peuvent être utilisées légalement et leur accès peut être limité au bon périmètre.', 'Le résultat doit préparer un tableau, une synthèse ou une tâche avec une étape de contrôle.'], limits: ['Un contexte long n’est pas une garantie de lecture exhaustive ni d’absence d’omission.', 'Un document reçu peut contenir des instructions malveillantes : il reste une donnée, pas une autorité.', 'Pour les dossiers sensibles, les conditions d’hébergement, de conservation et de traitement sont à valider avant tout transfert.'],
    faq: [['Quels documents peut-on analyser avec Claude ?', 'Nous étudions les formats et la qualité de vos pièces : PDF, textes, tableaux ou contenus extraits. Un échantillon permet de vérifier le traitement réellement possible.'], ['Peut-on obtenir des références dans les synthèses Claude ?', 'Oui, le parcours peut conserver les documents et passages associés aux réponses. Leur exactitude et leur complétude restent à évaluer sur vos cas.'], ['Claude peut-il remplir automatiquement notre logiciel métier ?', 'Une intégration peut préparer les données pour ce logiciel. Nous définissons ensuite les champs autorisés, les contrôles et les cas qui nécessitent une validation humaine.'], ['Claude est-il préférable à OpenAI pour notre entreprise ?', 'Il n’existe pas de réponse universelle. Nous comparons les résultats sur les mêmes documents et critères, puis examinons les coûts, les conditions contractuelles et les connexions.'], ['Peut-on analyser des contrats avec Claude ?', 'L’outil peut préparer une extraction ou une comparaison de clauses. Cela ne constitue pas un avis juridique et les décisions contractuelles doivent rester revues par une personne compétente.']],
    connections: [{ slug: 'n8n', reason: 'Déclencher l’analyse à la réception d’un fichier et router les demandes de validation.' }, { slug: 'python', reason: 'Préparer les tableaux, contrôler les valeurs et produire les exports.' }, { slug: 'google-workspace', reason: 'Organiser les documents et restituer les résultats dans les espaces autorisés.' }, { slug: 'openai', reason: 'Comparer les approches d’assistance sur un besoin et un jeu de test communs.' }],
    sources: [{ label: 'Anthropic : prise en charge des PDF', href: 'https://platform.claude.com/docs/en/build-with-claude/pdf-support' }, { label: 'Anthropic : citations', href: 'https://platform.claude.com/docs/en/build-with-claude/citations' }, { label: 'Anthropic : outils', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview' }],
    visual: { kind: 'documents', title: 'Lire les pièces. Retrouver les sources.', input: ['Proposition fournisseur A', 'Proposition fournisseur B', 'Grille : délais / exclusions'], output: ['Tableau comparatif', 'Passages de référence', 'Points à faire confirmer'] },
  },
  {
    slug: 'n8n', name: 'n8n', logo: '/brands/n8n-official.svg', color: '#ea4b71', category: 'Workflows & agents IA', title: 'Expert n8n : automatisation, CRM & agents IA | Litus', description: 'Litus conçoit vos workflows n8n : formulaires, CRM, emails, API et agents IA. Des automatisations documentées avec gestion des erreurs et validation humaine.',
    headline: 'Les étapes se suivent.', accent: 'Votre équipe garde la main.', intro: 'Un formulaire ne devrait pas devenir trois recopies et une relance oubliée. Avec n8n, nous relions les étapes de votre fonctionnement : réception, contrôle, enrichissement, enregistrement et notification. L’IA intervient seulement lorsqu’une lecture ou une interprétation apporte quelque chose.',
    service: { href: '/automatisation', label: 'Automatiser votre processus métier' }, deliverables: ['Un workflow lisible et documenté', 'Des erreurs et reprises prévues', 'Des accès limités au besoin'],
    cases: [['Formulaire → IA → CRM → email', 'La demande est validée avant qualification par OpenAI ou Claude. Les champs utiles rejoignent le CRM, puis un email de réception est envoyé. Le scénario distingue un doublon, une adresse invalide et une qualification incertaine afin de ne pas transformer une erreur en action automatique.'], ['Un résumé quotidien des emails', 'Un scénario collecte uniquement les messages autorisés, les regroupe par dossier et prépare une synthèse avec les liens utiles. L’équipe reçoit les actions à relire plutôt qu’une copie de toute la messagerie. Les destinataires et la conservation des traces sont définis au cadrage.'], ['Synchroniser commandes et opérations', 'Une commande payée peut ouvrir un dossier, transmettre les informations de préparation et prévenir le responsable. Nous définissons quel outil fait référence pour chaque donnée. Les événements répétés, annulations et interruptions sont traités pour éviter la création de plusieurs dossiers pour une même vente.']],
    context: ['n8n orchestre les actions ; le CRM, le paiement et le modèle IA gardent leurs rôles respectifs. Nous privilégions les connecteurs existants quand ils couvrent le besoin et utilisons les [API](/integrations-api) pour les échanges spécifiques. Le workflow documente les entrées, les règles et la sortie attendue : une succession de nœuds n’est utile que si l’équipe comprend son fonctionnement.', 'Le choix entre cloud et auto-hébergement dépend des contraintes d’exploitation, des données et des ressources disponibles. Une instance hébergée par vous demande maintenance, sauvegardes et supervision ; elle n’est pas automatiquement plus sûre ni conforme par nature. Nous comparons aussi [Make](/expertise/make) et [Zapier](/expertise/zapier) lorsque leur simplicité convient mieux au processus.'],
    process: [['Cartographier', 'Décrire le déclencheur, les données, les logiciels et les personnes responsables. Identifier les exceptions avant de construire le chemin qui fonctionne dans le cas idéal.'], ['Assembler', 'Configurer les connexions et les correspondances de champs. Définir un identifiant métier pour reconnaître les événements répétés et éviter les créations en double.'], ['Éprouver', 'Tester une donnée absente, une API indisponible et une reprise. Vérifier ce que l’équipe voit, qui reçoit l’alerte et comment relancer sans multiplier les actions.'], ['Transmettre', 'Livrer le scénario, sa documentation et les consignes d’exploitation. Définir les accès, sauvegardes, seuils de consommation et responsabilités après la mise en service.']],
    fit: ['Plusieurs applications participent à un même processus et leurs API permettent les opérations nécessaires.', 'Vous devez combiner des règles déterministes, des branchements et parfois une étape d’interprétation IA.', 'Une personne peut suivre les incidents et valider les évolutions du scénario avec les équipes métier.'], limits: ['Un connecteur ne donne pas des droits ou fonctionnalités absents du logiciel source.', 'L’auto-hébergement demande une exploitation réelle : mises à jour, supervision, secrets et sauvegardes.', 'Les licences, quotas et coûts des outils connectés s’ajoutent au coût de conception du workflow.'],
    faq: [['Litus peut-il reprendre un workflow n8n existant ?', 'Oui. Nous commençons par les exécutions, les accès et les erreurs observées pour comprendre le flux avant de modifier ses nœuds.'], ['Faut-il héberger n8n sur notre serveur ?', 'Pas nécessairement. Le choix entre service cloud et instance auto-hébergée dépend de vos contraintes et de la capacité à exploiter le service dans la durée.'], ['Un workflow n8n doit-il obligatoirement utiliser une IA ?', 'Non. Les règles, filtres et transformations classiques restent préférables lorsqu’ils suffisent. Une IA est ajoutée pour un besoin précis de compréhension ou de génération.'], ['Que se passe-t-il si un service connecté ne répond plus ?', 'Nous définissons les alertes, les nouvelles tentatives et les points de reprise. Le traitement doit éviter de répéter une action déjà effectuée, notamment un email ou une création de dossier.'], ['Peut-on connecter n8n à Shopify, Gmail et HubSpot ?', 'Ces usages sont à étudier avec les comptes et autorisations disponibles. Nous vérifions les opérations couvertes par les connecteurs et complétons par API si nécessaire.']],
    connections: [{ slug: 'openai', reason: 'Qualifier un texte libre ou préparer une réponse selon un format défini.' }, { slug: 'claude', reason: 'Extraire et résumer les documents transmis dans un workflow.' }, { slug: 'hubspot', reason: 'Créer ou mettre à jour la fiche commerciale sans perdre la source de la demande.' }, { slug: 'google-workspace', reason: 'Relier les fichiers, messages et tableaux au fonctionnement de votre équipe.' }],
    sources: [{ label: 'n8n : automatisation et IA', href: 'https://n8n.io/ai/' }, { label: 'n8n : agents et validation humaine', href: 'https://n8n.io/ai-agents/' }, { label: 'n8n : ressources de marque', href: 'https://n8n.io/press/' }],
    visual: { kind: 'flow', title: 'Une demande. Quatre étapes maîtrisées.', input: ['Formulaire reçu', 'Contrôles des champs', 'Qualification IA'], output: ['Fiche CRM mise à jour', 'Email de réception', 'Exception : revue humaine'] },
  },
  {
    slug: 'google-workspace', name: 'Google Workspace', logo: '/brands/google-workspace.png', color: '#4285f4', category: 'Collaboration & données métier', title: 'Google Workspace : intégrations & automatisation | Litus', description: 'Reliez Gmail, Drive, Sheets et vos outils métier avec Litus : suivi des demandes, génération de documents et automatisations Google Workspace.',
    headline: 'Gmail, Drive, Sheets.', accent: 'Un fonctionnement partagé.', intro: 'Votre équipe travaille déjà dans Google Workspace, mais les informations circulent encore à la main. Nous organisons les documents, les tableaux et les échanges pour qu’un dossier reste compréhensible de sa réception à son suivi, sans transformer un tableur en logiciel incontrôlable.',
    service: { href: '/integrations-api', label: 'Relier Workspace à vos outils métier' }, deliverables: ['Des sources de référence définies', 'Des partages et accès cadrés', 'Des automatisations documentées'],
    cases: [['Créer un dossier après un formulaire', 'Une demande validée peut créer une ligne de suivi, préparer un dossier Drive et prévenir le responsable. Le nommage, les champs et les droits sont définis avant l’automatisation. Un identifiant unique relie ensuite le message initial au document et au statut du dossier.'], ['Générer un compte rendu cohérent', 'Les données validées d’un tableau alimentent un modèle de document. L’équipe relit le contenu avant son envoi et conserve une version identifiable. Les cellules absentes ou incohérentes bloquent les informations concernées plutôt que de produire un document qui semble complet à tort.'], ['Synchroniser un suivi avec le CRM', 'Les équipes commerciales peuvent garder un tableau de lecture sans recopier chaque changement de statut. Nous définissons les données modifiables, le sens des échanges et la source de vérité. Les colonnes ne deviennent pas une porte d’entrée pour écraser silencieusement les données du CRM.']],
    context: ['Apps Script peut automatiser des actions dans les outils Google ; les API Workspace permettent des échanges plus spécifiques. Le bon choix dépend des autorisations, du volume et de la fréquence. Un déclencheur simple n’a pas les mêmes capacités qu’un déclencheur installé. Nous examinons ces limites avant de promettre un scénario de messagerie ou de traitement périodique.', 'L’organisation des accès fait partie du projet : propriétaires des fichiers, comptes utilisés pour les scripts, départ d’un collaborateur et partage externe. Pour les flux impliquant d’autres logiciels, [n8n](/expertise/n8n) ou [Make](/expertise/make) peut assurer l’orchestration. Si les données et règles deviennent trop complexes pour Sheets, une [application métier](/creation-application-web) est une alternative à comparer.'],
    process: [['Observer les usages', 'Recenser les tableaux, boîtes et dossiers réellement utilisés. Identifier les doublons et les informations dont la personne en charge a besoin pour traiter une demande.'], ['Organiser les données', 'Définir les colonnes, les identifiants, les statuts et les conventions de fichiers. Prévoir les champs qui restent sous contrôle humain avant toute génération documentaire.'], ['Configurer les échanges', 'Choisir Apps Script, API ou orchestrateur en fonction des droits et du volume. Tester sur des dossiers dédiés, pas sur une copie non maîtrisée de la production.'], ['Passer le relais', 'Documenter les comptes d’exécution, les alertes et la reprise des automatisations. Vérifier ce qui se passe lorsqu’un accès change ou qu’un quota est atteint.']],
    fit: ['L’équipe utilise déjà Workspace et souhaite fiabiliser un processus connu sans remplacer tous ses outils.', 'Les données sont suffisamment structurées pour définir des colonnes et des règles de mise à jour.', 'Les propriétaires des fichiers et comptes peuvent accorder les accès strictement nécessaires au scénario.'], limits: ['Un tableur partagé ne convient pas à toutes les contraintes transactionnelles ou aux droits métier complexes.', 'Les quotas, autorisations et fonctions disponibles varient selon les API et comptes utilisés.', 'L’automatisation ne corrige pas à elle seule des fichiers dupliqués, mal nommés ou accessibles à trop de personnes.'],
    faq: [['Peut-on automatiser Google Sheets sans changer nos tableaux ?', 'Nous pouvons partir de vos fichiers, mais une normalisation des colonnes, statuts et identifiants est parfois nécessaire pour rendre le traitement fiable.'], ['Peut-on générer des documents depuis Google Workspace ?', 'Oui, à partir de modèles et de données validées. Le périmètre inclut la mise en forme, les champs manquants, les droits et l’étape de relecture.'], ['Les scripts Workspace continuent-ils après le départ d’un salarié ?', 'Cela dépend de leur propriétaire et des comptes d’exécution. Nous documentons ces dépendances et préparons la continuité avec votre administrateur.'], ['Faut-il choisir Apps Script ou n8n ?', 'Apps Script peut convenir à un flux centré sur Google. Un orchestrateur devient intéressant pour plusieurs logiciels, des branches ou un suivi des exécutions plus large.'], ['Workspace peut-il servir de CRM ?', 'Un tableau peut suffire à un suivi simple. Pour des pipelines, permissions et historiques plus avancés, nous comparons une intégration CRM plutôt que de multiplier les scripts.']],
    connections: [{ slug: 'n8n', reason: 'Orchestrer les dossiers, messages et validations entre plusieurs applications.' }, { slug: 'hubspot', reason: 'Relier les tableaux de suivi aux données commerciales de référence.' }, { slug: 'gemini', reason: 'Étudier l’assistance sur les contenus Google en tenant compte des comptes et permissions.' }, { slug: 'python', reason: 'Traiter des exports volumineux avant de restituer un tableau lisible.' }], sources: [{ label: 'Google Workspace : développer des intégrations', href: 'https://developers.google.com/workspace/guides/get-started' }, { label: 'Apps Script : déclencheurs', href: 'https://developers.google.com/apps-script/guides/triggers' }, { label: 'API Google Sheets', href: 'https://developers.google.com/workspace/sheets/api/guides/concepts' }],
    visual: { kind: 'workspace', title: 'Le même dossier, dans les bons outils.', input: ['Gmail : demande reçue', 'Sheets : suivi du dossier', 'Drive : pièces accessibles'], output: ['Responsable identifié', 'Document à relire', 'Historique partagé'] },
  },
]
