import type { ExpertisePage } from './types'

export const technicalPages: ExpertisePage[] = [
  {
    slug: 'python', title: 'Développeur Python : automatisation, données & API | Litus',
    description: 'Développement Python sur mesure : traitement de fichiers, automatisation métier, API et outils internes. Un développeur dédié, des flux documentés et exploitables.',
    headline: 'Vos données circulent.', accent: 'Votre équipe avance.',
    intro: 'Des exports à rapprocher, des fichiers à nettoyer, un logiciel qui ne communique pas avec les autres : notre développeur dédié utilise Python pour transformer ces opérations en traitements explicites, contrôlables et maintenables.',
    action: 'Parler de mon projet Python', deliverables: ['Scripts et API documentés', 'Données contrôlées', 'Exécution et reprise prévues'],
    sections: [
      { id: 'usages-python', nav: 'Cas d’usage', kind: 'cards', eyebrow: 'Développement Python sur mesure', title: 'Ce qui peut sortir du tableur.', items: [
        { title: 'Rapprocher des exports', text: 'Assembler des fichiers de commandes, vérifier les références et signaler les lignes incohérentes avant import. Le résultat doit être relisible : quelles données ont été conservées, corrigées ou rejetées ?' },
        { title: 'Automatiser un traitement', text: 'Préparer un rapport récurrent, synchroniser un catalogue ou classer des documents selon des règles définies avec votre équipe. Nous prévoyons les erreurs et les relances, pas seulement le scénario où tout fonctionne.' },
        { title: 'Exposer une API métier', text: 'Mettre un calcul ou une recherche à disposition d’une [application web](/creation-application-web). L’API encadre les entrées et les droits ; elle ne laisse pas le navigateur accéder directement à vos données internes.' },
        { title: 'Relier un service IA', text: 'Extraire ou classer des informations avec un service adapté, puis faire valider les résultats ambigus. Un [outil IA](/creation-outils-ia) doit prévoir son coût, les données transmises et les possibilités de correction humaine.' },
      ] },
      { id: 'fiabilite-python', nav: 'Fiabilité', kind: 'issues', eyebrow: 'Reprendre un script existant', title: 'Le script fonctionne… jusqu’au prochain fichier.', items: [
        { symptom: 'Un import crée des doublons', diagnosis: 'Clés métier, historique des imports et règles de rapprochement.', action: 'Identifier chaque traitement et rendre les relances idempotentes lorsque le système cible le permet.' },
        { symptom: 'Une tâche se bloque sans alerte', diagnosis: 'Délais des appels externes, journaux, planification et dépendances.', action: 'Encadrer les délais, limiter les tentatives et rendre les échecs visibles pour la personne qui exploite le flux.' },
        { symptom: 'Le code ne tourne que sur un poste', diagnosis: 'Version Python, bibliothèques, secrets et chemins locaux.', action: 'Documenter l’environnement, isoler les dépendances et préparer un mode de lancement reproductible.' },
      ] },
      { id: 'methode-python', nav: 'Mise en œuvre', kind: 'workflow', eyebrow: 'Du besoin au traitement', title: 'D’abord un échantillon représentatif.', steps: [
        { title: 'Observer', text: 'Recueillir des fichiers anonymisés et comprendre les règles de votre équipe.' },
        { title: 'Définir', text: 'Écrire le résultat attendu, les rejets possibles et les accès autorisés.' },
        { title: 'Construire', text: 'Développer le traitement et son compte rendu, avec une exécution de démonstration.' },
        { title: 'Transmettre', text: 'Préparer le lancement, les alertes et la procédure de reprise avec votre référent.' },
      ], note: 'Un script n’est pas une automatisation autonome tant que son déclenchement et son exploitation ne sont pas définis.' },
      { id: 'choisir-python', nav: 'Quand le choisir', kind: 'choice', eyebrow: 'Le bon périmètre', title: 'Python ne remplace pas tous vos outils.', yes: ['Traitements de fichiers et échanges entre plusieurs systèmes.', 'Règles de transformation qui dépassent un simple connecteur.', 'Service serveur derrière une interface [React](/expertise/react).'], no: ['Un connecteur existant répond déjà au besoin sans développement.', 'Une contrainte de temps réel strict demande une architecture spécialisée.', 'La principale difficulté est l’interface : elle mérite un chantier distinct.'] },
    ],
    faq: [
      { question: 'Pouvez-vous reprendre un script Python créé en interne ?', answer: 'Oui, après examen du code, des dépendances et de quelques entrées représentatives. Nous définissons les comportements à conserver, les erreurs connues et l’environnement cible avant de proposer une reprise.' },
      { question: 'Python peut-il échanger avec notre CRM ou notre ERP ?', answer: 'Oui si le logiciel fournit une API, un export ou une autre interface autorisée. Le cadrage porte sur les droits, quotas, formats, identifiants métier et mécanismes de reprise. Un accès public au site ne suffit pas à autoriser une extraction de ses données.' },
      { question: 'Faut-il garder un ordinateur allumé ?', answer: 'Pas nécessairement. Un serveur, une tâche planifiée ou un service adapté peut exécuter le traitement. Le choix dépend de la durée, de la fréquence et de l’accès aux données ; un script local n’est pas automatiquement un service hébergé.' },
      { question: 'Python accélère-t-il toutes les opérations avec asyncio ?', answer: 'Non. asyncio sert surtout à organiser des entrées-sorties concurrentes lorsque les bibliothèques utilisées le permettent. Un calcul lourd demande d’autres choix. Nous mesurons d’abord ce qui prend du temps et ce que le système distant autorise.' },
    ],
    connections: [{ slug: 'react', reason: 'Donner une interface au traitement et à ses résultats.' }, { slug: 'dotnet', reason: 'Comparer les environnements serveur selon votre existant.' }, { slug: 'labview', reason: 'Exploiter des exports de mesure dans un traitement séparé.' }],
    reading: { href: '/automatisation', label: 'Automatiser une opération métier', reason: 'Partir des entrées, des décisions et des erreurs à gérer.' },
    sources: [{ label: 'Python : domaines d’application', href: 'https://www.python.org/about/apps/' }, { label: 'Python : lecture et écriture CSV', href: 'https://docs.python.org/3/library/csv.html' }, { label: 'Python : entrées-sorties asynchrones', href: 'https://docs.python.org/3/library/asyncio.html' }],
    cta: { title: 'Montrez-nous l’opération qui se répète.', text: 'Quelques fichiers anonymisés et le résultat souhaité permettent souvent de définir un premier périmètre utile.', label: 'Présenter mon automatisation' },
  },
  {
    slug: 'csharp', title: 'Développeur C# : logiciels métier & intégrations | Litus',
    description: 'Un développeur C# dédié pour vos outils internes, règles métier, API et logiciels sur mesure. Reprise de code, intégrations et interfaces adaptées aux usages.',
    headline: 'Vos règles métier.', accent: 'Un logiciel qui les comprend.',
    intro: 'Planifier une intervention, appliquer des droits, suivre un dossier ou relier deux logiciels : C# permet de structurer cette logique. Chez Litus, un développeur dédié aux projets techniques travaille sur ces besoins au-delà du site vitrine.',
    action: 'Présenter mon projet C#', deliverables: ['Règles métier explicites', 'Accès maîtrisés', 'Code et livraison documentés'],
    sections: [
      { id: 'applications-csharp', nav: 'Applications', kind: 'cards', eyebrow: 'Des logiciels pour vos opérations', title: 'Le développement C# en situations concrètes.', items: [
        { title: 'Gestion de dossiers', text: 'Un outil pour suivre une demande de son ouverture à sa clôture : responsables, pièces jointes, statuts et historique. Les transitions autorisées sont définies avec les personnes qui utilisent réellement le logiciel.' },
        { title: 'Interface d’atelier', text: 'Un écran pour identifier un lot, lancer une opération autorisée et enregistrer un résultat. Les périphériques, le poste de travail et la connexion réseau font partie du cadrage, pas des détails réglés après livraison.' },
        { title: 'Connecteur entre logiciels', text: 'Relier une base existante à une [API](/integrations-api), transformer un format ou synchroniser un référentiel. Chaque échange doit gérer les réponses tardives, les doublons et les droits d’accès.' },
        { title: 'Moteur de calcul', text: 'Centraliser une règle de tarification, un calcul de disponibilité ou une validation complexe. Le code distingue les données saisies, la règle applicable et les informations nécessaires pour expliquer le résultat.' },
      ] },
      { id: 'langage-csharp', nav: 'C# et .NET', kind: 'prose', eyebrow: 'Comprendre la distinction', title: 'C# est le langage. .NET est la plateforme.', paragraphs: ['C# fournit les types et les constructions utilisées pour écrire le programme. [.NET](/expertise/dotnet) apporte notamment son environnement d’exécution et ses bibliothèques. Un projet peut donc employer les deux sans qu’il s’agisse de deux applications séparées.', 'Pour une interface web, nous pouvons associer une API ASP.NET Core à [React](/expertise/react). Pour un logiciel installé sur un poste, le choix du framework d’interface dépend du système cible et des périphériques requis.', 'C# ne rend pas une application automatiquement sécurisée. Les autorisations, les validations d’entrée et le stockage des secrets restent des responsabilités à concevoir et à contrôler.'] },
      { id: 'reprise-csharp', nav: 'Reprise de code', kind: 'workflow', eyebrow: 'Faire évoluer l’existant', title: 'Comprendre avant de réécrire.', steps: [
        { title: 'Reproduire', text: 'Obtenir le code, les dépendances et une procédure de lancement.' },
        { title: 'Cartographier', text: 'Identifier les écrans, règles métier et connexions sensibles.' },
        { title: 'Cibler', text: 'Choisir un parcours prioritaire et expliciter les cas limites.' },
        { title: 'Livrer', text: 'Préparer la version, sa documentation et le retour à l’état précédent.' },
      ], note: 'La compatibilité d’un ancien composant Windows ou d’une bibliothèque propriétaire doit être examinée avant de promettre une migration multiplateforme.' },
      { id: 'choisir-csharp', nav: 'Le bon choix', kind: 'choice', eyebrow: 'Un choix situé', title: 'Le langage doit s’intégrer à votre environnement.', yes: ['Vous maintenez déjà des composants C# ou .NET.', 'Votre outil comporte une logique métier structurée et durable.', 'Votre projet doit dialoguer avec des logiciels ou bibliothèques compatibles.'], no: ['Vous attendez seulement un site de présentation administrable.', 'Une dépendance impose un système incompatible avec votre cible.', 'Le coût de maintenance serait disproportionné face à une solution existante.'] },
    ],
    faq: [
      { question: 'C# sert-il uniquement à créer des logiciels Windows ?', answer: 'Non : C# peut notamment servir à des applications serveur exécutées avec .NET sur différents systèmes. En revanche, certaines technologies d’interface comme WPF et Windows Forms restent liées à Windows. La compatibilité se décide composant par composant.' },
      { question: 'Peut-on garder notre interface et remplacer seulement le backend ?', answer: 'C’est possible si les échanges sont suffisamment définis. Nous examinons le contrat des API, la connexion utilisateur et les erreurs attendues afin de séparer une évolution technique d’une refonte visuelle.' },
      { question: 'Pouvez-vous intervenir sur un logiciel sans documentation ?', answer: 'Oui, avec une première étape de compréhension. Le code source, une version exécutable et les explications d’un utilisateur référent permettent de reconstituer progressivement le fonctionnement. Le périmètre dépend de ce qui est effectivement disponible.' },
      { question: 'Livrez-vous seulement le code source ?', answer: 'Le périmètre de livraison doit préciser le code, la configuration, les dépendances, le mode de déploiement et les consignes de reprise. Nous le définissons avant le développement, avec une séparation claire des licences tierces.' },
    ],
    connections: [{ slug: 'dotnet', reason: 'Exécuter et déployer l’application C#.' }, { slug: 'react', reason: 'Créer les écrans d’un outil accessible dans le navigateur.' }, { slug: 'typescript', reason: 'Décrire les échanges entre l’interface et l’API.' }],
    reading: { href: '/creation-application-web', label: 'Construire une application métier', reason: 'Définir les parcours, les accès et le périmètre de la première version.' },
    sources: [{ label: 'Microsoft : présentation de C#', href: 'https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/overview' }, { label: 'Microsoft : introduction à .NET', href: 'https://learn.microsoft.com/en-us/dotnet/core/introduction' }, { label: 'Microsoft : migration d’applications .NET', href: 'https://learn.microsoft.com/en-us/dotnet/core/porting/' }],
    cta: { title: 'Un logiciel à créer ou à reprendre ?', text: 'Partons d’un écran, d’un processus ou du code existant pour définir une intervention concrète.', label: 'Échanger avec notre développeur' },
  },
  {
    slug: 'dotnet', title: 'Développement .NET : API, applications & modernisation | Litus',
    description: 'Litus développe et reprend vos applications .NET : API ASP.NET Core, services métier, intégrations et modernisation. Une architecture adaptée à votre exploitation.',
    headline: 'Une application utile.', accent: 'Une base qui tient la suite.',
    intro: 'Le projet ne s’arrête pas à un écran fonctionnel. Avec .NET, notre développeur dédié prépare aussi les services, les échanges de données et les conditions d’exploitation d’une application métier.',
    action: 'Cadrer mon application .NET', deliverables: ['API et services structurés', 'Environnements séparés', 'Livraison exploitable'],
    sections: [
      { id: 'services-dotnet', nav: 'Interventions', kind: 'cards', eyebrow: 'Développement .NET sur mesure', title: 'Relier les interfaces à votre activité.', items: [
        { title: 'API ASP.NET Core', text: 'Fournir des routes pour consulter un dossier, enregistrer une demande ou modifier un statut. Le serveur applique les règles et les autorisations, indépendamment de ce qu’affiche le navigateur.' },
        { title: 'Service en arrière-plan', text: 'Traiter des imports ou des files de travail sans bloquer l’utilisateur. Nous précisons les déclencheurs, les limites de durée et la personne alertée lorsqu’une tâche échoue.' },
        { title: 'Application interne', text: 'Centraliser une opération aujourd’hui répartie entre emails et fichiers. L’outil peut réunir un tableau de suivi, une recherche et un historique, avec des droits adaptés aux différents rôles.' },
        { title: 'Modernisation progressive', text: 'Évaluer les dépendances d’une application existante, isoler un premier composant puis faire évoluer le reste. Une migration depuis .NET Framework n’est pas présentée comme un simple changement de numéro de version.' },
      ] },
      { id: 'architecture-dotnet', nav: 'Architecture', kind: 'prose', eyebrow: 'Choisir une base exploitable', title: 'Ni microservices par réflexe, ni boîte noire.', paragraphs: ['Un service bien séparé de son interface peut être plus facile à faire évoluer. Cela ne signifie pas multiplier les services : pour de nombreux outils internes, une application structurée avec une seule base de déploiement reste plus lisible.', 'Nous choisissons une version de .NET encore prise en charge au moment du projet et vérifions les dépendances. Le système d’exploitation, l’hébergement, les accès aux données et les contraintes de votre équipe guident le choix.', 'Une interface [React](/expertise/react), un outil existant ou une boutique peuvent consommer les mêmes services via des [API](/integrations-api). Les données sensibles et les secrets restent dans les environnements prévus pour les protéger.'] },
      { id: 'livraison-dotnet', nav: 'Livraison', kind: 'workflow', eyebrow: 'Préparer la mise en service', title: 'Ce qui accompagne la première version.', steps: [
        { title: 'Contrats', text: 'Décrire les entrées, les réponses et les règles d’accès.' },
        { title: 'Environnement', text: 'Séparer développement, recette et production, avec les bons secrets.' },
        { title: 'Exploitation', text: 'Prévoir les journaux utiles, sauvegardes et points de supervision.' },
        { title: 'Évolution', text: 'Documenter les mises à jour et les responsabilités de maintenance.' },
      ], note: 'Un déploiement réussi ne prouve pas qu’un parcours métier est correct : les critères de recette restent définis avec votre équipe.' },
      { id: 'choisir-dotnet', nav: 'Arbitrages', kind: 'choice', eyebrow: 'Le contexte avant la stack', title: 'Quand .NET mérite sa place.', yes: ['Vous cherchez une API ou un service métier maintenable.', 'Votre environnement utilise déjà [C#](/expertise/csharp).', 'L’exploitation et les intégrations comptent autant que l’interface.'], no: ['Votre besoin tient dans un CMS déjà en place.', 'Une bibliothèque historique ne fonctionne pas sur le système visé.', 'La migration globale présente plus de risques qu’une évolution par étapes.'] },
    ],
    faq: [
      { question: '.NET et .NET Framework sont-ils interchangeables ?', answer: 'Non. .NET Framework correspond à une branche historique liée à Windows. Le .NET moderne dispose d’un autre cycle d’évolution et d’une portée multiplateforme. La migration dépend des API, bibliothèques et composants graphiques utilisés.' },
      { question: 'Une API .NET peut-elle alimenter un site React ou Next.js ?', answer: 'Oui. L’interface échange avec les routes exposées par le backend. Nous cadrons l’authentification, les autorisations, les formats de réponse, les erreurs et la mise en cache, plutôt que de nous limiter à la connexion entre les deux technologies.' },
      { question: 'Faut-il obligatoirement utiliser Azure ?', answer: 'Non. Le choix de l’hébergement dépend de l’application et de ses dépendances. Nous examinons l’environnement déjà exploité, les accès réseau, le budget et la responsabilité de maintenance avant de choisir une plateforme.' },
      { question: 'Peut-on moderniser sans tout arrêter ?', answer: 'Une évolution par étapes est souvent étudiable, mais elle n’est pas garantie sans analyse. La coexistence des versions, les migrations de données et les interfaces doivent permettre une transition maîtrisée et un retour en cas de problème.' },
    ],
    connections: [{ slug: 'csharp', reason: 'Écrire les règles métier et les services.' }, { slug: 'react', reason: 'Construire une interface indépendante du backend.' }, { slug: 'python', reason: 'Relier des traitements de données spécialisés.' }],
    reading: { href: '/developpement-web-sur-mesure', label: 'Définir un développement sur mesure', reason: 'Mettre les contraintes d’exploitation dans le périmètre du projet.' },
    sources: [{ label: 'Microsoft : introduction à .NET', href: 'https://learn.microsoft.com/en-us/dotnet/core/introduction' }, { label: 'Microsoft : Minimal APIs', href: 'https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-10.0' }, { label: 'Microsoft : moderniser une application', href: 'https://learn.microsoft.com/en-us/dotnet/core/porting/' }],
    cta: { title: 'Une API, un outil interne, un existant à faire évoluer.', text: 'Décrivons la première version utile et ce qu’il faudra pour l’exploiter sereinement.', label: 'Parler de mon projet .NET' },
  },
  {
    slug: 'labview', title: 'Développement LabVIEW : mesure, acquisition & bancs de test | Litus',
    description: 'Développement avec LabVIEW : interfaces opérateur, acquisition de données, bancs de mesure et reprise de VIs. Cadrage du matériel, des licences et de la traçabilité.',
    headline: 'Du signal mesuré.', accent: 'À une décision lisible.',
    intro: 'Acquérir une mesure, piloter une séquence ou présenter un résultat à un opérateur : notre développeur dédié peut intervenir sur des projets utilisant LabVIEW. Le point de départ reste votre matériel, votre programme existant et le protocole à respecter.',
    action: 'Présenter mon besoin LabVIEW', deliverables: ['Périmètre matériel défini', 'Interfaces opérateur lisibles', 'Mesures et erreurs traçables'],
    sections: [
      { id: 'usages-labview', nav: 'Cas d’usage', kind: 'cards', eyebrow: 'Au-delà du développement de sites', title: 'Des outils autour de la mesure.', items: [
        { title: 'Acquisition de données', text: 'Organiser la lecture de signaux issus d’un matériel compatible, leur affichage et leur enregistrement. La fréquence, les unités et les métadonnées du lot se définissent avant la construction de l’interface.' },
        { title: 'Banc d’essai', text: 'Enchaîner des étapes préparatoires, des mesures et un compte rendu. Les seuils et critères d’acceptation viennent de votre protocole ; Litus ne les invente pas à partir de l’écran à reproduire.' },
        { title: 'Interface opérateur', text: 'Rendre une séquence compréhensible : état de l’instrument, action disponible, résultat et erreur à traiter. Les actions sensibles nécessitent un comportement explicite et un périmètre de validation convenu.' },
        { title: 'Reprise de VIs', text: 'Comprendre un programme graphique existant, ses sous-VIs et ses dépendances avant d’en modifier une partie. Nous distinguons une amélioration d’affichage d’une modification de la chaîne de mesure.' },
      ] },
      { id: 'fonctionnement-labview', nav: 'Fonctionnement', kind: 'prose', eyebrow: 'Le programme et son interface', title: 'Un flux de données, pas seulement des blocs.', paragraphs: ['Un instrument virtuel, ou VI, associe une face avant et un diagramme. La face avant présente les commandes et indicateurs ; le diagramme porte la logique graphique et la circulation des données.', 'Dans un projet réel, nous séparons autant que possible acquisition, traitement, interface et enregistrement. Cette organisation aide à comprendre où se produit une erreur et à faire évoluer un affichage sans modifier inutilement la mesure.', 'Des exports peuvent être repris avec [Python](/expertise/python) pour préparer un rapport ou alimenter un outil métier. Une connexion directe demande de vérifier les interfaces et versions effectivement prises en charge.'], note: { title: 'Un périmètre à confirmer', text: 'Nous ne revendiquons ni certification NI ni qualification réglementaire d’un système de mesure. La validation métrologique et les fonctions de sécurité nécessitent des responsabilités et compétences spécifiques.' } },
      { id: 'cadrage-labview', nav: 'Cadrage', kind: 'workflow', eyebrow: 'Avant le développement', title: 'Le matériel fait partie du logiciel.', steps: [
        { title: 'Inventorier', text: 'Identifier la version, les VIs, modules, pilotes et instruments.' },
        { title: 'Décrire', text: 'Documenter les signaux, unités, séquences et fichiers attendus.' },
        { title: 'Simuler', text: 'Préparer les parcours et erreurs avec des données de démonstration.' },
        { title: 'Confronter', text: 'Prévoir une recette sur le matériel cible avec votre référent technique.' },
      ], note: 'Une démonstration simulée ne remplace pas une validation sur votre équipement, notamment pour les délais, pilotes et comportements de défaut.' },
      { id: 'choisir-labview', nav: 'Compatibilité', kind: 'choice', eyebrow: 'Les points à arbitrer', title: 'Un environnement pertinent pour la mesure.', yes: ['Votre installation comporte déjà des VIs à maintenir.', 'Vous avez un besoin d’acquisition ou de séquencement de tests.', 'Votre équipe dispose du matériel, des pilotes et du protocole nécessaires.'], no: ['Le besoin est uniquement un site public ou une application de gestion.', 'Le matériel et les versions ne sont pas accessibles pour la recette.', 'Vous attendez une garantie de temps réel sans plateforme ni modules adaptés.'] },
    ],
    faq: [
      { question: 'Pouvez-vous améliorer une application LabVIEW existante ?', answer: 'Oui, sous réserve de disposer des sources et des dépendances utiles. La première étape consiste à identifier les VIs, la version de LabVIEW, les pilotes et les instruments concernés. Nous proposons ensuite un périmètre de reprise ciblé.' },
      { question: 'Une application LabVIEW nécessite-t-elle une licence ?', answer: 'Les besoins diffèrent entre développement, construction d’un exécutable et déploiement. L’édition, Application Builder, les modules et les runtimes requis doivent être examinés pour le projet précis. La disponibilité d’une édition Community ne vaut pas autorisation générale d’usage commercial.' },
      { question: 'LabVIEW permet-il du temps réel ou du FPGA ?', answer: 'Ces usages dépendent de matériels et modules spécifiques. Le seul fait de développer avec LabVIEW ne garantit pas le déterminisme ni la compatibilité FPGA. Ils nécessitent un cadrage technique dédié et une validation sur cible.' },
      { question: 'Quels éléments préparer pour un premier échange ?', answer: 'Une description du protocole, la version du logiciel, les références matérielles, les sources disponibles et un exemple de fichier de sortie. Précisez aussi ce qui pose problème : acquisition, interface, séquence, export ou installation.' },
    ],
    connections: [{ slug: 'python', reason: 'Analyser des fichiers de mesure et préparer des rapports.' }, { slug: 'csharp', reason: 'Étudier une interface ou un composant logiciel complémentaire.' }, { slug: 'dotnet', reason: 'Relier les résultats à une application métier via une interface adaptée.' }],
    reading: { href: '/integrations-api', label: 'Relier les données à vos outils métier', reason: 'Distinguer la chaîne de mesure de la diffusion de ses résultats.' },
    sources: [{ label: 'NI : présentation de LabVIEW', href: 'https://www.ni.com/en-us/shop/labview.html' }, { label: 'NI : programmation graphique', href: 'https://www.ni.com/en/shop/labview/benefits-of-programming-graphically-in-ni-labview.html' }, { label: 'NI : choix d’une édition', href: 'https://www.ni.com/en/shop/labview/select-edition.html' }, { label: 'NI : méthodes de développement', href: 'https://www.ni.com/en/support/documentation/supplemental/09/software-engineering-with-labview.html' }],
    cta: { title: 'Partons du signal et du programme existant.', text: 'Présentez l’équipement, le résultat attendu et les difficultés rencontrées. Nous préciserons ce qui peut être pris en charge.', label: 'Décrire mon projet de mesure' },
  },
]
