import type { ExpertisePage } from './types'

export const nextjsPages: ExpertisePage[] = [{
  slug: 'nextjs', title: 'Agence Next.js : développement, migration & SEO | Litus',
  description: 'Litus développe et reprend vos sites Next.js : rendu serveur, CMS, SEO technique, migration React, performance et déploiement avec un périmètre clair.',
  headline: 'Développement Next.js.\nUne base solide.\nUn site qui avance.', accent: 'Un site qui avance.',
  intro: 'Un site marketing connecté à un CMS, un catalogue ou une application métier : nous utilisons Next.js pour relier contenu, données et interactions. Le choix du rendu, du cache et de l’hébergement part de vos usages, pas d’une promesse de score automatique.',
  action: 'Parlons de votre projet Next.js', deliverables: ['Architecture documentée', 'SEO technique intégré', 'Préproduction avant livraison'],
  sections: [
    { kind: 'cards', id: 'developpement', nav: 'Développement', eyebrow: 'Une agence, un périmètre concret', title: 'Du site éditorial à l’application métier.', intro: 'Next.js apporte un cadre à React pour organiser les routes, le rendu et les échanges serveur. Nous cadrons ce qui doit rester simple et ce qui mérite un développement spécifique.', items: [
      { title: 'Un site connecté au CMS', text: 'Pages de services, articles et réalisations reposent sur des modèles éditoriaux cohérents. Vos équipes publient dans leur outil ; le site présente des contenus structurés avec titres, images et liens internes maîtrisés.', detail: 'Le CMS est choisi selon vos habitudes de publication.' },
      { title: 'Une application avec accès client', text: 'Nous séparons les écrans publics des opérations privées. Chaque lecture ou modification sensible vérifie l’identité et les permissions côté serveur, indépendamment de ce que masque l’interface.', detail: 'Voir notre approche [application web](/creation-application-web).' },
      { title: 'Un catalogue sur mesure', text: 'Recherche, filtres, fiches et connexion au back-office demandent une stratégie claire de fraîcheur des données. Un stock ou un tarif ne doit pas dépendre d’une copie périmée sans règle explicite.', detail: 'Un parcours headless peut se connecter à [Shopify](/expertise/shopify).' },
      { title: 'La reprise d’un site existant', text: 'Nous commençons par la version installée, les dépendances, les routes et les incidents observés. Une reprise progressive peut corriger les points bloquants sans transformer une optimisation en refonte complète.', detail: 'Un diagnostic précède toute promesse de migration.' },
    ] },
    { kind: 'prose', id: 'seo', nav: 'SEO & rendu', eyebrow: 'Le contenu avant les effets', title: 'Un rendu adapté à chaque page.', paragraphs: [
      'Un contenu public peut être préparé à la construction ou rendu sur le serveur selon ses contraintes. Les composants interactifs enrichissent ensuite le parcours. Nous vérifions le HTML réellement livré : un moteur ou un visiteur sans JavaScript doit retrouver les informations essentielles.',
      'La [stratégie SEO](/referencement-naturel) comprend les intentions de recherche, les URL, le maillage et les contenus. Next.js fournit des mécanismes de métadonnées, mais ne décide ni de la pertinence d’une page ni de sa position dans Google.',
      'Nous traitons les titres, descriptions, canoniques, images de partage, redirections, sitemap et statuts HTTP. Les contenus privés et préproductions sont protégés ; un simple noindex ne constitue jamais une protection d’accès.',
    ], note: { title: 'SSR ne signifie pas première place.', text: 'Le rendu serveur aide à fournir le contenu. La qualité éditoriale, la concurrence et les performances mesurées restent des sujets distincts.' } },
    { kind: 'workflow', id: 'migration', nav: 'Migration', eyebrow: 'Changer de base sans perdre le fil', title: 'Une migration se prépare URL par URL.', steps: [
      { title: 'Inventaire', text: 'Recenser les pages, formulaires, données et connexions actuelles.' },
      { title: 'Architecture', text: 'Choisir le CMS, les routes et les frontières client / serveur.' },
      { title: 'Reprise', text: 'Migrer les contenus et établir le plan de redirections.' },
      { title: 'Préproduction', text: 'Vérifier les parcours, le rendu mobile et les accès.' },
      { title: 'Publication', text: 'Déployer, surveiller les erreurs et suivre l’indexation.' },
    ], note: 'Nous conservons les URL utiles lorsque c’est possible. Les redirections et la surveillance réduisent les risques ; elles ne permettent pas de garantir une absence de fluctuation SEO après migration.' },
    { kind: 'issues', id: 'depannage', nav: 'Dépannage', eyebrow: 'Identifier la vraie cause', title: 'Hydratation, cache ou build : des diagnostics différents.', items: [
      { symptom: 'Le navigateur signale une hydratation incohérente', diagnosis: 'Comparer le HTML serveur et le premier rendu client, notamment dates et état stocké dans le navigateur.', action: 'Rendre le premier affichage déterministe et isoler les interactions réellement réservées au navigateur.' },
      { symptom: 'Une modification reste invisible', diagnosis: 'Examiner les règles de cache, la revalidation, le CMS et l’environnement effectivement déployé.', action: 'Définir quand les données doivent être rafraîchies et vérifier le même contenu après publication.' },
      { symptom: 'Le build échoue uniquement en production', diagnosis: 'Contrôler les versions, variables, fichiers nécessaires et appels externes au moment de la construction.', action: 'Reproduire le build dans un environnement comparable avant de modifier l’hébergement [Vercel](/expertise/vercel).' },
    ] },
    { kind: 'choice', id: 'choisir', nav: 'Choisir Next.js', eyebrow: 'Le bon niveau de complexité', title: 'Un framework, pas une réponse universelle.', yes: ['Vous combinez contenu public, CMS et interactions React.', 'Vous avez des règles métier ou intégrations particulières.', 'Vous pouvez maintenir le code et suivre les évolutions du framework.'], no: ['Votre besoin est un petit site marketing administrable sans développement : [Framer](/expertise/framer) peut être plus direct.', 'Votre équipe travaille efficacement dans [WordPress](/expertise/wordpress) et une correction ciblée suffit.', 'Vous recherchez uniquement une amélioration de design, sans besoin de changer de base technique.'] },
  ],
  faq: [
    { question: 'Quelle différence entre React et Next.js ?', answer: 'React est la bibliothèque d’interface. Next.js est un framework construit autour de React qui ajoute notamment une organisation des routes, des mécanismes de rendu et des fonctionnalités serveur. Leur intérêt dépend du type de projet, pas d’un classement entre deux outils équivalents.' },
    { question: 'Peut-on migrer un site WordPress vers Next.js ?', answer: 'Oui, après inventaire des contenus, fonctionnalités et URL. WordPress peut rester le CMS ou être remplacé. Nous définissons les redirections, la reprise des médias et la prévisualisation éditoriale avant la bascule, puis suivons les erreurs et l’indexation.' },
    { question: 'Next.js améliore-t-il automatiquement le référencement ?', answer: 'Non. Les possibilités de rendu et de métadonnées facilitent certains aspects techniques. Il faut encore produire un contenu pertinent, des pages accessibles, un maillage cohérent et des performances mesurées. Aucun framework ne garantit une position dans Google.' },
    { question: 'Faut-il héberger un site Next.js sur Vercel ?', answer: 'Non. Vercel propose une intégration directe, mais un hébergement compatible peut être retenu. Les fonctions utilisées, le besoin de cache, les coûts et la capacité d’exploitation déterminent le choix. Les contraintes d’un export statique sont différentes de celles d’un serveur complet.' },
    { question: 'Pouvez-vous reprendre une application Next.js déjà développée ?', answer: 'Oui, en commençant par un diagnostic du code, des versions, des accès et des problèmes reproductibles. Nous proposons ensuite des corrections ou une migration progressive. Le devis distingue ce qui est certain de ce qui nécessite une investigation complémentaire.' },
    { question: 'Comment une équipe non technique publie-t-elle ses contenus ?', answer: 'Le site peut être relié à un CMS adapté à l’équipe. Nous prévoyons les champs éditoriaux, les rôles, les médias et un parcours de prévisualisation. L’autonomie de publication doit être testée avec les futurs utilisateurs, pas seulement démontrée par les développeurs.' },
  ],
  connections: [{ slug: 'react', reason: 'Des composants interactifs pour les parcours qui le nécessitent.' }, { slug: 'typescript', reason: 'Des contrats explicites entre le CMS, les API et les écrans.' }, { slug: 'vercel', reason: 'Des préproductions et une exploitation cadrée après livraison.' }],
  reading: { href: '/developpement-web-sur-mesure', label: 'Développement web sur mesure', reason: 'Relier les choix techniques aux opérations que votre site doit réellement permettre.' },
  sources: [{ label: 'Next.js : composants serveur et client', href: 'https://nextjs.org/docs/app/getting-started/server-and-client-components' }, { label: 'Next.js : métadonnées et Open Graph', href: 'https://nextjs.org/docs/app/getting-started/metadata-and-og-images' }, { label: 'Next.js : déploiement', href: 'https://nextjs.org/docs/app/getting-started/deploying' }],
  cta: { title: 'Un site Next.js à créer ou à reprendre ?', text: 'Présentez-nous votre site, votre CMS et les parcours qui comptent. Nous définirons une intervention adaptée à votre équipe.', label: 'Échanger sur votre projet Next.js' },
}]
