import { connectedDefinitions } from './connected-definitions'
import type { ExpertisePage, ExpertiseSection } from './types'

export const connectedPages: ExpertisePage[] = connectedDefinitions.map(d => {
  const sections: ExpertiseSection[] = [
    { id: 'interventions', nav: 'Nos interventions', kind: 'cards', eyebrow: `${d.name} · usages à construire`, title: 'Ce que nous pouvons réaliser avec vous.', intro: 'Des cas d’usage à adapter à votre fonctionnement, sans chiffres de résultats ni références clients inventés.', items: d.cases.map(([title, text]) => ({ title, text })) },
    { id: 'integration', nav: 'Architecture & intégrations', kind: 'prose', eyebrow: 'Le rôle de chaque outil', title: `${d.name} dans votre environnement.`, paragraphs: d.context, note: { title: 'Le besoin avant la connexion', text: `Nous cadrons les accès, la source de référence et le résultat attendu. ${d.name} garde un rôle précis ; les autres outils ne sont pas remplacés sans raison.` } },
    { id: 'methode', nav: 'Méthode & livraison', kind: 'workflow', eyebrow: 'Du premier cas à la mise en service', title: 'Un parcours que votre équipe peut reprendre.', steps: d.process.map(([title, text]) => ({ title, text })), note: `Le périmètre, les dépendances et les responsabilités sont validés ensemble. La [prestation associée](${d.service.href}) précise le besoin à traiter ; notre [générateur de cahier des charges](/ressources/cahier-des-charges) aide à préparer les premières informations.` },
    { id: 'choisir', nav: 'Avantages & limites', kind: 'choice', eyebrow: 'Un choix à justifier', title: `Quand retenir ${d.name} ?`, yes: d.fit, no: d.limits },
    { id: 'perimetre', nav: 'Préparer le projet', kind: 'prose', eyebrow: 'Votre échange avec Litus', title: 'Partir d’un exemple réel de votre travail.', paragraphs: [`Pour étudier ${d.name}, présentez-nous un exemple représentatif : ${d.cases[0][0].toLocaleLowerCase('fr-FR')}. Expliquez ce qui déclenche le travail, les outils concernés, le résultat souhaité et la personne qui le valide. Un exemple anonymisé suffit au premier échange ; ne transmettez pas de mot de passe ni de données clients inutiles.`, `Nous séparons la conception, les abonnements tiers et le suivi après livraison. Les livrables prévus sont : ${d.deliverables.join(', ').toLocaleLowerCase('fr-FR')}. Le chiffrage dépend du nombre de parcours, des accès disponibles et des contraintes à traiter. [Parlons du périmètre](${d.service.href}) avant de retenir une solution ou une date de mise en service.`] },
  ]
  // Vary the reading rhythm to reflect the subject, while keeping shared landmarks.
  if (d.visual.kind === 'documents' || d.visual.kind === 'code') [sections[0], sections[1]] = [sections[1], sections[0]]
  return { slug: d.slug, title: d.title, description: d.description, headline: d.headline, accent: d.accent, intro: d.intro, action: `Parler de mon projet ${d.name}`, deliverables: d.deliverables, sections, faq: d.faq.map(([question, answer]) => ({ question, answer })), connections: d.connections, reading: { href: d.service.href, label: d.service.label, reason: 'Le service correspondant pour cadrer le besoin et les responsabilités de Litus.' }, sources: d.sources, cta: { title: d.cases[0][0] + ' ?', text: `Montrez-nous vos étapes et ce qui bloque aujourd’hui. Nous étudierons le rôle de ${d.name}, les connexions nécessaires et les points à valider.`, label: 'Présenter mon besoin à Litus' } }
})
