import type { ExpertiseScene } from './visuals'

const make = (file: string, alt: string, title: string, text: string, points: [string, string, string], href: string, label: string): ExpertiseScene => ({ file, width: 1280, height: 800, alt, title, text, points, link: { href, label }, caption: 'Composition originale Litus : scénario pédagogique et données fictives, pas une capture du logiciel ni une réalisation client.' })
export const technicalScenes = {
  python: [
    make('python-donnees-import', 'Schéma Python reliant un fichier de commandes CSV à un contrôle des données puis à un rapport et un CRM, avec lignes prêtes ou à vérifier', 'La donnée rejetée doit aussi être expliquée.', 'Un import utile ne se contente pas d’accepter un fichier. Il rend visibles les références manquantes, les valeurs ambiguës et les lignes qui nécessitent une décision avant d’entrer dans votre outil.', ['Entrées et formats identifiés', 'Rejets compréhensibles', 'Import sans doublons'], '/integrations-api', 'Préparer les échanges de données'),
    make('python-automatisation-api', 'Maquette de suivi d’une automatisation Python montrant déclenchement planifié, traitement, API métier et résultat de chaque étape', 'Savoir où en est le traitement.', 'Lorsqu’une API distante est indisponible, votre équipe doit savoir si elle peut relancer l’opération. Le suivi distingue ce qui est terminé, en attente ou à reprendre, sans annoncer une réussite avant confirmation.', ['Déclenchement explicite', 'Délais et relances encadrés', 'Confirmation des actions'], '/automatisation', 'Définir un flux exploitable'),
  ],
  csharp: [
    make('csharp-application-metier', 'Maquette d’application métier C# avec dossiers d’intervention, responsables et états à planifier, en cours et à valider', 'Un dossier, un responsable, une prochaine action.', 'L’interface traduit le fonctionnement de votre équipe. Nous définissons qui peut créer une demande, l’affecter et la valider, puis comment ces opérations sont enregistrées et expliquées à l’utilisateur.', ['Statuts métier définis', 'Responsabilités visibles', 'Historique des opérations'], '/creation-application-web', 'Concevoir un outil interne'),
    make('csharp-regles-metier', 'Schéma d’une requête C# passant par le contrôle d’identité, les droits sur le dossier et la validation de transition avant enregistrement', 'Le bouton ne décide pas de l’autorisation.', 'Masquer une action dans l’interface améliore la lisibilité, mais ne remplace pas le contrôle serveur. Nous séparons la présentation, les droits et les règles qui permettent réellement de changer l’état d’un dossier.', ['Identité authentifiée', 'Droits sur la ressource', 'Transition métier validée'], '/expertise/dotnet', 'Structurer le service .NET'),
  ],
  dotnet: [
    make('dotnet-api-architecture', 'Architecture pédagogique .NET reliant une interface React à une API ASP.NET Core puis à une base métier privée', 'Une interface publique, des données maîtrisées.', 'Le navigateur interagit avec l’API ; la base reste dans l’environnement prévu pour elle. Cette séparation permet d’expliquer les responsabilités de chaque composant et les accès nécessaires.', ['Contrat API explicite', 'Logique métier serveur', 'Accès aux données limités'], '/expertise/react', 'Préparer l’interface utilisateur'),
    make('dotnet-livraison-service', 'Tableau pédagogique de livraison d’un service .NET : configuration documentée, sauvegarde à restaurer en test et procédure de retour de version', 'Une livraison que votre équipe peut reprendre.', 'Les fichiers de configuration, les consignes de sauvegarde et la procédure de retour font partie d’un service exploitable. Nous définissons avec vous ce qui est livré et qui prend en charge la suite.', ['Configuration documentée', 'Recette distincte de la production', 'Responsabilités de maintenance'], '/developpement-web-sur-mesure', 'Cadrer le développement et sa livraison'),
  ],
  labview: [
    make('labview-acquisition-mesures', 'Schéma original d’acquisition avec LabVIEW montrant instrument, mesures horodatées et canaux température et tension, sans données réelles', 'Une mesure a besoin de son contexte.', 'La valeur seule ne suffit pas : unité, canal, référence du lot et conditions d’acquisition rendent l’enregistrement exploitable. La chaîne réelle doit être validée avec les instruments et le protocole du projet.', ['Canaux et unités définis', 'Horodatage et référence du lot', 'Validation sur matériel cible'], '/expertise/python', 'Exploiter les fichiers de mesure'),
    make('labview-banc-essai', 'Maquette illustrative de séquence d’un banc de test utilisant LabVIEW : initialisation, mesure et archivage avec résultats simulés', 'Une séquence compréhensible par l’opérateur.', 'L’écran explique ce qui est prêt, ce qui se déroule et ce qui exige une intervention. Les seuils sont fournis par le protocole métier ; une simulation de cette interface ne constitue pas une validation du banc.', ['Étapes et préconditions visibles', 'Gestion des erreurs', 'Compte rendu du lot'], '/integrations-api', 'Relier les résultats au suivi métier'),
  ],
} satisfies Record<'python' | 'csharp' | 'dotnet' | 'labview', [ExpertiseScene, ExpertiseScene]>
