import { connectedScenes } from './visuals-connected'
import { technicalScenes } from './visuals-technical'
import type { ExpertiseSlug } from './types'

export type ExpertiseScene = {
  file: string; width: number; height: number; alt: string; caption: string
  title: string; text: string; points: [string, string, string]
  link: { href: string; label: string }; source?: { href: string; label: string; license: string }
}
const original = 'Maquette pédagogique originale Litus. Données fictives, pas une capture du logiciel ni une réalisation client.'
const scene = (file: string, alt: string, title: string, text: string, points: [string, string, string], href: string, label: string): ExpertiseScene => ({ file, width: 1280, height: 800, alt, caption: original, title, text, points, link: { href, label } })

export const expertiseScenes = {
  ...connectedScenes,
  ...technicalScenes,
  shopify: [
    scene('shopify-catalogue-produits', 'Maquette de gestion e-commerce avec liste de produits, stocks et collections, illustrant un projet Shopify', 'Une boutique Shopify commence par un catalogue bien organisé.', 'Notre accompagnement Shopify relie la création de boutique à son exploitation : variantes, collections, disponibilité et commandes. Avant de développer le thème, nous préparons des données que votre équipe pourra réellement maintenir.', ['Produits, variantes et collections', 'Stocks et informations utiles à l’achat', 'Reprise des données avant migration'], '/creation-site-ecommerce', 'Préparer votre boutique en ligne'),
    scene('shopify-boutique-collection', 'Exemple fictif de boutique de décoration avec une collection de vases, fiches produits et bouton de commande, pour illustrer un site Shopify', 'Création, optimisation ou migration vers Shopify : partir du parcours d’achat.', 'Une fiche claire, des choix compréhensibles et un passage en caisse sans surprise comptent davantage qu’une accumulation d’applications. Pour dépanner ou optimiser une boutique Shopify existante, nous observons le problème avant de modifier le thème, les apps ou le tracking.', ['Hiérarchie de la fiche produit', 'Livraison et paiement à tester', 'SEO, redirections et suivi des événements'], '/expertise/stripe', 'Comprendre les parcours de paiement'),
  ],
  framer: [
    scene('framer-composition-site-marketing', 'Maquette pédagogique d’un atelier de design avec calques, aperçu d’un site marketing et réglages responsive, illustrant la création avec Framer', 'Créer un site avec Framer, sans séparer design et contenu.', 'Nous composons les pages autour de vos messages et de vos appels à l’action. Le travail sur la plateforme Framer inclut les sections réutilisables, les variantes responsive et des animations qui accompagnent la lecture sans retarder l’accès au contenu.', ['Composition et composants réutilisables', 'Lecture confortable sur petit écran', 'Animations mesurées et accessibles'], '/creation-site-internet', 'Cadrer la création de votre site'),
    scene('framer-cms-publication', 'Maquette de collection éditoriale avec articles, statuts de publication et aperçu de page, pour expliquer l’organisation d’un CMS Framer', 'Un CMS Framer pensé pour publier, puis optimiser.', 'Un site marketing doit pouvoir évoluer après sa mise en ligne. Nous préparons les collections, les champs SEO, les images et les formulaires. L’optimisation d’un site Framer existant commence par les pages importantes, les parcours mobiles et les demandes réellement transmises.', ['Collections et modèles éditoriaux', 'Titres, descriptions et images de partage', 'Formulaires reliés au bon destinataire'], '/referencement-naturel', 'Relier le site à votre stratégie SEO'),
  ],
  wordpress: [
    { ...scene('wordpress-editeur-gutenberg-officiel', 'Visuel officiel Gutenberg montrant l’éditeur de blocs WordPress sur tablette et téléphone avec un article Hello, world', 'WordPress : rendre l’édition aussi claire que la page publiée.', 'L’éditeur de blocs organise les contenus en éléments réutilisables. Nous adaptons les modèles, les droits et les consignes éditoriales à votre équipe. Selon le thème, les outils disponibles diffèrent : la reprise commence par votre installation réelle, pas par une démonstration standard.', ['Modèles éditoriaux cohérents', 'Images et titres correctement renseignés', 'Autonomie de l’équipe de publication'], '/creation-site-internet', 'Concevoir un site administrable'), width: 1200, height: 831, caption: 'Visuel du dépôt officiel Gutenberg, publié en 2020. L’interface dépend de la version installée.', source: { href: 'https://github.com/WordPress/gutenberg', label: 'WordPress / Gutenberg', license: '/expertise/licenses/wordpress-LICENSE.txt' } },
    scene('wordpress-maintenance-diagnostic', 'Maquette d’un suivi de maintenance WordPress présentant sauvegarde, extensions, formulaire et contrôles WooCommerce', 'Dépannage et maintenance WordPress : retrouver un site fiable.', 'Erreur critique, extension incompatible, formulaire muet ou commande WooCommerce bloquée : chaque panne demande une vérification différente. Notre intervention WordPress distingue sauvegarde restaurable, diagnostic, correction et contrôle des parcours après mise à jour.', ['Sauvegarde des fichiers et de la base', 'Conflits de thème ou d’extension', 'Formulaires et commandes WooCommerce'], '/refonte-site-internet', 'Choisir entre correction et refonte'),
  ],
  stripe: [
    { ...scene('stripe-checkout-abonnement-officiel', 'Capture du projet officiel Stripe Samples : formulaire Checkout en mode test pour un abonnement Starter, avec champs email et carte bancaire', 'Stripe Checkout : un paiement lisible, une intégration maîtrisée.', 'Checkout prend en charge l’interface de paiement hébergée. Nous préparons la session depuis votre serveur et relions la transaction à la bonne demande. Ce visuel du projet Stripe Samples illustre un abonnement de démonstration, pas un paiement réel ni les tarifs de Litus.', ['Session associée à une commande', 'Parcours test avant production', 'Confirmation de paiement côté serveur'], '/creation-application-web', 'Relier le paiement à votre application'), width: 1062, height: 662, caption: 'Capture extraite de la démonstration officielle Stripe Samples, en mode test. Interface illustrative, susceptible d’évoluer.', source: { href: 'https://github.com/stripe-samples/checkout-single-subscription', label: 'Stripe Samples', license: '/expertise/licenses/stripe-LICENSE.txt' } },
    scene('stripe-webhooks-abonnements', 'Schéma d’exploitation d’un abonnement Stripe reliant événement de paiement, activation du compte et synchronisation CRM', 'L’abonnement ne s’arrête pas à la page de confirmation.', 'Après l’encaissement viennent les factures, les changements d’offre, les impayés et les résiliations. L’intégration des webhooks Stripe permet de relier ces événements à vos règles métier. Nous prévoyons les notifications répétées, les erreurs et les reprises de traitement.', ['Signature et contrôle des événements', 'Actions idempotentes et traçables', 'Synchronisation avec les accès et le CRM'], '/integrations-api', 'Préparer vos intégrations API'),
  ],
  vercel: [
    scene('vercel-previews-deploiement', 'Maquette d’un suivi de déploiement avec préproduction, branche de code et publication, illustrant un workflow sur Vercel', 'Voir la prochaine version avant de la publier sur Vercel.', 'Les préproductions servent à relire un contenu, tester un formulaire et partager une évolution avant sa mise en ligne. Nous séparons les variables et les accès des environnements pour éviter qu’un test utilise involontairement un service de production.', ['Préproduction identifiable', 'Variables séparées par environnement', 'Validation avant publication'], '/expertise/nextjs', 'Explorer le développement Next.js'),
    scene('vercel-build-logs-diagnostic', 'Maquette de console de build et de diagnostic DNS présentant des étapes de construction et des points de contrôle pour un déploiement Vercel', 'Un déploiement Vercel qui échoue mérite un diagnostic précis.', 'Un build rouge, un domaine inaccessible et une fonction en erreur ne se corrigent pas avec la même action. Nous relions les logs au code et à la configuration, puis documentons la correction. La surveillance des usages et des coûts fait partie de la préparation de l’exploitation.', ['Logs de build et erreurs applicatives', 'DNS, domaine et certificat', 'Usages, limites et procédure de retour'], '/developpement-web-sur-mesure', 'Faire diagnostiquer votre projet'),
  ],
  react: [
    scene('react-interface-configurateur', 'Maquette d’une interface React de configuration de projet avec options, étapes et récapitulatif du choix utilisateur', 'Une interface React se juge sur un vrai parcours.', 'Choisir des options, filtrer une liste et retrouver son récapitulatif : les composants React doivent garder un état cohérent. Nous préparons aussi les messages d’erreur et les écrans de chargement, pour que l’utilisateur comprenne ce qui se passe à chaque étape.', ['État et règles du formulaire', 'Retour clair après chaque action', 'Validation serveur des données sensibles'], '/creation-application-web', 'Définir les usages de votre application'),
    scene('react-composants-parcours', 'Diagramme original d’une arborescence de composants React reliant page, filtre, liste et fiche de détail', 'Reprendre une application React sans multiplier les rustines.', 'Le découpage des composants et la circulation des données déterminent la facilité de maintenance. Nous observons les interactions qui ralentissent et les dépendances qui se répètent avant de proposer une reprise ciblée. Next.js peut compléter React si le projet nécessite des routes et un rendu serveur.', ['Composants aux responsabilités claires', 'Performance observée sur un parcours', 'Architecture adaptée au rendu attendu'], '/expertise/nextjs', 'Comprendre le rôle de Next.js'),
  ],
  nextjs: [
    scene('nextjs-rendu-serveur-cms', 'Schéma d’architecture Next.js reliant CMS, rendu serveur, page HTML et composants interactifs React', 'Contenu serveur, interactions client : chacun son rôle.', 'Nous gardons les données sensibles côté serveur et réservons le JavaScript navigateur aux interactions utiles. Cette séparation permet de raisonner sur ce qui est envoyé au visiteur, sur la fraîcheur des données et sur la manière dont une page peut être explorée.', ['CMS et sources de données', 'HTML public et métadonnées', 'Interactions React ciblées'], '/expertise/react', 'Découvrir les interfaces React'),
    scene('nextjs-site-editorial-preview', 'Maquette d’un site éditorial affichant une page de conseil et ses métadonnées de prévisualisation, pour illustrer un projet Next.js', 'Une migration Next.js se voit aussi dans les détails éditoriaux.', 'Titres, visuels, canoniques et liens internes doivent suivre les contenus jusqu’à la nouvelle version. Nous relisons les pages prioritaires en préproduction et conservons les repères utiles aux visiteurs. Le suivi après bascule reste indispensable.', ['Correspondance des anciennes URL', 'Aperçu éditorial et image de partage', 'Suivi des erreurs après publication'], '/expertise/vercel', 'Préparer le déploiement'),
  ],
  typescript: [
    scene('typescript-contrat-donnees-api', 'Exemple de contrat TypeScript décrivant une demande de contact avec un type de projet, un email et un statut', 'TypeScript donne un vocabulaire commun à vos données.', 'Un contrat explicite aide à relier formulaire, API et CRM sans deviner la forme de chaque valeur. Nous utilisons le typage pour détecter les incompatibilités au développement. Les données externes restent validées à l’exécution : une annotation de type n’est pas un contrôle de sécurité.', ['Contrats entre les écrans et les API', 'Erreurs détectées avant livraison', 'Validation des entrées à l’exécution'], '/integrations-api', 'Fiabiliser vos échanges de données'),
    scene('typescript-migration-javascript', 'Diagramme d’une migration progressive JavaScript vers TypeScript, des modules existants aux contrats partagés et aux contrôles', 'Migrer JavaScript vers TypeScript, un périmètre à la fois.', 'Nous commençons par les zones où le manque de contrats coûte du temps : réponses d’API, formulaires ou règles métier. La migration reste progressive pour conserver un produit utilisable. Les contrôles choisis et les limites restantes sont documentés pour l’équipe qui reprend le code.', ['Modules prioritaires identifiés', 'Types partagés sans any généralisé', 'Contrôles renforcés progressivement'], '/expertise/react', 'Appliquer ces contrats à votre interface'),
  ],
  tailwind: [
    scene('tailwind-composants-design-system', 'Planche de composants d’interface avec boutons, champs, carte et tokens de couleur, illustrant un design system Tailwind CSS', 'Tailwind CSS : des composants cohérents, pas des classes au hasard.', 'Nous traduisons votre direction artistique en règles réutilisables : espacements, couleurs, typographie et états des composants. La cohérence vient de ces choix partagés, pas du nombre de classes. Un bouton garde le même rôle et la même lisibilité sur toutes les pages.', ['Tokens alignés sur votre identité', 'États focus, erreur et désactivation', 'Composants documentés et réutilisables'], '/creation-site-internet', 'Construire votre interface de marque'),
    scene('tailwind-responsive-ecrans', 'Maquette comparant une même page sur ordinateur, tablette et téléphone, avec une grille responsive adaptée à chaque largeur', 'Un responsive pensé pour le contenu réel.', 'Nous vérifions les retours à la ligne, les menus, les cartes et les formulaires sur plusieurs largeurs. Une intégration Tailwind responsive ne consiste pas à réduire tout proportionnellement : elle réorganise la hiérarchie pour conserver des actions accessibles et un contenu lisible.', ['Grille adaptée à chaque largeur', 'Textes longs et zoom du navigateur', 'Navigation tactile et clavier'], '/refonte-site-internet', 'Améliorer une interface existante'),
  ],
} as Record<ExpertiseSlug, [ExpertiseScene, ExpertiseScene]>

export function expertiseImage(file: string) { return `/expertise/images/${file}.webp` }
