import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, MapPin, Search, FileText, Smartphone, MessageCircle, ChartNoAxesCombined, Check, Plus } from 'lucide-react'
import { pageMetadata } from '@/lib/seo/metadata'
import { portfolioCatalog } from '@/lib/portfolio-catalog'
import { ReferenceReveal } from '@/components/sections/home/ReferenceMotion'
import { SeoLocalHero } from './SeoLocalHero'
import './seo-local.css'
const url = 'https://www.litus.fr/seo-local'
const description = 'Améliorez votre visibilité sur Google et Maps : fiche établissement, pages locales et suivi des demandes. Un accompagnement SEO local à Lorient et au Mans.'
export const metadata: Metadata = pageMetadata('/seo-local', { title: 'SEO local : visibilité Google à Lorient & au Mans | Litus', description, openGraph: { images: [{ url: '/blog/photos/le-mans-cathedrale.webp', width: 1400, height: 928, alt: 'La cathédrale Saint-Julien au Mans, territoire accompagné par Litus' }] }, twitter: { images: ['/blog/photos/le-mans-cathedrale.webp'] } })
const faq = [
  ['Qu’est-ce que le référencement local ?', 'Le SEO local aide une entreprise à être trouvée pour ses prestations dans une zone géographique pertinente. Il associe le site internet, la fiche Google Business Profile, les informations de l’établissement, les avis et les références locales. L’objectif n’est pas seulement une position : c’est aussi un appel, une visite ou une demande de devis adaptée.'],
  ['Google Maps et le référencement du site, est-ce la même chose ?', 'Non. Les résultats de la carte reposent notamment sur la pertinence de la fiche, la distance avec la personne qui cherche et la notoriété de l’établissement. Les pages du site travaillent les recherches organiques et expliquent les services. Une fiche complète et des pages utiles se complètent, mais une bonne position dans l’un ne garantit pas la même dans l’autre.'],
  ['Peut-on travailler plusieurs villes autour de Lorient ou du Mans ?', 'Oui, si ces communes correspondent à votre activité réelle. Nous partons de vos chantiers, de vos déplacements et de la demande. Une page pour Lanester, Ploemeur, Allonnes ou Coulaines doit apporter des informations propres à la zone : prestations, projets et modalités de contact. Changer uniquement le nom de la ville dans un texte identique n’est pas une stratégie.'],
  ['Je travaille chez mes clients : faut-il afficher mon adresse personnelle ?', 'Si vous ne recevez pas de clients à votre adresse, Google demande de la masquer dans la fiche publique et d’indiquer les zones desservies. Nous vérifions le type d’établissement et les règles applicables à votre activité. Il ne faut pas créer de fausses implantations ou une fiche par commune pour simuler une présence.'],
  ['Combien de temps faut-il pour voir une progression ?', 'Certaines corrections peuvent être prises en compte rapidement ; les effets d’un travail de fond s’observent généralement sur plusieurs mois. L’état du site, la concurrence, la saison et l’historique de la fiche changent le calendrier. Nous établissons un point de départ et suivons la progression, sans promettre une date ni une première position.'],
  ['Quel budget prévoir pour un accompagnement SEO local ?', 'L’offre de suivi présentée sur cette page commence à 99 € par mois, selon le périmètre retenu. Un audit complet, une refonte, des pages supplémentaires ou un accompagnement multi-établissements font l’objet d’un devis distinct. Les livrables, la fréquence du suivi et les conditions d’engagement sont précisés avant le démarrage.'],
  ['Peut-on combiner SEO local et Google Ads ?', 'Oui. Le SEO travaille la présence organique et les contenus dans la durée ; Google Ads permet de diffuser des annonces avec un budget média distinct. Nous séparons leurs résultats pour savoir quelles demandes viennent de chaque canal. Le cas SARL Péan J présenté sur notre page Google Ads relève de l’acquisition payante, pas d’une performance SEO.'],
  ['Comment mesurez-vous les résultats ?', 'Nous croisons les recherches et clics du site dans Search Console, les interactions de la fiche établissement et les demandes reçues. Le suivi peut inclure les formulaires et les clics sur le téléphone, avec une configuration adaptée des outils. Un clic sur le numéro n’est pas forcément un appel abouti : la qualification des demandes avec votre équipe reste importante.'],
]
const schema = { '@context': 'https://schema.org', '@graph': [
  { '@type': 'WebPage', '@id': url, url, name: 'SEO local à Lorient et au Mans', description, inLanguage: 'fr-FR' },
  { '@type': 'Service', '@id': `${url}#service`, name: 'Accompagnement en référencement local', serviceType: 'SEO local et Google Business Profile', url, provider: { '@id': 'https://www.litus.fr/#organization' }, areaServed: [{ '@type': 'City', name: 'Lorient' }, { '@type': 'City', name: 'Le Mans' }] },
  { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: 'https://www.litus.fr' }, { '@type': 'ListItem', position: 2, name: 'SEO local', item: url }] },
  { '@type': 'FAQPage', mainEntity: faq.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) },
] }
const pillars = [
  { icon: MapPin, title: 'Une fiche établissement juste.', text: 'Catégorie, services, coordonnées, horaires et zone desservie : nous vérifions ce qui décrit réellement votre entreprise. Des photos récentes rendent votre activité plus tangible.', href: '#google-business-profile', label: 'Travailler Google Maps' },
  { icon: FileText, title: 'Des pages qui répondent au besoin.', text: 'Prestations, réalisations, déroulement d’une intervention et réponses aux questions : chaque page locale doit aider à choisir, pas simplement répéter une ville.', href: '/creation-site-internet', label: 'Un site pensé pour vos clients' },
  { icon: Smartphone, title: 'Un parcours simple sur mobile.', text: 'Une page rapide, un téléphone accessible et une demande de devis courte. Nous corrigeons aussi l’indexation, les liens internes et les informations structurées utiles.', href: '/expertise', label: 'Découvrir nos expertises' },
  { icon: MessageCircle, title: 'Des preuves, pas des raccourcis.', text: 'Photos de projets, avis authentiques et réponses soignées renforcent la confiance. Les partenariats locaux pertinents ont plus de sens qu’une collection de liens artificiels.', href: '/realisations', label: 'Voir les projets Litus' },
]
const projects = [
  { slug: 'west-clotures-paysage', label: 'Artisan · Morbihan', title: 'West Clôtures & Paysage', text: 'Une refonte qui relie clôtures, portails, terrasses et aménagements paysagers aux communes réellement desservies. Les réalisations donnent à voir le travail ; les pages de prestations et le formulaire accompagnent la demande de devis.', tags: ['Refonte', 'SEO local', 'Parcours devis'], lesson: 'Le point clé : associer une prestation précise, une zone réelle et des preuves de savoir-faire.' },
  { slug: 'demetis-immo', label: 'Immobilier · Le Mans', title: 'Demetis Immo', text: 'Un site immobilier qui réunit annonces, photographies et informations pratiques, avec un ancrage clair au Mans et en Sarthe. La lecture des biens et les prises de contact restent au centre du parcours, plutôt qu’une simple accumulation de mots-clés.', tags: ['Site immobilier', 'Visibilité locale', 'Next.js'], lesson: 'Le point clé : une présence locale crédible et un accès direct aux biens proposés.' },
  { slug: 'loumor-debarras', label: 'Services · Vannes et Morbihan', title: 'Loumor Débarras', text: 'Maison, local professionnel ou succession : le site distingue les situations de débarras, précise les zones d’intervention et rend le contact facile à trouver. Une structure utile pour relier chaque besoin à la bonne prestation.', tags: ['WordPress', 'SEO local', 'Site vitrine'], lesson: 'Le point clé : rassurer avec des réponses adaptées à chaque situation.' },
].map(project => ({ ...project, cover: portfolioCatalog.find(item => item.slug === project.slug)!.cover }))
function Cta({ children }: { children: ReactNode }) { return <Link className="site-cta-primary" href="/contact?objet=Audit%20SEO%20local">{children}<ArrowRight size={18} aria-hidden="true" /></Link> }
function Heading({ label, title, children }: { label: string; title: string; children?: ReactNode }) { return <div className="local-heading"><p className="local-eyebrow">{label}</p><h2>{title}</h2>{children && <p>{children}</p>}</div> }
export default function SeoLocalPage() {
  return <div className="local-seo-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} /><SeoLocalHero />
    <nav className="local-jump local-container" aria-label="Sur cette page"><Link href="/">Accueil</Link><span aria-hidden="true">/</span><span>SEO local</span><div><a href="#territoires">Lorient & Le Mans</a><a href="#realisations-locales">Projets clients</a><a href="#tarifs">Accompagnement</a><a href="#faq">Questions fréquentes</a></div></nav>
    <section id="referencement-local" className="local-section local-container"><ReferenceReveal><Heading label="01 · Être trouvé, puis choisi" title="Le bon service. Au bon endroit.">Votre futur client ne cherche pas « du référencement ». Il cherche une entreprise capable de répondre à son besoin, près de chez lui. Nous travaillons cette rencontre.</Heading><div className="local-pillars">{pillars.map(({ icon: Icon, ...pillar }) => <article key={pillar.title}><Icon size={25} aria-hidden="true" /><h3>{pillar.title}</h3><p>{pillar.text}</p><Link href={pillar.href}>{pillar.label}<ArrowRight size={15} aria-hidden="true" /></Link></article>)}</div></ReferenceReveal></section>
    <section id="territoires" className="local-section local-territories"><div className="local-container"><Heading label="02 · Deux territoires, des besoins différents" title="Du pays de Lorient au bassin manceau.">Même méthode, jamais le même copier-coller. La zone d’intervention, le métier et les habitudes de recherche donnent le point de départ.</Heading>
      <ReferenceReveal className="local-city-row"><figure className="local-city-photo"><Image src="/territories/lorient-port.webp" alt="Voiliers amarrés au quai de Rohan dans le port de plaisance de Lorient" width={1200} height={896} sizes="(max-width: 760px) 90vw, 45vw" loading="lazy" /><figcaption>Lorient · Quai de Rohan <Link href="/territories/credits.html">Photo : Taratata · CC BY 3.0</Link></figcaption></figure><div><p className="local-eyebrow">Lorient · Lanester · Ploemeur · Caudan</p><h3>Un artisan visible là où il intervient vraiment.</h3><p>Pour un plombier du pays de Lorient, les recherches « dépannage plomberie Lorient » et « installation salle de bain Ploemeur » ne décrivent pas le même besoin. La page d’arrivée doit présenter le bon service, les modalités d’intervention et un moyen de joindre l’entreprise.</p><div className="local-example"><span>Exemple de stratégie, pas un résultat client</span><p><Search size={17} aria-hidden="true" />Besoin local → page de prestation → photos de chantiers → appel ou devis.</p></div><ul className="local-checks"><li><Check aria-hidden="true" />Définir les communes réellement desservies.</li><li><Check aria-hidden="true" />Présenter les prestations et les projets correspondants.</li><li><Check aria-hidden="true" />Faciliter l’appel depuis un téléphone.</li></ul><Link className="local-text-link" href="/agence-web-lorient">Notre accompagnement à Lorient <ArrowRight size={16} aria-hidden="true" /></Link></div></ReferenceReveal>
      <ReferenceReveal className="local-city-row local-city-reverse"><figure className="local-city-photo"><Image src="/blog/photos/le-mans-cathedrale.webp" alt="Chevet de la cathédrale Saint-Julien au Mans vu de la place des Jacobins" width={1400} height={928} sizes="(max-width: 760px) 90vw, 45vw" loading="lazy" /><figcaption>Le Mans · Place des Jacobins <Link href="/territories/credits.html">Photo : Patrick Monchicourt · CC BY-SA 2.0</Link></figcaption></figure><div><p className="local-eyebrow">Le Mans · Coulaines · Allonnes · Changé</p><h3>Répondre à une intention, pas à un nom de ville.</h3><p>Dans l’immobilier, « agence immobilière Le Mans » et « faire estimer sa maison au Mans » appellent deux réponses différentes : découvrir une agence et ses biens, ou comprendre une prestation d’estimation. Nous organisons les contenus et les contacts en conséquence.</p><div className="local-example"><span>Exemple de stratégie, à adapter à l’agence</span><p><Search size={17} aria-hidden="true" />Recherche immobilière → biens ou service d’estimation → informations locales → rendez-vous.</p></div><p>Demetis Immo illustre cet ancrage territorial avec une présentation de l’agence et un accès direct aux annonces. Son projet est détaillé plus bas.</p><Link className="local-text-link" href="/agence-web-le-mans">Notre accompagnement au Mans <ArrowRight size={16} aria-hidden="true" /></Link></div></ReferenceReveal>
    </div></section>
    <section id="google-business-profile" className="local-section local-container"><ReferenceReveal className="local-maps-grid"><div><Heading label="03 · Google Business Profile" title="Votre fiche Maps est aussi une première impression.">Une entreprise bien présentée permet de comprendre rapidement son activité : où elle intervient, quand la joindre et ce qu’elle réalise.</Heading><p>Nous vérifions les catégories, les services, les horaires et la cohérence des coordonnées avec le site. Nous organisons les photos et les avis authentiques, sans faux commentaires ni fausses adresses.</p><p>Le classement local dépend notamment de la pertinence, de la distance et de la notoriété. On peut améliorer les informations et la présence en ligne ; on ne peut pas acheter une première place organique ou supprimer l’effet de la distance.</p><a className="local-text-link" href="https://support.google.com/business/answer/7091?hl=fr">Les recommandations officielles de Google <ArrowRight size={16} aria-hidden="true" /></a></div><div className="local-map-checklist"><MapPin size={30} aria-hidden="true" /><h3>La fiche que l’on veut trouver.</h3><ul>{['Une activité et des catégories exactes', 'Des horaires fiables et actualisés', 'Des photos de l’entreprise et de ses projets', 'Une zone desservie cohérente', 'Des avis authentiques et des réponses utiles', 'Un lien vers la bonne page du site'].map(text => <li key={text}><Check size={18} aria-hidden="true" />{text}</li>)}</ul><Link href="/ressources/checklist-gmb">Consulter la checklist Google Business Profile <ArrowRight size={16} aria-hidden="true" /></Link></div></ReferenceReveal></section>
    <section id="realisations-locales" className="local-section local-project-section"><div className="local-container"><Heading label="04 · Des entreprises, des projets réels" title="Le référencement prend forme sur le terrain.">Trois réalisations Litus où le site, les prestations et la présence locale travaillent ensemble.</Heading><div className="local-projects">{projects.map((project, index) => <ReferenceReveal key={project.slug} className={`local-project ${index === 1 ? 'local-project-reverse' : ''}`}><Link className="local-browser" href={`/realisations/${project.slug}`} aria-label={`Découvrir le projet ${project.title}`}><span className="local-browser-top" aria-hidden="true"><i /><i /><i /><span>{project.title}</span></span><Image src={project.cover.src} alt={project.cover.alt} width={project.cover.width} height={project.cover.height} sizes="(max-width: 760px) 90vw, 52vw" loading="lazy" />{project.cover.kind === 'archive' && <span className="local-archive">Visuel d’archive du projet</span>}</Link><div className="local-project-copy"><p className="local-eyebrow">{project.label}</p><h3>{project.title}</h3><div className="local-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><p>{project.text}</p><p className="local-project-lesson">{project.lesson}</p><Link className="local-text-link" href={`/realisations/${project.slug}`}>Découvrir cette réalisation <ArrowRight size={16} aria-hidden="true" /></Link></div></ReferenceReveal>)}</div><Link className="local-text-link" href="/realisations">Toutes nos réalisations <ArrowRight size={16} aria-hidden="true" /></Link></div></section>
    <section className="local-section local-container"><ReferenceReveal className="local-followup"><div><ChartNoAxesCombined size={31} aria-hidden="true" /><Heading label="05 · Ce qui compte vraiment" title="Des demandes utiles, pas seulement des positions.">Nous construisons un point de départ et suivons l’évolution des recherches, des pages consultées et des demandes reçues. Les chiffres prennent leur sens avec votre retour terrain.</Heading><Link className="local-text-link" href="/google-ads">Besoin d’accélérer aussi avec Google Ads ? <ArrowRight size={16} aria-hidden="true" /></Link></div><ol><li><strong>Comprendre votre marché</strong><p>Votre activité, votre zone, les recherches pertinentes et les pages déjà visibles.</p></li><li><strong>Prioriser les actions</strong><p>Fiche, contenus, technique et parcours de contact : un plan adapté à vos moyens.</p></li><li><strong>Mesurer et ajuster</strong><p>Clics organiques, interactions Maps et demandes qualifiées, sans confondre clic et client.</p></li></ol></ReferenceReveal></section>
    <section id="tarifs" className="local-section local-pricing-section"><div className="local-container local-pricing"><Heading label="06 · Un accompagnement à votre mesure" title="Un cadre clair pour avancer.">Le bon périmètre dépend du site, de la fiche et du territoire. Nous distinguons les corrections initiales, le suivi récurrent et les besoins de refonte.</Heading><div className="local-price-card"><p className="local-eyebrow">Suivi SEO local</p><p className="local-price">À partir de <strong>99 €</strong> / mois</p><ul className="local-checks">{['Rédaction de 1 à 2 articles par mois', 'Optimisation continue de la fiche établissement', 'Suivi de positionnement et rapport trimestriel', 'Support email'].map(text => <li key={text}><Check aria-hidden="true" />{text}</li>)}</ul><p className="local-small">Périmètre et conditions d’engagement précisés au devis. Audit complet, refonte et besoins multi-établissements chiffrés séparément.</p><Cta>Définir mon accompagnement</Cta><Link className="local-text-link" href="/tarifs">Tous les tarifs Litus <ArrowRight size={15} aria-hidden="true" /></Link></div></div></section>
    <section id="faq" className="local-section local-container local-faq"><Heading label="07 · Vos questions" title="Le SEO local, sans zone floue." /><div>{faq.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={19} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></section>
    <section className="local-container local-final-cta"><div><p className="local-eyebrow">Votre prochaine demande commence peut-être ici.</p><h2>Faisons le point sur votre visibilité locale.</h2><p>Votre activité, votre ville, vos priorités. Nous identifions ensemble les prochaines actions utiles.</p></div><Cta>Parlons de votre marché</Cta></section>
  </div>
}
