import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, ChartNoAxesCombined, Check, ChevronDown, FileSearch, FileText, GitBranch, Layers3, ListChecks, Search, Settings2, Target, UsersRound } from 'lucide-react'
import { ServiceHero } from '@/components/sections/services/ServiceHero'
import { BusinessSectionHeading, ServiceReveal } from '@/components/sections/services/BusinessService'
import { SeoStrategyDemo } from './_components/SeoStrategyDemo'
import './referencement-naturel.css'

const title = 'Référencement naturel SEO : audit, stratégie & contenu | Litus'
const description = 'Une stratégie SEO adaptée à votre entreprise : audit technique, recherche de mots-clés, contenus et maillage. Litus améliore votre site et suit les actions utiles.'
const url = 'https://litus.fr/referencement-naturel'
const contact = '/contact?objet=R%C3%A9f%C3%A9rencement%20naturel%20SEO'
export const metadata: Metadata = {
  title: { absolute: title }, description, alternates: { canonical: url },
  openGraph: { title, description, url, siteName: 'Litus', type: 'website', locale: 'fr_FR', images: [{ url: '/litus-og-social.png', width: 1200, height: 630, alt: 'Litus — Votre agence web pour développer votre activité.' }] },
  twitter: { card: 'summary_large_image', title, description, images: ['/litus-og-social.png'] },
}
const services = [
  { icon: FileSearch, title: 'Audit & priorités SEO', text: 'Comprendre les pages, les recherches et les obstacles actuels. Nous examinons les données disponibles et distinguons les corrections nécessaires des pistes à tester.', result: 'Un état des lieux et une feuille de route.' },
  { icon: Settings2, title: 'Technique & structure', text: 'Examiner l’exploration, l’indexation, les URL de référence et les liens internes. Nous rapprochons les problèmes détectés des pages importantes pour votre activité.', result: 'Des interventions hiérarchisées.' },
  { icon: FileText, title: 'Contenus & intentions', text: 'Travailler les pages de services, les catégories et les contenus de conseil autour des questions de vos prospects. Votre expertise nourrit les sujets et les réponses.', result: 'Des pages qui répondent à un besoin.' },
]
const method = [
  { title: 'Comprendre votre activité', text: 'Vos offres, vos clients, vos objectifs commerciaux et votre organisation servent de point de départ. Nous recensons aussi ce qui fonctionne déjà.' },
  { title: 'Choisir les bons chantiers', text: 'L’analyse du site et des recherches permet d’arbitrer les priorités. Chaque action est reliée à une page, un besoin et un livrable.' },
  { title: 'Faire évoluer les pages', text: 'Nous préparons les améliorations techniques et éditoriales, les validons avec vous, puis accompagnons leur intégration dans le site.' },
  { title: 'Observer et ajuster', text: 'Les données disponibles et les retours commerciaux éclairent les prochains choix. La progression se lit dans la durée, en tenant compte du contexte.' },
]
const faqs = [
  { question: 'Que comprend un accompagnement en référencement naturel ?', answer: 'Le périmètre peut couvrir l’audit du site, la recherche de sujets et de mots-clés, les améliorations techniques, les contenus, le maillage interne et le suivi. Il est défini selon votre point de départ et les ressources disponibles. Notre proposition précise les pages concernées, les livrables et les responsabilités pour leur mise en œuvre.' },
  { question: 'Quelle différence entre SEO général, SEO local et Google Ads ?', answer: 'Le référencement naturel travaille la présence de vos pages dans les résultats non publicitaires. Le SEO local répond plus particulièrement aux recherches liées à une zone géographique et à votre présence locale. Google Ads est un levier publicitaire avec son propre budget. Ces approches peuvent se compléter, avec des objectifs et un suivi distincts.' },
  { question: 'Pouvez-vous garantir la première place sur Google ?', answer: 'Non. Le classement et l’indexation sont décidés par Google et évoluent selon de nombreux éléments, dont la concurrence et la recherche effectuée. Nous nous engageons sur un travail défini, une méthode expliquée et un suivi des actions. Les objectifs sont posés à partir de votre situation, sans promesse de position garantie.' },
  { question: 'Combien de temps faut-il pour observer des effets ?', answer: 'Les délais varient selon l’état du site, les changements réalisés et la concurrence. Google indique que certaines modifications peuvent se refléter rapidement, tandis que d’autres prennent plusieurs mois. Nous définissons un rythme de suivi adapté et évitons de conclure sur une variation isolée ou quelques jours de données.' },
  { question: 'Faut-il refaire tout mon site pour améliorer le SEO ?', answer: 'Pas nécessairement. Une partie des améliorations peut concerner la structure, les contenus ou la configuration du site actuel. Si les limites de la plateforme rendent le travail difficile, nous vous expliquons les options. Lors d’une refonte, les pages utiles, les URL et les redirections doivent être prises en compte dès la préparation.' },
  { question: 'Quel budget prévoir pour une stratégie SEO ?', answer: 'Le budget dépend du nombre de pages, de l’état technique, des contenus à préparer et du rythme d’accompagnement. Nous proposons un périmètre chiffré après un premier échange et l’examen des informations disponibles. La production, l’intégration et le suivi sont précisés pour que vous sachiez ce qui est inclus.' },
]
const structuredData = { '@context': 'https://schema.org', '@graph': [
  { '@type': 'Service', '@id': `${url}#service`, name: 'Référencement naturel SEO', description, url, serviceType: 'Audit et accompagnement en référencement naturel', provider: { '@type': 'Organization', name: 'Litus', url: 'https://litus.fr' }, areaServed: { '@type': 'Country', name: 'France' } },
  { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: 'https://litus.fr' }, { '@type': 'ListItem', position: 2, name: 'Référencement naturel', item: url }] },
  { '@type': 'FAQPage', mainEntity: faqs.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
] }

export default function ReferencementNaturelPage() {
  return <div className="business-service seo-service-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, '\\u003c') }} />
    <ServiceHero id="referencement-naturel-title" eyebrow="Référencement naturel · Stratégie & contenu" title={'Votre référencement naturel.\nPensé pour vos futurs clients.'} accent="Pensé pour vos futurs clients." description="Une stratégie SEO relie vos offres aux recherches de vos clients. Nous travaillons la technique, les contenus et les liens de votre site, avec des priorités claires et un accompagnement dans la durée." primaryAction={{ label: 'Parlons de votre projet', href: contact }} secondaryAction={{ label: 'Voir notre approche', href: '#approche-seo' }} visual={<SeoStrategyDemo />} proof={<ul className="business-hero-proof"><li><Target aria-hidden="true" /><span>Des recherches pertinentes</span></li><li><Layers3 aria-hidden="true" /><span>Un site mieux structuré</span></li><li><UsersRound aria-hidden="true" /><span>Un suivi compréhensible</span></li></ul>} />
    <div className="business-content">
      <section className="business-section seo-service-intro" aria-labelledby="seo-role-title"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">Être présent au bon moment</p><h2 id="seo-role-title">Vos clients cherchent déjà.<br /><em>Que trouvent-ils ?</em></h2><p>Un prospect compare des solutions, cherche une réponse ou prépare un achat. Votre site doit l’aider à comprendre votre offre et à passer à l’étape suivante.</p><p>Notre accompagnement s’adresse aux entreprises de services, aux PME et aux sites marchands qui veulent construire une présence cohérente dans la recherche. Il part de vos pages et de votre réalité commerciale.</p></div><ServiceReveal className="seo-service-needs">{[
        { icon: Search, title: 'Votre site reste difficile à trouver', text: 'Identifier les sujets sur lesquels vous souhaitez être découvert, puis examiner les pages qui peuvent y répondre.' },
        { icon: FileText, title: 'Vos contenus ne reflètent plus votre offre', text: 'Clarifier les services, les réponses et les éléments de confiance dont vos prospects ont besoin.' },
        { icon: GitBranch, title: 'Les actions s’accumulent sans direction', text: 'Rassembler les interventions dans un plan lisible, avec des responsabilités et un ordre de priorité.' },
      ].map(({icon:Icon,title:itemTitle,text})=><article key={itemTitle}><span className="business-icon"><Icon aria-hidden="true" /></span><div><h3>{itemTitle}</h3><p>{text}</p></div></article>)}</ServiceReveal></div></section>
      <section className="business-section business-section-soft" aria-labelledby="seo-levers-title"><div className="business-container"><BusinessSectionHeading eyebrow="Les leviers de votre référencement" id="seo-levers-title" description="Une stratégie relie le fonctionnement du site, les besoins de ses visiteurs et la qualité de ses pages. Nous travaillons ces sujets ensemble.">Des fondations solides.<br /><em>Des contenus qui comptent.</em></BusinessSectionHeading><ServiceReveal className="business-grid">{services.map(({icon:Icon,title:itemTitle,text,result})=><article className="business-card seo-service-card" key={itemTitle}><span className="business-icon"><Icon aria-hidden="true" /></span><h3>{itemTitle}</h3><p>{text}</p><div><Check aria-hidden="true" />{result}</div></article>)}</ServiceReveal></div></section>
      <section className="business-section" aria-labelledby="seo-intent-title"><div className="business-container"><BusinessSectionHeading eyebrow="Avant les mots-clés, l’intention" id="seo-intent-title" description="Nous recherchons ce que la personne veut accomplir, le type de réponse attendu et sa proximité avec vos offres. Un volume de recherche seul ne suffit pas à décider.">Une recherche.<br /><em>Une réponse adaptée.</em></BusinessSectionHeading><div className="seo-service-intents">{[
        { label: 'Comprendre', question: '« Comment choisir une solution ? »', page: 'Un guide clair', text: 'Expliquer les critères, les usages et les points de vigilance à partir de votre expérience.' },
        { label: 'Comparer', question: '« Quelle solution pour mon besoin ? »', page: 'Une page d’offre précise', text: 'Décrire le périmètre, les options et le fonctionnement de votre accompagnement.' },
        { label: 'Agir', question: '« À qui confier mon projet ? »', page: 'Un parcours de contact', text: 'Donner les éléments utiles à une demande et faciliter le prochain échange.' },
      ].map(item=><article key={item.label}><span>{item.label}</span><h3>{item.question}</h3><ArrowRight aria-hidden="true" /><strong>{item.page}</strong><p>{item.text}</p></article>)}</div><p className="seo-service-example-note">Exemples d’intentions, à préciser selon votre activité et les résultats de recherche observés.</p></div></section>
      <section className="business-section business-section-warm" aria-labelledby="seo-plan-title"><div className="business-container business-split"><figure className="seo-service-photo"><div className="business-photo"><Image src="/blog/photos/planning-bureau.webp" alt="Un carnet ouvert, un ordinateur et un téléphone sur une table blanche" fill sizes="(max-width:850px) 100vw, 48vw" /><div className="business-photo-note"><strong>Une direction claire pour votre site.</strong><span>Les priorités sont définies avec votre équipe.</span></div></div><figcaption>Photographie d’illustration — JESHOOTS.COM, CC0.</figcaption></figure><div className="business-copy"><p className="business-kicker">Un plan que vous pouvez suivre</p><h2 id="seo-plan-title">Savoir ce qui change.<br /><em>Comprendre pourquoi.</em></h2><p>Une recommandation n’est utile que si elle peut être mise en œuvre. Nous précisons les pages concernées, l’action proposée et le résultat attendu du travail : une structure corrigée, une page enrichie ou un parcours clarifié.</p><p>Votre expertise métier reste essentielle. Elle permet de produire un contenu fidèle à votre activité, de vérifier les réponses et d’éviter les pages interchangeables.</p><ul className="business-check-list"><li><Check aria-hidden="true" /><span>Un périmètre et des livrables explicités.</span></li><li><Check aria-hidden="true" /><span>Un échange avec les personnes qui connaissent votre métier.</span></li><li><Check aria-hidden="true" /><span>Une mise en œuvre coordonnée avec votre site.</span></li></ul><Link className="business-text-link" href="/refonte-site-internet">Vous préparez une refonte ? Parlons des acquis SEO<ArrowUpRight size={16} aria-hidden="true" /></Link></div></div></section>
      <section className="business-section business-section-dark" aria-labelledby="seo-follow-title"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">Mesurer pour décider</p><h2 id="seo-follow-title">Des observations utiles.<br /><em>Des décisions expliquées.</em></h2><p>Nous lisons les données disponibles dans leur contexte : recherches, pages, évolution de l’offre ou saisonnalité. Les échanges avec votre équipe aident à rapprocher la visibilité des demandes reçues.</p><p>Le suivi porte sur les actions réalisées et sur ce que les données permettent réellement d’observer. Les variations isolées ne deviennent pas des promesses commerciales.</p></div><div className="seo-service-report"><p><ChartNoAxesCombined aria-hidden="true" />Votre point de suivi</p><ul><li><span>Présence dans la recherche</span><strong>Requêtes et pages visibles</strong></li><li><span>Parcours sur le site</span><strong>Contenus consultés et actions utiles</strong></li><li><span>Travail réalisé</span><strong>Livrables, constats et prochaines priorités</strong></li></ul><small>Indicateurs choisis selon les outils et les accès disponibles.</small></div></div></section>
      <section className="business-section" id="approche-seo" aria-labelledby="seo-method-title"><div className="business-container"><BusinessSectionHeading eyebrow="Notre accompagnement" id="seo-method-title">Une stratégie construite.<br /><em>Un travail qui avance.</em></BusinessSectionHeading><ServiceReveal className="seo-service-method">{method.map((item,index)=><article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</ServiceReveal><div className="seo-service-scope"><ListChecks aria-hidden="true" /><p><strong>Un périmètre adapté à votre site.</strong> Le budget et le rythme sont définis après le premier échange. Les contenus, les intégrations et le suivi sont distingués dans la proposition.</p><Link className="business-text-link" href={contact}>Définissons vos priorités<ArrowRight size={17} aria-hidden="true" /></Link></div></div></section>
      <section className="business-section business-section-soft" aria-labelledby="seo-faq-title"><div className="business-container"><BusinessSectionHeading eyebrow="Vos questions" id="seo-faq-title">Le référencement naturel,<br /><em>avec des repères clairs.</em></BusinessSectionHeading><div className="business-faq">{faqs.map(item=><details key={item.question}><summary>{item.question}<ChevronDown aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></div></section>
      <section className="business-section" aria-labelledby="seo-contact-title"><div className="business-container business-final"><div><p className="business-kicker">Votre visibilité se prépare</p><h2 id="seo-contact-title">Faisons le point sur votre site.<br /><em>Et sur ce qu’il peut apporter.</em></h2><p>Présentez-nous votre activité, vos offres et vos objectifs. Nous identifierons les questions à creuser et le bon point de départ pour votre référencement.</p></div><div className="business-final-actions"><Link href={contact} className="site-cta-primary">Parlons de votre projet SEO<ArrowRight size={18} aria-hidden="true" /></Link><span>Premier échange · Proposition sur mesure</span><a href="tel:+33744985521">07 44 98 55 21</a></div></div><nav className="business-container seo-service-related" aria-label="Expertises complémentaires"><Link href="/seo-local">Référencement local<ArrowUpRight /></Link><Link href="/google-ads">Campagnes Google Ads<ArrowUpRight /></Link><Link href="/creation-site-internet">Création de site internet<ArrowUpRight /></Link></nav></section>
    </div>
  </div>
}
