import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { expertisePath, expertiseTools, expertiseTool, expertiseStyle } from '@/lib/expertise/catalog'
import { aiPillars, expertiseCategories } from '@/lib/expertise/categories'
import './expertise-connected.css'

export function AiPillars() {
  const descriptions = ['Qualifier une demande, retrouver une réponse, préparer un rapport.', 'Préparer du code, des tests et des tâches de maintenance sous revue.', 'Analyser des documents, extraire des données et garder les références.', 'Relier formulaires, IA, CRM et emails avec des étapes contrôlées.']
  return <section className="business-section ex-ai-pillars" aria-labelledby="ai-pillars-title"><div className="business-container"><p className="business-kicker">Automatisation & IA</p><h2 id="ai-pillars-title">Quatre outils.<br /><em>Des rôles bien distincts.</em></h2><p className="ex-ai-intro">L’assistant comprend, l’agent prépare, le workflow relie. Nous choisissons les outils selon la tâche et conservons des validations là où elles comptent.</p><div className="ex-ai-grid">{aiPillars.map((slug, index) => { const tool = expertiseTool(slug); return <Link href={expertisePath(slug)} key={slug} style={expertiseStyle(slug)}><span className="ex-ai-logo"><Image src={tool.logo} alt="" width={42} height={42} unoptimized loading="lazy" /></span><span className="ex-ai-number">0{index + 1}</span><h3>{tool.name}</h3><p>{descriptions[index]}</p><span className="ex-ai-link">Explorer les cas d’usage<ArrowUpRight size={16} /></span></Link> })}</div><p className="ex-ai-related">Pour compléter le dispositif : <Link href="/expertise/make">Make</Link>, <Link href="/expertise/gemini">Gemini</Link>, <Link href="/expertise/microsoft-copilot">Microsoft Copilot</Link>. Pour le code et les données : <Link href="/expertise/python">Python</Link> et <Link href="/expertise/dotnet">.NET</Link>, dans nos expertises de développement.</p></div></section>
}

export function ExpertiseDirectory() {
  return <section className="business-section ex-directory" id="annuaire-outils" aria-labelledby="directory-title"><div className="business-container"><div className="ex-directory-heading"><div><p className="business-kicker">Le catalogue complet</p><h2 id="directory-title">Chaque outil.<br /><em>Sa page, ses usages.</em></h2></div><p>{expertiseTools.length} expertises accessibles directement, sans recherche ni filtre à activer.</p></div><ul className="ex-directory-grid">{expertiseTools.map(tool => <li key={tool.slug}><Link href={expertisePath(tool.slug)} style={expertiseStyle(tool.slug)}><Image src={tool.logo} alt="" width={30} height={30} unoptimized loading="lazy" /><span><strong>{tool.name}</strong><small>{tool.category}</small></span><ArrowUpRight size={15} /></Link></li>)}</ul><details className="ex-directory-by-need"><summary>Retrouver les outils par besoin</summary>{expertiseCategories.map(category => <div key={category.id}><h3>{category.label}</h3><p>{category.tools.map((slug, index) => <span key={slug}>{index > 0 && ' · '}<Link href={expertisePath(slug)}>{expertiseTool(slug).name}</Link></span>)}</p></div>)}</details></div></section>
}
