import { pageMetadata } from '@/lib/seo/metadata'
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, MapPin, Search, MousePointer2 } from 'lucide-react';
import ArtisansTrades from '../artisans/_components/ArtisansTrades';
import { ArtisansMethod } from '../artisans/_components/ArtisansMethod';
import { ArtisanPricing, ArtisanCases, ArtisanFaq, ArtisanCta } from '@/components/artisan/ArtisanShared';
import { artisanMetadata, artisanSchema, JsonLd } from '@/lib/artisan/seo';

const faq = [
  { question: 'Pourquoi choisir un site adapté à mon métier plutôt qu’un modèle généraliste ?', answer: 'Un dépannage urgent, un aménagement de jardin et une rénovation complète ne se décident pas de la même façon. Les informations prioritaires, les photos utiles et les questions du formulaire changent. Nous adaptons le contenu et le parcours à vos prestations, sans imposer une structure identique à toutes les entreprises.' },
  { question: 'Litus travaille-t-il uniquement avec les artisans de Lorient et du Mans ?', answer: 'Nos ancrages sont Lorient et Le Mans, mais nous pouvons accompagner une entreprise à distance. Le travail de référencement local porte sur votre véritable zone d’intervention. Il ne consiste pas à afficher des agences fictives dans toutes les communes.' },
  { question: 'Faut-il déjà avoir un site internet ?', answer: 'Non. Nous pouvons partir de vos prestations, de vos photos et de vos coordonnées, ou reprendre un site existant après analyse. Dans le second cas, les contenus utiles, les anciennes adresses et les accès techniques sont recensés avant de décider quoi conserver ou améliorer.' },
  { question: 'Quel budget prévoir pour un site d’artisan ?', answer: 'Les offres publiques Litus comprennent notamment Site Essentiel à 99 €/mois et Visibilité à 229 €/mois. Elles servent de repères : le périmètre, la durée et les éventuelles options sont précisés au devis. La gestion Google Ads démarre à 129 €/mois, sans inclure le budget publicitaire payé à Google.' },
  { question: 'Est-ce que vous garantissez un nombre de devis ou une première place sur Google ?', answer: 'Non. Les demandes dépendent notamment de la concurrence, du secteur géographique, des prestations, du budget et de la capacité à répondre aux prospects. Nous construisons un dispositif mesurable et l’ajustons à partir de demandes réelles, sans promettre un classement ou un volume de chantiers garanti.' },
  { question: 'Je propose plusieurs métiers : dois-je créer plusieurs sites ?', answer: 'Pas forcément. Un même site peut présenter plusieurs activités cohérentes, avec une page utile par prestation et un formulaire qui oriente la demande. Nous évitons de multiplier les sites ou les pages très proches lorsque cela complique la gestion sans aider le visiteur.' },
];

export const metadata = pageMetadata("/artisan", artisanMetadata('Création de sites internet pour artisans', 'Un site adapté à votre métier : plombier, électricien, couvreur, paysagiste et artisans du bâtiment. Création web, SEO local et Google Ads avec Litus.', '/artisan', '/artisan/menuisier-metier.webp', 'Atelier de menuiserie avec outils et établis de travail'));

export default function ArtisanHub() {
  const schema = artisanSchema();
  const graph = { ...schema, '@graph': [...schema['@graph'], { '@type': 'FAQPage', '@id': 'https://www.litus.fr/artisan#faq', mainEntity: faq.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) }] };
  return <div className="artisans-page trade-page trade-hub">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JsonLd({ data: graph }) }} />
    <div className="art-container"><nav className="trade-breadcrumb" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span>/</span><span aria-current="page">Artisans</span></nav></div>
    <section className="trade-hero"><div className="art-container trade-hero-grid"><div className="trade-hero-copy"><p className="art-kicker">Litus · Agence web pour artisans</p><h1>Création de sites internet<br /><em>pour artisans.</em></h1><p className="trade-hero-intro">Vous connaissez votre métier. Nous vous aidons à le rendre visible, à montrer votre savoir-faire et à recevoir des demandes mieux renseignées.</p><p className="trade-promise"><span aria-hidden="true" />Un site pensé pour vos clients, pas seulement pour faire joli.</p><div className="trade-hero-actions"><a href="#metiers-artisans" className="trade-button">Choisir mon métier <ArrowRight size={19} /></a><Link href="/contact" className="trade-text-link">Parlons de votre projet <ArrowRight size={17} /></Link></div><p className="trade-hero-footnote"><MapPin size={15} />Lorient · Le Mans · Partout à distance</p></div><figure className="trade-hero-figure"><div className="trade-photo-wrap"><Image src="/artisan/menuisier-metier.webp" alt="Atelier de menuiserie, avec ses établis et ses outils, illustrant le travail des artisans" width={1280} height={960} priority sizes="(max-width: 850px) 100vw, 48vw" className="trade-hero-photo" /><div className="trade-photo-note"><span>Votre savoir-faire mérite<br /><strong>une vraie place en ligne.</strong></span></div></div><figcaption>Photographie d’illustration · s w / Unsplash · CC0</figcaption></figure></div></section>
    <div className="art-content"><ArtisansTrades />
      <section className="art-section trade-problem"><div className="art-container trade-two-column"><div><p className="art-kicker">Une présence utile</p><h2>Pas plus de pages.<br /><em>Les bonnes réponses.</em></h2></div><div><p>Un particulier cherche un professionnel capable d’intervenir chez lui. Il veut comprendre vos prestations, voir un travail comparable, connaître votre secteur et savoir comment vous joindre. Votre site doit lever ces hésitations avant de lui demander ses coordonnées.</p><p>Nous partons de votre activité réelle : urgences et rappels rapides pour certains métiers, photos de finitions pour d’autres, préparation du devis pour les projets plus longs. Les pages métier ci-dessus détaillent ces différences, les contenus à prévoir et les leviers d’acquisition pertinents.</p></div></div></section>
      <section className="art-section"><div className="art-container"><p className="art-kicker">Le site et ce qui l’alimente</p><h2>Trois leviers.<br /><em>Un seul objectif : des demandes utiles.</em></h2><div className="trade-hub-services"><article><h3>Un site clair et rassurant</h3><p>Prestations, zone d’intervention, photos autorisées, avis vérifiables et contact accessible. Sur téléphone comme sur ordinateur, votre visiteur doit trouver l’essentiel sans chercher.</p><Link href="/creation-site-internet" className="trade-text-link">Création de site <ArrowRight size={17} /></Link></article><article><Search size={23} /><h3>Une visibilité locale cohérente</h3><p>Des pages de services précises, une fiche d’établissement tenue à jour et un maillage naturel. Pas de dizaines de pages où seul le nom de la ville change.</p><Link href="/referencement-naturel" className="trade-text-link">Référencement SEO <ArrowRight size={17} /></Link></article><article><MousePointer2 size={23} /><h3>Une acquisition pilotée</h3><p>Quand Google Ads est pertinent, nous relions l’intention de recherche à une page adaptée et suivons les prises de contact. Le nombre de clics ne remplace pas la qualité des demandes reçues.</p><Link href="/google-ads" className="trade-text-link">Google Ads <ArrowRight size={17} /></Link></article></div></div></section>
      <ArtisanCases slugs={['west-clotures-paysage', 'nos-travaux', 'sarl-pean-j']} />
      <ArtisanPricing />
      <section className="art-section art-method-section" id="methode-artisans"><div className="art-container"><div className="art-section-heading"><p className="art-kicker">Du premier échange à la mise en ligne</p><h2>Une méthode <em>simple et concrète.</em></h2><p>Les campagnes publicitaires sont un levier possible, pas une obligation : nous choisissons les actions selon votre besoin et votre budget.</p></div><ArtisansMethod /></div></section>
      <ArtisanFaq items={faq} /><ArtisanCta />
    </div>
  </div>;
}
