import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Check, ChevronDown, ClipboardCheck, FileSearch, FileText, Gauge, Layers3, Link2, PanelTop, RefreshCw, Search, ShieldCheck, Smartphone } from 'lucide-react'
import { ServiceHero } from '@/components/sections/services/ServiceHero'
import { BusinessSectionHeading, ServiceReveal } from '@/components/sections/services/BusinessService'
import { RefonteHeroDemo } from './_components/RefonteHeroDemo'
import { refonteContactHref, refonteFaq } from './refonte-content'
import './refonte.css'

const title = 'Refonte de site internet : UX, performance & migration SEO | Litus'
const description = 'Faites évoluer votre site avec Litus : audit de l’existant, design, contenus, parcours mobile et migration SEO préparée. Une refonte sur mesure, avec un suivi clair.'
const url = 'https://litus.fr/refonte-site-internet'
export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: url }, openGraph: { title, description, url, siteName: 'Litus', locale: 'fr_FR', type: 'website', images: [{ url: `${url}/opengraph-image`, width: 1200, height: 630, alt: 'Litus — Refonte de site internet, un nouveau cap préparé' }] }, twitter: { card: 'summary_large_image', title, description, images: [`${url}/opengraph-image`] } }
const schema = { '@context': 'https://schema.org', '@graph': [
  { '@type': 'Service', '@id': `${url}#service`, name: 'Refonte de site internet', description, url, serviceType: 'Audit, refonte UX et technique, reprise des contenus et préparation de la migration SEO', provider: { '@type': 'Organization', name: 'Litus', url: 'https://litus.fr' }, areaServed: { '@type': 'Country', name: 'France' } },
  { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: 'https://litus.fr' }, { '@type': 'ListItem', position: 2, name: 'Refonte de site internet', item: url }] },
  { '@type': 'FAQPage', '@id': `${url}#faq`, mainEntity: refonteFaq.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
] }

export default function RefontePage() {
  return <div className="business-service refonte-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} />
    <ServiceHero id="refonte-title" eyebrow="Refonte de site · Lorient & Le Mans" title={'Refonte de site internet.\nUn nouveau cap pour votre site.'} accent="Un nouveau cap pour votre site." description="Votre activité évolue, votre site doit suivre. Nous repensons son design, ses contenus et ses parcours à partir de l’existant, avec une migration préparée pour prendre soin de votre visibilité." primaryAction={{ label: 'Parlons de votre refonte', href: refonteContactHref }} secondaryAction={{ label: 'Voir notre méthode', href: '#methode-refonte' }} visual={<RefonteHeroDemo />} visualBackground="/blog/photos/developpeur-travail.webp" proof={<ul className="business-hero-proof"><li><FileSearch aria-hidden="true" /><span>Un audit de l’existant</span></li><li><Smartphone aria-hidden="true" /><span>Une expérience repensée</span></li><li><Link2 aria-hidden="true" /><span>Une migration préparée</span></li></ul>} />
    <div className="business-content">
      <section className="business-section refonte-opening" aria-labelledby="refonte-opening-title"><div className="business-container business-split"><div><p className="business-kicker">Faire le point avant de refaire</p><h2 id="refonte-opening-title">Votre site a déjà<br /><em>une histoire utile.</em></h2></div><div className="business-copy"><p>Des contenus expliquent votre métier. Des pages sont connues de vos clients. Des liens conduisent déjà vers vous. La refonte commence par comprendre ce que votre site a construit.</p><p>Nous rapprochons cet existant de vos objectifs actuels pour décider <strong>ce qui mérite d’être gardé, amélioré ou repensé.</strong> Le design vient donner une forme cohérente à ces choix.</p></div></div></section>

      <section className="business-section" id="audit-refonte" aria-labelledby="refonte-audit-title"><div className="business-container"><BusinessSectionHeading id="refonte-audit-title" eyebrow="Un diagnostic avant les maquettes" description="Un problème de contact, une navigation confuse et une limite technique n’appellent pas forcément la même réponse. L’état des lieux sert à définir les bonnes priorités.">Identifier ce qui freine.<br /><em>Comprendre ce qui fonctionne.</em></BusinessSectionHeading><ServiceReveal className="refonte-audit-grid">{[
        { icon: PanelTop, title: 'L’offre & les parcours', text: 'La compréhension des services, l’accès au contact et les étapes sur mobile. Nous examinons ce que vos visiteurs cherchent à accomplir.', detail: 'Messages · navigation · formulaires' },
        { icon: Search, title: 'Les contenus & la visibilité', text: 'Les pages utiles, leurs adresses, les liens et les informations de recherche disponibles. Cet inventaire nourrit le plan de reprise.', detail: 'Pages · URL · maillage · recherche' },
        { icon: Gauge, title: 'La base technique', text: 'Les performances, le CMS, les intégrations et les possibilités d’évolution. Nous identifions les contraintes qui pèsent sur le projet.', detail: 'Chargement · administration · connexions' },
      ].map(({ icon: Icon, title: itemTitle, text, detail }) => <article key={itemTitle}><span className="business-icon"><Icon aria-hidden="true" /></span><h3>{itemTitle}</h3><p>{text}</p><span>{detail}</span></article>)}</ServiceReveal></div></section>

      <section className="business-section business-section-warm" aria-labelledby="refonte-decisions-title"><div className="business-container business-split"><figure className="business-photo refonte-planning-photo"><Image src="/blog/photos/planning-bureau.webp" alt="Un carnet ouvert, un crayon, un ordinateur et un téléphone sur une table blanche" width={1400} height={933} sizes="(max-width: 850px) 100vw, 45vw" /><figcaption className="business-photo-note"><strong>Un périmètre clair, avant de commencer.</strong><span>Les priorités se définissent avec les personnes qui connaissent votre activité.</span></figcaption></figure><div className="business-copy"><p className="business-kicker">Les choix qui donnent du sens</p><h2 id="refonte-decisions-title">Une refonte se prépare<br /><em>page par page.</em></h2><div className="refonte-decisions">{[
        ['Ce que l’on conserve', 'Les contenus et les adresses qui restent pertinents, les éléments de votre identité et les fonctions utiles à vos clients.'], ['Ce que l’on fait évoluer', 'La structure de l’offre, la hiérarchie des textes, les parcours de contact, les écrans mobiles et les outils d’administration.'], ['Ce que l’on vérifie', 'La reprise des contenus, les liens, les adresses modifiées, les formulaires, les intégrations et les informations de mesure.'],
      ].map(([itemTitle, text], index) => <details key={itemTitle} open={index === 0}><summary>{itemTitle}<ChevronDown aria-hidden="true" /></summary><p>{text}</p></details>)}</div><p className="refonte-credit">Illustration — <a href="https://commons.wikimedia.org/wiki/File:White_work_table_with_notes,_smartphone_and_laptop_(Unsplash).jpg" target="_blank" rel="noopener noreferrer">JESHOOTS.COM</a> · CC0.</p></div></div></section>

      <section className="business-section" aria-labelledby="refonte-experience-title"><div className="business-container"><BusinessSectionHeading id="refonte-experience-title" eyebrow="Le changement que vos visiteurs voient">Une offre plus lisible.<br /><em>Un site plus facile à utiliser.</em></BusinessSectionHeading><ServiceReveal className="business-grid" data-columns="4">{[
        { icon: Layers3, title: 'Une structure claire', text: 'Des pages organisées autour de vos services et des attentes de vos visiteurs.' }, { icon: FileText, title: 'Des contenus utiles', text: 'Des réponses concrètes, à jour et cohérentes avec votre positionnement.' }, { icon: Smartphone, title: 'Un vrai parcours mobile', text: 'Des écrans lisibles, des contacts accessibles et des formulaires pratiques.' }, { icon: RefreshCw, title: 'Une prise en main prévue', text: 'Un fonctionnement et des modalités de mise à jour adaptés à votre équipe.' },
      ].map(({ icon: Icon, title: itemTitle, text }) => <article className="business-card" key={itemTitle}><span className="business-icon"><Icon aria-hidden="true" /></span><h3>{itemTitle}</h3><p>{text}</p></article>)}</ServiceReveal></div></section>

      <section className="business-section business-section-dark" id="migration-seo" aria-labelledby="refonte-migration-title"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">La visibilité fait partie du chantier</p><h2 id="refonte-migration-title">Un nouveau site.<br /><em>Des repères à préserver.</em></h2><p>Le travail SEO d’une refonte accompagne la reprise des pages et le changement d’adresses éventuel. Les URL pertinentes sont conservées lorsque c’est possible ; les modifications sont documentées et testées.</p><p>Une migration peut entraîner des variations de visibilité. Nous préparons la bascule et son suivi pour limiter les risques et repérer rapidement les problèmes, sans promettre des positions inchangées.</p><Link href="/referencement-naturel" className="business-text-link">Découvrir notre accompagnement SEO<ArrowRight size={17} aria-hidden="true" /></Link></div><div className="refonte-migration-plan">{[
        ['Avant', 'Inventorier les pages et préparer leurs destinations.'], ['Au lancement', 'Vérifier les redirections, les liens et l’accès aux contenus.'], ['Après', 'Suivre l’exploration, les erreurs et l’évolution de la visibilité.'],
      ].map(([itemTitle, text], index) => <article key={itemTitle}><span>0{index + 1}</span><div><h3>{itemTitle}</h3><p>{text}</p></div><Check aria-hidden="true" /></article>)}<p><ShieldCheck aria-hidden="true" />Un plan de migration adapté à votre site.</p></div></div></section>

      <section className="business-section" id="methode-refonte" aria-labelledby="refonte-method-title"><div className="business-container"><BusinessSectionHeading id="refonte-method-title" eyebrow="Un projet organisé de bout en bout" description="Le site existant, la nouvelle version et la mise en service sont pensés ensemble. Vous validez les choix et les écrans avant la bascule.">De l’état des lieux<br /><em>au nouveau départ.</em></BusinessSectionHeading><ServiceReveal className="refonte-method-grid">{[
        { title: 'Auditer & cadrer', text: 'Comprendre le site, fixer les priorités et définir le périmètre de la reprise.', result: 'Un diagnostic et une feuille de route.' }, { title: 'Concevoir & valider', text: 'Repenser la structure, travailler les contenus et valider les maquettes utiles.', result: 'Des pages et des parcours concrets.' }, { title: 'Développer & tester', text: 'Préparer la nouvelle version et vérifier la reprise, les fonctions et les adresses.', result: 'Une version prête pour la recette.' }, { title: 'Basculer & suivre', text: 'Planifier la mise en ligne et contrôler les pages, les contacts et la migration.', result: 'Un lancement accompagné.' },
      ].map((item, index) => <article key={item.title}><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p><strong>{item.result}</strong></article>)}</ServiceReveal></div></section>

      <section className="business-section business-section-soft" aria-labelledby="refonte-handover-title"><div className="business-container refonte-handover"><span className="business-icon"><ClipboardCheck aria-hidden="true" /></span><div><h2 id="refonte-handover-title">Une mise en ligne,<br /><em>et une suite prévue.</em></h2><p>Documentation, accès, prise en main et suivi : nous précisons ce qui est livré et la façon dont votre site sera accompagné après la refonte.</p></div><Link href={refonteContactHref} className="site-cta-secondary">Faisons le point sur votre site<ArrowRight size={17} aria-hidden="true" /></Link></div></section>

      <section className="business-section" id="faq" aria-labelledby="refonte-faq-title"><div className="business-container"><BusinessSectionHeading id="refonte-faq-title" eyebrow="Vos questions">Refaire votre site,<br /><em>avec une vision claire.</em></BusinessSectionHeading><div className="business-faq">{refonteFaq.map(item => <details key={item.question}><summary>{item.question}<ChevronDown size={17} aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></div></section>

      <section className="business-section" aria-labelledby="refonte-contact-title"><div className="business-container business-final"><div><p className="business-kicker">Partons de votre site actuel</p><h2 id="refonte-contact-title">Votre site peut mieux<br /><em>représenter votre activité.</em></h2><p>Montrez-nous votre site et expliquez-nous ce qui a changé dans votre entreprise. Nous définirons les priorités et la bonne façon de le faire évoluer.</p></div><div className="business-final-actions"><Link href={refonteContactHref} className="site-cta-primary">Parlons de votre refonte<ArrowRight size={18} aria-hidden="true" /></Link><span>Premier échange · Devis sur mesure</span><a href="tel:+33744985521">07 44 98 55 21</a></div></div><nav className="business-container refonte-related" aria-label="Expertises complémentaires"><Link href="/creation-site-internet">Création de site internet<ArrowUpRight size={16} aria-hidden="true" /></Link><Link href="/creation-site-ecommerce">Site e-commerce<ArrowUpRight size={16} aria-hidden="true" /></Link><Link href="/referencement-naturel">Référencement naturel<ArrowUpRight size={16} aria-hidden="true" /></Link></nav></section>
    </div>
  </div>
}
