export const refonteContactHref = '/contact?objet=Refonte%20de%20site%20internet'
export const refonteFaq = [
  { question: 'Comment savoir si mon site a besoin d’une refonte ?', answer: 'Les signes peuvent être une offre devenue difficile à comprendre, un parcours mobile peu pratique, des contenus compliqués à modifier ou des limites techniques. L’audit permet de distinguer ce qui demande une correction ciblée de ce qui justifie une refonte plus large. L’âge du site ne suffit pas à lui seul.' },
  { question: 'Peut-on conserver les contenus et les pages qui fonctionnent ?', answer: 'Oui. L’inventaire sert justement à identifier les pages utiles aux visiteurs, les contenus qui contribuent à votre visibilité et les éléments à conserver. Nous décidons ensuite quoi reprendre, enrichir, regrouper ou retirer. Une modification d’adresse est traitée dans le plan de migration.' },
  { question: 'Est-il possible de garantir que le référencement ne baissera pas ?', answer: 'Non, aucune refonte ne permet de garantir des positions inchangées. Nous préparons les contenus, les adresses, les redirections et les contrôles pour limiter les risques. Des variations peuvent apparaître pendant que les moteurs explorent le nouveau site ; le suivi après mise en ligne sert à repérer les problèmes et à agir.' },
  { question: 'Que deviennent les anciennes adresses des pages ?', answer: 'Nous cherchons d’abord à conserver les URL pertinentes. Lorsqu’une adresse doit changer, elle est reliée à sa nouvelle destination dans un plan de redirection. Les liens internes et les adresses importantes sont vérifiés. Les pages retirées sont étudiées individuellement plutôt que renvoyées indistinctement vers l’accueil.' },
  { question: 'Mon site doit-il être coupé pendant les travaux ?', answer: 'La nouvelle version est généralement préparée dans un environnement distinct pendant que le site actuel reste disponible. La bascule se planifie avec les sauvegardes, les vérifications et les contraintes de votre hébergement. Le déroulement précis dépend des outils et des intégrations de votre site.' },
  { question: 'Faut-il changer de CMS, d’hébergement ou de nom de domaine ?', answer: 'Pas nécessairement. Nous évaluons l’existant et vos besoins d’administration avant de proposer un changement. Quand plusieurs transformations sont nécessaires, leur ordre est étudié afin de rendre les tests et la migration plus lisibles. La solution retenue doit être utile à votre activité.' },
  { question: 'Quel budget et quel délai pour refaire mon site ?', answer: 'Le volume de pages, les contenus à reprendre, les fonctions, le design et le travail de migration déterminent le périmètre. Après un premier état des lieux, nous proposons un devis et un calendrier adaptés. Les éléments à conserver, les travaux prévus et l’accompagnement après lancement sont explicités.' },
  { question: 'Comment vérifiez-vous la refonte après la mise en ligne ?', answer: 'Nous contrôlons notamment les pages principales, les redirections, les formulaires, les parcours mobiles et les éléments de mesure prévus. Les informations disponibles dans les outils de suivi permettent ensuite de surveiller l’exploration, la visibilité et les demandes. Les modalités et la durée du suivi sont convenues dans le projet.' },
] as const
