export type Trade = {
  slug: string; name: string; subject: string; title: string; description: string; intro: string; promise: string;
  style: 'urgent' | 'technical' | 'visual'; photoAlt: string; photoCredit: string;
  problem: { title: string; paragraphs: string[] };
  priorities: { title: string; text: string }[];
  pages: { name: string; purpose: string }[];
  local: { title: string; text: string; queries: string[] };
  channels: { seo: string; ads: string; decision: string };
  qualification: { title: string; fields: string[]; text: string };
  budget: string; preparation: string[]; journey: string[];
  cases: string[]; related: string[]; faq: { question: string; answer: string }[];
  cta: string; sources: string[];
};

// Authored separately per trade. The presentation primitives are shared, not
// the business argument, search intent, project structure or FAQ answers.
export const trades: Trade[] = [
  {
    slug: 'plombier', name: 'Plombier', subject: 'un plombier', style: 'urgent',
    title: 'Création de site internet pour plombier',
    description: 'Un site de plomberie conçu pour les appels locaux, le dépannage et les devis sanitaires. Prix Litus, SEO et Google Ads adaptés à votre zone.',
    intro: 'Une fuite ne laisse pas le temps de parcourir un site compliqué. Nous mettons votre disponibilité, vos prestations et votre téléphone au premier plan, tout en donnant une vraie place aux projets de salle de bain.',
    promise: 'L’urgence trouve un numéro. Le projet trouve des réponses.',
    photoAlt: 'Plombier en tenue bleue serrant un raccord de tuyauterie avec une clé', photoCredit: 'Photographie d’illustration · Pexels',
    problem: { title: 'Une fuite et une salle de bain ne se choisissent pas de la même manière.', paragraphs: [
      'La personne qui découvre une fuite consulte son téléphone, vérifie que vous intervenez dans sa commune et cherche à joindre quelqu’un. Celle qui prépare une rénovation compare vos réalisations, veut comprendre les travaux et attend un devis. Mélanger ces deux besoins sous une simple liste de prestations fait perdre de la clarté aux deux parcours.',
      'Votre site doit aussi éviter les appels inutiles : demandes hors secteur, horaires où personne ne répond, interventions que vous ne faites pas. Nous définissons les limites de votre activité avant d’écrire les pages. Le dépannage n’est mis en avant que si vous le proposez réellement ; aucune disponibilité permanente n’est annoncée par défaut.',
    ] },
    priorities: [
      { title: 'Un appel accessible immédiatement', text: 'Sur mobile, le numéro doit être lisible et cliquable sans ouvrir un menu. Vos horaires et votre secteur restent proches du bouton : le visiteur sait à qui il s’adresse avant d’appeler.' },
      { title: 'Des prestations sans ambiguïté', text: 'Recherche de fuite, débouchage, chauffe-eau et installation sanitaire ont des attentes différentes. Chaque page explique les situations prises en charge, le premier échange et les informations nécessaires à l’intervention.' },
      { title: 'Des projets mieux préparés', text: 'Pour une salle de bain, des photos autorisées et un formulaire dédié permettent de décrire l’existant, la commune et le calendrier. Vous recevez un point de départ pour un devis, pas une promesse de prix automatique.' },
    ],
    pages: [
      { name: 'Accueil et secteur', purpose: 'Présenter votre entreprise, vos horaires et les deux entrées dépannage / projet.' },
      { name: 'Dépannage plomberie', purpose: 'Expliquer comment vous contacter pour une intervention réellement disponible.' },
      { name: 'Recherche de fuite', purpose: 'Distinguer diagnostic, accès aux réseaux et réparation à prévoir après constat.' },
      { name: 'Débouchage', purpose: 'Préciser les installations traitées, sans promettre une solution avant diagnostic.' },
      { name: 'Chauffe-eau', purpose: 'Séparer réparation, remplacement et installation selon vos compétences.' },
      { name: 'Installation sanitaire', purpose: 'Montrer les équipements que vous posez et le déroulement d’un chantier.' },
      { name: 'Rénovation de salle de bain', purpose: 'Présenter des réalisations et qualifier les projets planifiés.' },
      { name: 'Entreprise, réalisations et contact', purpose: 'Rassurer sur votre identité, présenter vos travaux et faciliter le devis.' },
    ],
    local: { title: 'Être présent sur « plombier + ville », mais pour les bonnes interventions.', text: 'Votre fiche Google Business Profile, le site et les horaires doivent raconter la même réalité. Nous organisons les contenus autour des communes effectivement desservies et des services que vous souhaitez développer. Une page consacrée au débouchage peut répondre plus précisément qu’une page générale à un besoin déjà identifié. Les comptes rendus de chantiers apportent des preuves locales, sans exposer l’adresse privée des clients.', queries: ['plombier Lorient', 'recherche de fuite Le Mans', 'débouchage canalisation près de chez moi', 'devis rénovation salle de bain'] },
    channels: { seo: 'Le référencement naturel construit des points d’entrée pour vos prestations et vos chantiers. Il permet aussi à une personne recommandée par un voisin de vérifier votre sérieux. Les positions évoluent : on les suit dans la durée plutôt que de promettre une première place.', ads: 'Google Ads peut donner rapidement de la visibilité aux dépannages sur les créneaux où vous pouvez répondre. Nous séparons l’urgence des projets sanitaires et écartons les recherches de tutoriels, d’emploi ou de pièces seules lorsqu’elles ne correspondent pas à votre activité.', decision: 'Avant d’augmenter les dépenses, on regarde les appels réellement reçus, les interventions possibles et les devis acceptés. Un clic sur le téléphone n’est pas, à lui seul, un nouveau chantier.' },
    qualification: { title: 'Un devis plomberie qui commence par la bonne question.', fields: ['Dépannage ou projet planifié ?', 'Commune d’intervention', 'Équipement ou pièce concernée', 'Disponibilité pour être rappelé'], text: 'L’urgence doit garder un accès direct à l’appel. Le formulaire sert surtout aux demandes qui peuvent être préparées. Les photographies de l’installation peuvent être proposées dans un second temps, sans obliger le visiteur à créer un compte.' },
    budget: 'Le coût de votre site de plomberie dépend surtout de la séparation des parcours, du nombre de prestations détaillées et des contenus à produire pour les salles de bain. Un suivi des appels ou une campagne de dépannage demande un cadrage distinct de la simple mise en ligne. Les horaires, les tarifs d’intervention que vous décidez de publier et les coordonnées doivent rester faciles à actualiser.',
    preparation: ['Les interventions acceptées et celles que vous refusez', 'Les communes et créneaux réellement couverts', 'Vos photos de salles de bain et installations autorisées', 'Votre manière de traiter un appel ou un devis'],
    journey: ['Recherche : fuite d’eau Lorient', 'Page recherche de fuite', 'Secteur, horaires et présentation de l’entreprise', 'Appel ou demande de rappel', 'Intervention qualifiée dans votre suivi'],
    cases: [], related: ['chauffagiste-climatisation', 'renovation-interieure'],
    faq: [
      { question: 'Quel prix prévoir pour un site internet de plombier ?', answer: 'L’offre publique Site Essentiel de Litus est affichée à 99 €/mois. Elle constitue un point de départ, pas le prix de toutes les architectures plomberie. Les pages de dépannage, les contenus sanitaires et l’acquisition sont cadrés au devis ; le budget versé à Google est distinct.' },
      { question: 'Faut-il un site différent pour les urgences et les salles de bain ?', answer: 'Pas nécessairement. Un même site peut proposer deux parcours clairement séparés. L’urgence conduit vers l’appel et les informations pratiques ; la salle de bain vers les réalisations et une demande de devis préparée.' },
      { question: 'Google Business Profile suffit-il pour un plombier ?', answer: 'La fiche aide à présenter vos coordonnées, vos horaires et vos avis. Le site permet de détailler les prestations et d’expliquer votre fonctionnement. Les deux se complètent : une fiche ne remplace pas toutes les réponses attendues sur un projet sanitaire.' },
      { question: 'Dois-je faire de la publicité si je suis seul sur les chantiers ?', answer: 'Seulement avec une organisation capable de traiter les demandes. Des campagnes limitées à vos créneaux et à votre secteur sont préférables à des annonces diffusées en continu alors que vous ne pouvez pas décrocher.' },
      { question: 'Peut-on travailler plusieurs villes sans multiplier les pages identiques ?', answer: 'Oui. On commence par une zone d’intervention claire. Une page locale supplémentaire se justifie si elle apporte des informations utiles : chantiers, prestations disponibles ou conditions de déplacement, pas un changement de nom de ville.' },
      { question: 'Comment savoir si le site apporte des clients et pas seulement des visites ?', answer: 'On distingue demandes de formulaire, clics d’appel, appels qualifiés et interventions réalisées. Le rapprochement avec votre suivi commercial évite d’additionner plusieurs fois le même prospect ou de confondre visite et chiffre d’affaires.' },
    ],
    cta: 'Faisons de votre prochain appel le début d’une vraie intervention.',
    sources: ['https://www.coutsite.fr/prix-site-internet-artisan/plombier', 'https://www.vincentduquesne.net/google-ads-plombier-chauffagiste.html', 'https://artiads.fr/metiers/plombier/'],
  },
  {
    slug: 'electricien', name: 'Électricien', subject: 'un électricien', style: 'technical',
    title: 'Création de site internet pour électricien',
    description: 'Présentez dépannage, rénovation électrique, domotique et bornes de recharge avec un site clair. Création web, SEO local et acquisition pour électriciens.',
    intro: 'Du tableau à remplacer à la borne de recharge, vos clients ne recherchent pas la même prestation. Un site précis valorise vos compétences et vous aide à recevoir des demandes que vous pouvez réellement prendre en charge.',
    promise: 'Vos compétences méritent mieux qu’une liste de services.',
    photoAlt: 'Électricien contrôlant les connexions d’un tableau électrique avec un multimètre', photoCredit: 'Photographie d’illustration · Pexels',
    problem: { title: 'Vos clients décrivent un problème. Vous connaissez la solution technique.', paragraphs: [
      'Un particulier parle d’un disjoncteur qui saute ou d’une prise qui ne fonctionne plus. Un propriétaire qui rénove cherche à refaire une installation. Un commerce attend une organisation compatible avec ses horaires. Le site doit traduire ces demandes en prestations compréhensibles, sans obliger le visiteur à maîtriser votre vocabulaire.',
      'Il doit également distinguer ce que vous installez, ce que vous diagnostiquez et les équipements sur lesquels vous intervenez. Une qualification ou une spécialité comme la recharge électrique n’est affichée que si elle correspond à votre activité et à vos justificatifs. La précision rassure davantage qu’une accumulation de badges.',
    ] },
    priorities: [
      { title: 'Une entrée par situation', text: 'Dépannage, rénovation et nouvelle installation ont chacun leur accès. Le visiteur comprend si sa demande relève d’un rappel, d’une visite ou d’un projet à préparer, sans chercher dans un catalogue technique.' },
      { title: 'Des preuves lisibles', text: 'Des photographies de tableaux, de luminaires ou d’équipements posés montrent votre soin. Les qualifications détenues sont expliquées avec leur périmètre plutôt que présentées comme une garantie valable pour tous les travaux.' },
      { title: 'Des demandes déjà orientées', text: 'Type de bâtiment, commune et nature du besoin suffisent souvent pour préparer le premier échange. Pour une borne ou la domotique, quelques informations complémentaires évitent de traiter tous les contacts comme des urgences.' },
    ],
    pages: [
      { name: 'Électricité générale', purpose: 'Présenter votre clientèle : particuliers, commerces ou bâtiments professionnels.' },
      { name: 'Dépannage électrique', purpose: 'Donner vos horaires et le moyen de joindre l’entreprise sans conseil de manipulation risquée.' },
      { name: 'Rénovation d’installation', purpose: 'Expliquer votre démarche de visite, d’étude et de chiffrage.' },
      { name: 'Tableaux électriques', purpose: 'Présenter les remplacements et adaptations réalisés après diagnostic.' },
      { name: 'Éclairage', purpose: 'Montrer des ambiances et des équipements intérieurs ou extérieurs.' },
      { name: 'Borne de recharge', purpose: 'Une page si vous proposez ce service, avec qualifications détenues et projet à étudier.' },
      { name: 'Domotique', purpose: 'Décrire des usages concrets, les équipements compatibles et l’accompagnement.' },
      { name: 'Références et demande de visite', purpose: 'Regrouper des travaux documentés et un formulaire adapté au bâtiment.' },
    ],
    local: { title: 'Du référencement « électricien » aux recherches d’équipements.', text: 'Nous différencions les requêtes généralistes des besoins précis. Une entreprise spécialisée dans la rénovation n’a pas forcément intérêt à attirer toutes les demandes de dépannage. Le site relie les prestations aux communes où vous vous déplacez, tandis que la fiche Google renseigne l’activité réelle et les horaires. Les projets réalisés permettent de montrer le type de bâtiment et la nature des travaux sans divulguer de données privées.', queries: ['électricien Le Mans', 'remplacement tableau électrique Lorient', 'installation borne recharge maison', 'devis rénovation électrique appartement'] },
    channels: { seo: 'Des pages pédagogiques sur vos installations aident les clients à préparer un projet et à comparer les entreprises. Le référencement s’appuie sur des contenus accessibles, vos références et la cohérence de votre présence locale, pas sur la répétition de noms de normes.', ads: 'Les campagnes peuvent être séparées entre dépannage, rénovation et recharge. Nous adaptons la page d’arrivée à l’équipement recherché et filtrons les demandes d’emploi, de formation ou d’achat de matériel seul si elles ne vous concernent pas.', decision: 'La bonne mesure dépend du chantier visé : appel exploitable pour le dépannage, visite programmée pour une installation. Le budget se règle aussi sur vos disponibilités et votre capacité à réaliser les visites.' },
    qualification: { title: 'Préparer une visite, sans demander au client de faire un diagnostic.', fields: ['Maison, appartement ou local professionnel', 'Dépannage, rénovation ou équipement neuf', 'Commune du bâtiment', 'Échéance et contact pour la visite'], text: 'Le formulaire recueille ce que le client peut décrire simplement. Il n’a pas à démonter un équipement ou à fournir des mesures électriques. Les informations techniques sont complétées avec vous lors d’un échange adapté.' },
    budget: 'Pour un site d’électricien, le périmètre change selon la place donnée au dépannage, au tertiaire et aux spécialités. Une galerie de tableaux demande surtout un tri documentaire ; des pages dédiées à la recharge ou à la domotique nécessitent un travail rédactionnel supplémentaire. La mesure des appels, les campagnes et les futures mises à jour d’équipements sont à distinguer dans le devis.',
    preparation: ['Vos clientèles et équipements pris en charge', 'Vos qualifications effectivement détenues', 'Des photos autorisées de vos installations', 'Votre secteur et votre organisation des visites'],
    journey: ['Recherche : borne de recharge maison Le Mans', 'Page installation de borne', 'Compétences, exemples et déroulement', 'Demande de visite', 'Projet étudié puis devis suivi'],
    cases: [], related: ['renovation-interieure', 'chauffagiste-climatisation'],
    faq: [
      { question: 'Quel budget pour le site d’un électricien indépendant ?', answer: 'Le Site Essentiel Litus est affiché à 99 €/mois sur la page Tarifs. Un site qui traite plusieurs clientèles ou spécialités demande un cadrage différent. On précise les pages, la rédaction, le suivi et les fonctionnalités avant de confirmer la formule.' },
      { question: 'Faut-il une page spéciale pour les bornes de recharge ?', answer: 'Oui si vous proposez réellement leur installation. La page explique votre périmètre, les éléments étudiés avant devis et vos qualifications détenues. Elle ne promet pas un prix universel sans connaître l’installation existante.' },
      { question: 'Comment présenter des travaux techniques à des particuliers ?', answer: 'En partant du besoin : rénover un logement, éclairer une terrasse ou équiper un garage. Des photos légendées et une explication du déroulement sont plus utiles qu’une liste d’abréviations sans contexte.' },
      { question: 'Google Ads peut-il promouvoir uniquement la rénovation électrique ?', answer: 'Oui. On sélectionne les recherches et les zones adaptées, avec une page dédiée et des exclusions. Il n’est pas nécessaire de présenter l’entreprise comme un service de dépannage permanent pour lancer des campagnes.' },
      { question: 'Dois-je publier toutes mes certifications ?', answer: 'Seulement les qualifications à jour et pertinentes pour les prestations annoncées. Nous vous demandons les justificatifs et formulons leur portée avec précision, sans vous attribuer un label non détenu.' },
      { question: 'Comment faire connaître une nouvelle spécialité en électricité ?', answer: 'On commence par une page documentée, des réalisations lorsque vous en disposez et une mise à jour cohérente de la fiche Google. Une campagne ciblée peut compléter ce travail, après définition de la clientèle et du budget.' },
    ], cta: 'Attirons les projets qui correspondent vraiment à votre savoir-faire.',
    sources: ['https://www.aerialgrouplyon.com/creation-site-electricien.asp', 'https://agencecentauri.com/blog/creation-site-internet-electricien', 'https://www.studio120k.com/fr/site-internet-electricien'],
  },
  {
    slug: 'chauffagiste-climatisation', name: 'Chauffagiste / Climatisation', subject: 'un chauffagiste ou climaticien', style: 'technical',
    title: 'Création de site internet pour chauffagiste et climaticien',
    description: 'Installation de PAC, entretien et climatisation : un site qui distingue vos offres et vos saisons. SEO local, devis qualifiés et campagnes Google Ads.',
    intro: 'Un chauffage en panne, un contrat d’entretien et une installation de climatisation appellent trois réponses différentes. Nous organisons votre site et votre acquisition autour de vos équipements, de vos saisons et de votre capacité d’intervention.',
    promise: 'Trois besoins. Des parcours distincts. Une activité mieux présentée.',
    photoAlt: 'Technicien intervenant sur un appareil de climatisation ouvert', photoCredit: 'Photographie d’illustration · Pexels',
    problem: { title: 'Ne laissez pas les pics de demande décider seuls de votre planning.', paragraphs: [
      'Le dépannage arrive souvent au moment où les équipes sont déjà sollicitées. À l’inverse, un remplacement de chauffage ou une climatisation peut se préparer en amont. Un site qui ne montre qu’un numéro d’urgence masque vos projets d’installation et vos prestations d’entretien.',
      'Le visiteur compare aussi les systèmes, les marques et les interlocuteurs. Il doit comprendre si vous installez, entretenez ou dépannez l’appareil qu’il possède. Nous construisons des parcours qui apportent ces réponses sans promettre des économies, une aide financière ou une disponibilité avant l’étude du dossier.',
    ] },
    priorities: [
      { title: 'Séparer les trois activités', text: 'Installation, entretien et dépannage disposent de leurs propres pages et contacts. Vous pouvez donner la priorité aux prestations que vous souhaitez développer au lieu de tout faire arriver dans le même formulaire.' },
      { title: 'Préparer l’étude du logement', text: 'Pour une pompe à chaleur ou une climatisation, le type de bâtiment et l’équipement existant orientent le premier échange. Le site explique qu’une proposition sérieuse nécessite une étude, pas un prix automatique.' },
      { title: 'Rassurer après la pose', text: 'Votre accompagnement, les équipements pris en charge et les modalités d’entretien méritent une place visible. Les clients comprennent comment vous joindre après l’installation et quelles prestations relèvent de votre entreprise.' },
    ],
    pages: [
      { name: 'Installation de chauffage', purpose: 'Présenter les systèmes proposés et votre démarche d’étude.' },
      { name: 'Pompe à chaleur', purpose: 'Distinguer les solutions, les bâtiments et les questions à examiner.' },
      { name: 'Climatisation réversible', purpose: 'Expliquer les pièces concernées, l’implantation et les étapes du projet.' },
      { name: 'Entretien', purpose: 'Décrire vos prestations et la demande de rendez-vous.' },
      { name: 'Dépannage', purpose: 'Annoncer uniquement les horaires et appareils réellement pris en charge.' },
      { name: 'Marques et compétences', purpose: 'Préciser vos équipements, formations et qualifications vérifiables.' },
      { name: 'Installations réalisées', purpose: 'Montrer les unités, leur intégration et le contexte des logements.' },
      { name: 'Demander une étude', purpose: 'Recueillir les informations utiles avant une visite technique.' },
    ],
    local: { title: 'Des recherches locales, avec une forte dimension d’équipement.', text: '« Chauffagiste » ne décrit pas toujours le projet recherché. Nous travaillons les pages installation, entretien et dépannage séparément, avec une zone d’intervention réaliste. Le référencement de la climatisation tient compte des usages du logement, tandis qu’une recherche d’entretien attend surtout un interlocuteur et un rendez-vous. La fiche Google complète ces pages avec des coordonnées cohérentes et des installations autorisées à la publication.', queries: ['chauffagiste Lorient', 'installation pompe à chaleur Le Mans', 'entretien chaudière près de chez moi', 'devis climatisation réversible maison'] },
    channels: { seo: 'Les contenus sur l’installation et l’entretien permettent de préparer la demande avant les périodes de forte sollicitation. Des pages bien différenciées évitent que la climatisation et le chauffage se concurrencent dans un même texte imprécis.', ads: 'Nous pouvons répartir les campagnes par équipement et par objectif : rendez-vous d’entretien, projet de PAC ou climatisation. Les budgets et la diffusion évoluent avec vos disponibilités. Les recherches de pièces détachées ou d’aides sans projet pertinent sont analysées séparément.', decision: 'La priorité est de mesurer des études réalisables. Une demande hors secteur ou sur un appareil que vous ne maintenez pas n’a pas la même valeur qu’une visite d’installation planifiée.' },
    qualification: { title: 'Une demande d’étude utile à votre équipe technique.', fields: ['Installation, entretien ou dépannage', 'Type de logement et commune', 'Équipement actuel et besoin recherché', 'Période souhaitée pour le projet'], text: 'Nous limitons les questions aux éléments compréhensibles par le particulier. Surface indicative, photographies et référence d’appareil peuvent compléter le dossier ensuite. Le dimensionnement et l’éligibilité éventuelle aux aides restent à vérifier par les interlocuteurs compétents.' },
    budget: 'Votre budget web varie avec le nombre de familles d’équipements et la profondeur de l’accompagnement éditorial. Présenter correctement les marques, l’entretien et les nouvelles installations prend plus de travail qu’une page de coordonnées. Une prise de rendez-vous connectée ou des campagnes saisonnières sont chiffrées selon vos outils et vos besoins, sans inventer une formule propre aux chauffagistes.',
    preparation: ['Les systèmes et marques sur lesquels vous intervenez', 'Votre répartition installation / entretien / dépannage', 'Vos périodes de disponibilité et zones', 'Vos qualifications et photos d’installations'],
    journey: ['Recherche : installation climatisation Le Mans', 'Page climatisation réversible', 'Exemples, étude et équipements proposés', 'Description du logement', 'Visite technique et suivi du devis'],
    cases: [], related: ['plombier', 'electricien'],
    faq: [
      { question: 'Faut-il un seul site pour le chauffage et la climatisation ?', answer: 'Un même site peut très bien réunir les deux. Il faut en revanche des pages et des entrées distinctes pour l’installation, l’entretien et le dépannage afin de ne pas envoyer toutes les demandes vers une réponse générique.' },
      { question: 'Combien coûte un site de chauffagiste chez Litus ?', answer: 'Nos offres publiques commencent avec Site Essentiel à 99 €/mois. Le périmètre adapté à vos équipements, aux contenus et aux prises de rendez-vous est confirmé au devis. Les campagnes publicitaires et leur budget média ne se confondent pas avec la création du site.' },
      { question: 'Peut-on adapter les campagnes aux saisons ?', answer: 'Oui. La diffusion peut être orientée vers les prestations et les zones que vous pouvez servir à un moment donné. Nous évitons de lancer davantage de demandes d’entretien si votre planning ne permet pas de les traiter.' },
      { question: 'Doit-on parler des aides pour les pompes à chaleur ?', answer: 'Seulement avec des informations tenues à jour et des renvois vers les organismes officiels. Le site ne doit pas garantir une éligibilité ni afficher un montant valable pour tous les logements. Le dossier réel reste à examiner.' },
      { question: 'Comment attirer davantage de contrats d’entretien ?', answer: 'Une page dédiée précise les appareils concernés, la prestation et la manière de demander un rendez-vous. Un accès clair depuis les pages d’installation permet aussi aux clients déjà équipés de retrouver cette offre.' },
      { question: 'Peut-on connecter les demandes à notre planning ?', answer: 'Oui, après examen de votre outil et de vos règles de disponibilité. Une demande de rendez-vous à confirmer est parfois plus pertinente qu’une réservation automatique de visite technique qui ignore les temps de trajet.' },
    ], cta: 'Préparons votre visibilité avant la prochaine saison.',
    sources: ['https://www.beffroi.studio/artisans/chauffagiste', 'https://www.trafimedia.fr/climatisation.html', 'https://ioquery.fr/google-ads-pompe-a-chaleur'],
  },
  {
    slug: 'couvreur', name: 'Couvreur', subject: 'un couvreur', style: 'visual',
    title: 'Création de site internet pour couvreur',
    description: 'Mettez vos chantiers de toiture en valeur avec un site de couvreur : galeries, demandes de devis, SEO local et campagnes Google Ads ciblées.',
    intro: 'Une toiture engage le budget et la confiance d’un propriétaire. Nous concevons un site qui montre vos chantiers, explique vos interventions et donne un chemin clair vers une visite et un devis.',
    promise: 'Avant le devis, il y a la confiance.',
    photoAlt: 'Couvreur travaillant sur la couverture d’une maison en construction', photoCredit: 'Photographie d’illustration · Clément Proust / Pexels',
    problem: { title: 'Vos futurs clients ne peuvent pas juger une toiture depuis leur salon.', paragraphs: [
      'Une infiltration inquiète. Une réfection complète demande de comparer plusieurs solutions et interlocuteurs. Dans les deux cas, le propriétaire cherche des signes concrets de sérieux : une entreprise identifiable, des photos, un secteur annoncé et une explication de la visite. Une formule vague sur le « travail de qualité » ne suffit pas.',
      'Votre site peut montrer la réalité du chantier : état initial, matériaux, étapes et résultat. Nous organisons ces éléments pour distinguer réparation, entretien et rénovation. Les prestations de charpente ou d’isolation ne sont proposées que si elles font partie de votre périmètre effectif.',
    ] },
    priorities: [
      { title: 'Des chantiers qui expliquent', text: 'Une galerie ne se limite pas à des toits vus de loin. Des légendes précisent le type de couverture, le besoin initial et les travaux réalisés. Les avant/après sont identifiés sans transformer une photo d’illustration en référence.' },
      { title: 'Une entreprise identifiable', text: 'Présentation de l’équipe, coordonnées, assurances pertinentes et déroulement de la visite apportent des repères. Nous publions les informations que vous pouvez documenter, sans ajouter de certifications de convenance.' },
      { title: 'Un contact adapté au besoin', text: 'La recherche de fuite garde un chemin court vers l’appel. Un projet de réfection peut renseigner le type de bâtiment, la commune et les travaux envisagés pour préparer une visite utile.' },
    ],
    pages: [
      { name: 'Réfection de toiture', purpose: 'Décrire la visite, le choix des matériaux et les étapes du chantier.' },
      { name: 'Recherche de fuite', purpose: 'Présenter votre réponse aux infiltrations et les conditions de déplacement.' },
      { name: 'Zinguerie et gouttières', purpose: 'Montrer les ouvrages et les détails qui distinguent votre savoir-faire.' },
      { name: 'Entretien de couverture', purpose: 'Préciser les opérations proposées et leurs limites selon l’état du toit.' },
      { name: 'Isolation de toiture', purpose: 'Une page dédiée uniquement si cette prestation est dans votre activité.' },
      { name: 'Fenêtres de toit', purpose: 'Présenter les créations ou remplacements effectivement réalisés.' },
      { name: 'Chantiers avant/après', purpose: 'Organiser les projets par matériau et nature d’intervention.' },
      { name: 'Entreprise et visite devis', purpose: 'Donner des repères fiables et recueillir un projet sans devis fictif.' },
    ],
    local: { title: 'Associer la proximité à des preuves de couverture.', text: 'Une page sur la toiture en ardoise, un chantier documenté et une zone précise répondent mieux à un propriétaire que des dizaines de pages de communes interchangeables. Nous faisons correspondre les termes de recherche aux interventions proposées et à votre implantation. Les avis existants restent attribués à leur auteur ; la fiche Google et le site renvoient vers les mêmes coordonnées et les mêmes prestations.', queries: ['couvreur Lorient', 'réparation fuite toiture Le Mans', 'devis réfection toiture ardoise', 'zingueur près de chez moi'] },
    channels: { seo: 'Les pages de prestations et les récits de chantiers construisent une présence durable sur les besoins de toiture. Un contenu utile décrit les matériaux et le déroulement du projet ; il ne cherche pas à diagnostiquer l’état d’une charpente à distance.', ads: 'Les campagnes peuvent distinguer recherche de fuite, réfection et entretien. Nous évitons de faire arriver une demande d’infiltration sur une galerie seule. Le secteur, les disponibilités et les mots-clés exclus sont ajustés pour limiter les contacts impossibles à traiter.', decision: 'Le suivi commercial doit aller jusqu’aux visites pertinentes et aux devis. On n’évalue pas une demande de réfection comme un simple clic d’annonce : son traitement et son calendrier font partie de la décision.' },
    qualification: { title: 'Préparer une visite de toiture sans imposer un diagnostic au client.', fields: ['Commune et type de bâtiment', 'Fuite, entretien ou rénovation', 'Matériau connu, si disponible', 'Description et période souhaitée'], text: 'Les photos existantes peuvent aider, mais le formulaire ne demande jamais au particulier de monter sur son toit. Le chiffrage reste conditionné à l’examen de l’ouvrage et au périmètre réellement retenu.' },
    budget: 'Un site de couvreur très visuel demande du tri, des légendes et une bonne optimisation des images. Le prix dépend également des prestations couvertes : zinguerie, réfection, entretien et fenêtres de toit ne racontent pas la même chose. Les contenus locaux, le suivi des demandes et la gestion Google Ads sont distingués pour que vous sachiez ce que finance votre accompagnement.',
    preparation: ['Des photographies autorisées avant, pendant et après chantier', 'Les matériaux et prestations proposés', 'Les assurances et qualifications vérifiables', 'Le secteur et le déroulement de votre visite'],
    journey: ['Recherche : réfection toiture ardoise Lorient', 'Page rénovation de couverture', 'Chantier similaire et présentation de l’entreprise', 'Demande de visite', 'Devis et relance organisés'],
    cases: ['br-z-couverture'], related: ['macon', 'renovation-interieure'],
    faq: [
      { question: 'Quel prix pour un site internet de couvreur ?', answer: 'Le Site Essentiel de Litus est affiché à 99 €/mois. Une galerie détaillée, plusieurs familles de travaux et une stratégie de référencement demandent un périmètre adapté. Nous vous indiquons la formule et les éventuels besoins spécifiques après examen des contenus.' },
      { question: 'Les photos de toiture prises au téléphone suffisent-elles ?', answer: 'Elles peuvent suffire si elles sont nettes et si vous avez le droit de les publier. Des vues avant, pendant et après sont utiles. Nous privilégions une sélection expliquée plutôt que des dizaines d’images presque identiques.' },
      { question: 'Faut-il mettre le démoussage et la réfection sur la même page ?', answer: 'Une présentation générale peut les réunir, mais ces besoins méritent généralement des pages distinctes. La personne qui cherche un entretien ne prépare pas le même budget ni la même visite qu’un propriétaire qui envisage une réfection.' },
      { question: 'Comment rassurer sans afficher de fausses garanties ?', answer: 'Avec votre identité, vos coordonnées, des chantiers réels, les justificatifs pertinents et une explication de votre méthode. Le site ne doit ni inventer de label ni laisser croire que toutes les situations sont couvertes par une garantie universelle.' },
      { question: 'Google Ads est-il utile pour une entreprise de couverture ?', answer: 'Il peut compléter le référencement sur des demandes clairement ciblées, à condition de pouvoir les traiter. Nous séparons les recherches urgentes des projets de rénovation et suivons la qualité des contacts, pas seulement les impressions.' },
      { question: 'Avez-vous déjà une réalisation liée à la couverture ?', answer: 'BR’Z Couverture figure dans le portfolio Litus pour un site vitrine et du référencement local. La fiche présente le périmètre documenté et un visuel d’archive ; aucun résultat chiffré supplémentaire n’est attribué à ce projet.' },
    ], cta: 'Donnons à vos chantiers la visibilité et la confiance qu’ils méritent.',
    sources: ['https://wecomm.fr/creation-site-web/couvreur/', 'https://www.trend-design.fr/post/site-internet-artisan-couvreur', 'https://notely.fr/metiers/couvreur/'],
  },
  {
    slug: 'menuisier', name: 'Menuisier', subject: 'un menuisier', style: 'visual',
    title: 'Création de site internet pour menuisier',
    description: 'Fenêtres, volets, agencement : valorisez vos ouvrages et qualifiez vos devis. Site de menuiserie, référencement local et cas Google Ads SARL Péan J.',
    intro: 'Remplacer des fenêtres ou faire fabriquer un dressing ne demande pas le même accompagnement. Votre site doit montrer vos ouvrages, vos matériaux et votre façon de travailler avant de demander un rendez-vous.',
    promise: 'Le sur-mesure se comprend mieux quand il se voit.',
    photoAlt: 'Établi et outillage dans un atelier de menuiserie', photoCredit: 'Photographie d’illustration · s w / wengenroad · CC0',
    problem: { title: 'Pose, fabrication, agencement : montrez ce qui fait votre atelier.', paragraphs: [
      'Certains visiteurs comparent des matériaux et des performances ; d’autres cherchent une pièce qui s’intègre dans un espace précis. Une page qui mélange fenêtres, escaliers et dressings sans organisation rend votre offre difficile à comprendre. Votre spécialité doit se voir dès les premières images.',
      'Le devis commence souvent avant la visite : nombre d’ouvertures, pièce concernée, rénovation ou neuf, contraintes d’accès. Nous vous aidons à recueillir ces éléments sans transformer votre site en configurateur complexe qui donnerait un faux prix définitif. Votre rôle de conseil reste central.',
    ] },
    priorities: [
      { title: 'Un portfolio par type d’ouvrage', text: 'Fenêtres, portes, volets ou agencements peuvent être parcourus séparément. Les légendes expliquent matériau, usage et contexte. On valorise vos réalisations réelles plutôt que de présenter des visuels fournisseurs comme vos propres chantiers.' },
      { title: 'Des matériaux bien expliqués', text: 'Bois, aluminium ou PVC sont présentés selon les solutions que vous proposez. Les marques et qualifications sont affichées avec l’autorisation et les justificatifs nécessaires, sans promettre la même réponse à chaque bâtiment.' },
      { title: 'Un premier contact plus utile', text: 'Le formulaire prépare le métré et le rendez-vous. Le client décrit son besoin ; vous conservez la maîtrise du conseil, des choix techniques et du chiffrage après examen du projet.' },
    ],
    pages: [
      { name: 'Menuiserie extérieure', purpose: 'Orienter les projets de remplacement ou de construction.' },
      { name: 'Fenêtres et baies', purpose: 'Montrer matériaux, ouvertures et intégrations réellement proposées.' },
      { name: 'Portes et volets', purpose: 'Séparer fermeture, protection et remplacement selon vos solutions.' },
      { name: 'Pergolas', purpose: 'Une page si vous installez ces équipements, avec exemples et étude du projet.' },
      { name: 'Agencement intérieur', purpose: 'Présenter dressings, rangements et meubles selon les espaces.' },
      { name: 'Atelier et fabrication', purpose: 'Distinguer vos ouvrages fabriqués de vos prestations de pose.' },
      { name: 'Réalisations par matériau', purpose: 'Permettre au client de retrouver des projets proches du sien.' },
      { name: 'Demander un métré', purpose: 'Recueillir localisation, type d’ouvrage et coordonnées de rappel.' },
    ],
    local: { title: 'Être trouvé sur un ouvrage précis, pas uniquement sur « menuisier ».', text: 'Les pages fenêtres, volets et agencement répondent à des recherches différentes. Nous travaillons les expressions qui décrivent vos ouvrages et votre secteur, avec des projets qui prouvent votre expérience. Le site complète votre fiche Google et les recommandations reçues hors ligne. Un atelier disposant d’un showroom peut expliquer la visite et la prise de rendez-vous, sans créer de fausses implantations pour gagner des villes.', queries: ['menuisier Le Mans', 'remplacement fenêtres Lorient', 'dressing sur mesure Morbihan', 'réparation volet roulant Sarthe'] },
    channels: { seo: 'Les réalisations classées et les pages par ouvrage enrichissent votre visibilité au fil du temps. Le contenu aide les clients à comparer votre manière de travailler, sans recopier les fiches commerciales des fabricants.', ads: 'Google Ads peut cibler une famille de demandes, par exemple des fenêtres ou des volets. Les campagnes orientent le visiteur vers une page correspondante. Nous distinguons la recherche de pose, la réparation et l’achat de matériel seul pour ne pas mélanger les contacts.', decision: 'Le cas SARL Péan J illustre une acquisition pilotée par Litus. Les chiffres présentés appartiennent à ce client, pas à tous les menuisiers : votre budget et vos objectifs se définissent selon vos marges, vos disponibilités et la qualité des demandes.' },
    qualification: { title: 'Du premier message au rendez-vous de métré.', fields: ['Fenêtres, volets ou agencement', 'Neuf ou remplacement', 'Quantité ou pièce concernée', 'Commune et calendrier envisagé'], text: 'Un dépôt de photographies ou de dimensions indicatives peut compléter le parcours selon le projet. Ces indications facilitent le premier échange mais ne remplacent pas un métré professionnel ni la validation des choix.' },
    budget: 'L’organisation de vos ouvrages et le nombre de galeries influencent le budget du site. Un artisan centré sur la pose de fenêtres n’a pas le même besoin éditorial qu’un atelier présentant aussi l’agencement intérieur. Nous séparons la réalisation web, l’alimentation des références, le référencement et le pilotage des campagnes pour éviter un devis opaque.',
    preparation: ['Vos familles d’ouvrages et matériaux', 'La distinction fabrication / pose / réparation', 'Vos photographies et droits sur les visuels de marques', 'Les informations utiles avant un métré'],
    journey: ['Recherche : remplacement volets Sarthe', 'Page volets et menuiserie extérieure', 'Ouvrages, matériaux et avis existants', 'Demande de métré', 'Devis qualifié puis suivi commercial'],
    cases: ['sarl-pean-j', 'menuiserie-jerome-rio'], related: ['renovation-interieure', 'paysagiste'],
    faq: [
      { question: 'Quel prix prévoir pour un site de menuiserie ?', answer: 'La page Tarifs Litus affiche Site Essentiel à 99 €/mois et des accompagnements plus complets. Le nombre de galeries, les contenus par ouvrage et les outils de prise de rendez-vous déterminent le périmètre retenu. Le budget des annonces reste distinct des honoraires de gestion.' },
      { question: 'Peut-on montrer à la fois la pose et la fabrication ?', answer: 'Oui, mais en les distinguant. Le client doit comprendre ce que vous concevez dans votre atelier, ce que vous fournissez et ce que vous posez. Cette distinction rend les réalisations et les demandes de devis plus pertinentes.' },
      { question: 'Litus a-t-il créé le site de SARL Péan J ?', answer: 'Non : le cas présenté ici concerne uniquement les campagnes Google Ads et l’acquisition pilotées par Litus. Le site de l’entreprise n’est pas une création attribuée à notre agence.' },
      { question: 'Quels résultats sont documentés pour SARL Péan J ?', answer: 'Les données communiquées par Litus font état de plus de 30 leads par mois et d’environ 15 € de coût par conversion. Le client augmente progressivement son budget parce que les campagnes lui apportent des demandes rentables. Ce cas ne constitue pas une garantie de résultats futurs.' },
      { question: 'Peut-on utiliser les photos des fabricants ?', answer: 'Seulement avec les droits adaptés et une attribution claire lorsque nécessaire. Nous distinguons ces visuels de vos réalisations de pose pour que le visiteur ne les confonde pas avec des chantiers exécutés par votre entreprise.' },
      { question: 'Comment éviter les demandes de prix trop vagues ?', answer: 'En demandant le type d’ouvrage, la quantité indicative, la commune et le contexte neuf ou rénovation. Les étapes de visite et de métré sont expliquées, plutôt que d’afficher un calcul qui ferait croire à un devis ferme sans étude.' },
    ], cta: 'Vos ouvrages font la différence. Rendons-la visible.',
    sources: ['https://www.beffroi.studio/artisans/menuisier', 'https://www.tempoagency.fr/site-internet-menuisier', 'https://artiads.fr/metiers/menuisier/'],
  },
  {
    slug: 'peintre', name: 'Peintre', subject: 'un peintre en bâtiment', style: 'visual',
    title: 'Création de site internet pour peintre en bâtiment',
    description: 'Un site de peintre qui montre vos finitions et prépare les devis : peinture intérieure, façade, décoration, portfolio et référencement local.',
    intro: 'Vos finitions, la préparation des supports et la propreté d’un chantier ne se résument pas à un prix au mètre carré. Nous les rendons visibles dans un site pensé pour les projets que vous souhaitez recevoir.',
    promise: 'Faites comparer votre travail, pas seulement votre prix.',
    photoAlt: 'Application de peinture blanche au rouleau sur un mur intérieur', photoCredit: 'Photographie d’illustration · Blue Bird / Pexels',
    problem: { title: 'Derrière une demande de peinture, il y a un logement et des contraintes.', paragraphs: [
      'Un appartement habité, une façade et des bureaux à remettre en état ne mobilisent pas la même organisation. Le client voit une couleur à changer ; vous voyez l’état du support, les protections, l’accès et les finitions. Le site sert à rendre cette différence compréhensible avant la comparaison des devis.',
      'Nous mettons en scène des projets documentés : vue d’ensemble, préparation et détails de finition. L’objectif n’est pas de remplir une galerie de nuanciers, mais de montrer votre travail et votre manière d’intervenir. Le devis reste lié à la visite et à la réalité du chantier.',
    ] },
    priorities: [
      { title: 'Des finitions visibles', text: 'Les angles, plafonds et raccords méritent des images nettes. Les avant/après utilisent des vues comparables et des légendes sobres. Une belle couleur seule ne raconte pas la préparation ni votre niveau de finition.' },
      { title: 'Des prestations bien séparées', text: 'Peinture intérieure, ravalement et revêtements décoratifs répondent à des besoins différents. Le visiteur doit identifier rapidement les travaux que vous faites et les bâtiments sur lesquels vous intervenez.' },
      { title: 'Un chantier compris avant la visite', text: 'Le site précise votre organisation, la protection des lieux et les étapes du projet. Un formulaire peut recueillir pièces, occupation et échéance, sans demander au client de mesurer toutes les surfaces avec exactitude.' },
    ],
    pages: [
      { name: 'Peinture intérieure', purpose: 'Présenter murs, plafonds et supports pris en charge.' },
      { name: 'Façades et ravalement', purpose: 'Décrire votre périmètre extérieur et les étapes avant devis.' },
      { name: 'Préparation des supports', purpose: 'Expliquer ce qui se passe avant la mise en peinture.' },
      { name: 'Papier peint et revêtements', purpose: 'Montrer les prestations décoratives effectivement proposées.' },
      { name: 'Locaux professionnels', purpose: 'Présenter votre organisation lorsque les lieux restent en activité.' },
      { name: 'Réalisations avant/après', purpose: 'Associer pièces, supports et finitions à des photos autorisées.' },
      { name: 'Méthode et protection des lieux', purpose: 'Rassurer sur le chantier au-delà de la couleur choisie.' },
      { name: 'Visite et devis peinture', purpose: 'Préparer le rendez-vous avec pièces, commune et calendrier.' },
    ],
    local: { title: 'Peinture intérieure et façade : deux recherches, deux réponses.', text: 'Le référencement d’un peintre s’appuie sur ses prestations et ses réalisations locales. Nous séparons par exemple la remise en peinture d’un appartement et le ravalement, pour que la page réponde au besoin réel. Les avis décrivant le soin, la ponctualité ou l’organisation sont utiles lorsqu’ils existent et sont correctement attribués. Les zones desservies restent cohérentes avec vos déplacements, pas avec une liste arbitraire de villes.', queries: ['peintre en bâtiment Lorient', 'devis peinture appartement Le Mans', 'ravalement façade Sarthe', 'artisan pose papier peint'] },
    channels: { seo: 'Une galerie commentée et des pages sur vos finitions aident les clients à se projeter. Des réponses sur la préparation et le déroulement de la visite enrichissent le site sans remplacer vos conseils de terrain.', ads: 'Les annonces peuvent mettre l’accent sur la peinture de logements, les façades ou les locaux professionnels selon le planning. Nous distinguons les demandes de prestation des recherches de produits, de loisirs créatifs ou d’artiste peintre.', decision: 'Le suivi doit tenir compte de la nature du chantier. Remplir le formulaire n’est qu’une étape : on regarde si la visite a lieu et si le devis correspond aux projets que votre équipe veut réaliser.' },
    qualification: { title: 'Un premier message qui ne se limite pas à « combien le m² ? ».', fields: ['Intérieur, façade ou local professionnel', 'Pièces et surfaces indicatives', 'Lieux occupés ou libres', 'Commune et période de travaux'], text: 'La demande explique le contexte sans donner de prix artificiel. Les supports, leur état et les finitions souhaitées sont confirmés lors de la visite. Le client comprend pourquoi deux logements de même surface peuvent demander des travaux différents.' },
    budget: 'Le volume de photographies à trier et la variété des finitions influencent le coût de création. Un site centré sur la peinture intérieure peut démarrer simplement ; une entreprise qui souhaite aussi développer le ravalement et les chantiers professionnels a besoin de contenus distincts. Le devis web précise les pages, la rédaction, les images et l’accompagnement après mise en ligne.',
    preparation: ['Vos types de supports et finitions', 'Des avant/après autorisés et bien éclairés', 'Votre organisation en logement occupé', 'Les chantiers que vous souhaitez développer'],
    journey: ['Recherche : devis peinture appartement Le Mans', 'Page peinture intérieure', 'Photos de finitions et méthode de chantier', 'Description des pièces et de l’occupation', 'Visite puis devis détaillé'],
    cases: [], related: ['renovation-interieure', 'carreleur'],
    faq: [
      { question: 'Combien coûte un site internet pour peintre ?', answer: 'Litus affiche une offre Site Essentiel à 99 €/mois. Le devis adapté dépend de vos galeries, de vos prestations et de l’accompagnement souhaité. Une stratégie façade et locaux professionnels demande un contenu différent d’une vitrine centrée sur la peinture intérieure.' },
      { question: 'Faut-il afficher un prix de peinture au mètre carré ?', answer: 'C’est à vous de décider quels repères vous pouvez publier. Ils doivent préciser les conditions et ne pas remplacer l’étude des supports. Nous n’inventons aucun tarif de chantier ni simulateur qui ferait croire à un devis confirmé.' },
      { question: 'Comment photographier mes finitions pour le site ?', answer: 'Privilégiez une vue générale et quelques détails nets, avec l’accord du client. Pour un avant/après, gardez un angle comparable. Évitez d’inclure des informations privées ou de retoucher un défaut au point de tromper sur le travail réalisé.' },
      { question: 'Mon bouche-à-oreille fonctionne : pourquoi un site ?', answer: 'Une personne recommandée peut vouloir voir votre travail avant de vous contacter. Le site confirme votre spécialité, votre secteur et votre organisation ; il complète la recommandation plutôt que de prétendre la remplacer.' },
      { question: 'Comment éviter les contacts qui cherchent un artiste peintre ?', answer: 'En employant clairement « peintre en bâtiment », avec des pages de prestations et des exemples de rénovation. En publicité, les termes de recherche sont suivis et les intentions artistiques non pertinentes peuvent être exclues.' },
      { question: 'Puis-je montrer le ravalement et la décoration intérieure ensemble ?', answer: 'Oui, sous la même identité, avec deux univers distincts. Les images, les questions du formulaire et le déroulement présenté doivent correspondre à chaque chantier plutôt que de reprendre le même argumentaire.' },
    ], cta: 'Mettons en lumière le soin que vous apportez à chaque finition.',
    sources: ['https://www.groupe10x.com/creation-site-internet-peintre', 'https://lesiteartisan.fr/articles/site-internet-peintre-batiment', 'https://www.alizee-web.com/creation-site-internet-peintre'],
  },
  {
    slug: 'carreleur', name: 'Carreleur', subject: 'un carreleur', style: 'visual',
    title: 'Création de site internet pour carreleur',
    description: 'Carrelage, faïence, terrasse et salle de bain : un site de carreleur qui montre vos poses, prépare les devis et travaille votre visibilité locale.',
    intro: 'Le choix d’un carreleur se joue dans les détails : coupes, alignements, joints et intégration des matériaux. Votre site doit montrer votre précision et aider le client à préparer son projet, au-delà du seul prix de pose.',
    promise: 'Les détails de vos poses deviennent des arguments.',
    photoAlt: 'Artisan posant du carrelage pendant une rénovation intérieure', photoCredit: 'Photographie d’illustration · Sergei Starostin / Pexels',
    problem: { title: 'Une surface en m² ne décrit pas tout le chantier.', paragraphs: [
      'Le format du carreau, le support, les découpes et l’usage de la pièce changent le travail à prévoir. Un client qui compare uniquement un prix de pose ne dispose pas de ces repères. Votre site peut expliquer le processus et montrer ce qui distingue une réalisation soignée.',
      'Nous séparons sols, faïence et extérieur pour que chacun retrouve un projet comparable. La demande de devis identifie aussi la fourniture : carreaux déjà achetés ou choix à accompagner. Cela vous aide à préparer le rendez-vous sans transformer quelques réponses en chiffrage définitif.',
    ] },
    priorities: [
      { title: 'Des gros plans qui comptent', text: 'Une vue de la pièce donne le contexte ; une photo de détail montre les raccords et les coupes. Les légendes précisent le type de pose et le matériau sans attribuer au carreleur la totalité d’une rénovation.' },
      { title: 'Des projets classés par usage', text: 'La salle de bain, la terrasse et la pièce de vie méritent des entrées distinctes. Vos visiteurs repèrent rapidement les travaux que vous proposez, y compris la préparation des supports si elle fait partie du chantier.' },
      { title: 'Un devis mieux contextualisé', text: 'Surface indicative, intérieur ou extérieur, carreaux fournis ou non : quelques choix simples préparent le premier échange. Les décisions techniques et l’état réel du support sont ensuite examinés avec vous.' },
    ],
    pages: [
      { name: 'Pose de carrelage intérieur', purpose: 'Présenter les pièces, formats et finitions proposés.' },
      { name: 'Faïence murale', purpose: 'Montrer découpes, niches et raccords dans leur contexte.' },
      { name: 'Salle de bain et douche', purpose: 'Préciser votre périmètre et la coordination avec les autres corps de métier.' },
      { name: 'Terrasses et extérieur', purpose: 'Présenter des projets adaptés à cet usage, sans diagnostic à distance.' },
      { name: 'Préparation des supports', purpose: 'Expliquer l’examen préalable et les travaux que vous prenez en charge.' },
      { name: 'Formats et matériaux', purpose: 'Montrer grès cérame, grands formats ou autres spécialités réelles.' },
      { name: 'Galerie de poses', purpose: 'Organiser vues générales et détails par type de réalisation.' },
      { name: 'Demande de devis', purpose: 'Distinguer fourniture, pose, surface et état de l’existant à examiner.' },
    ],
    local: { title: 'Faire correspondre la recherche à une pièce et à une pose.', text: 'Les clients recherchent souvent un carreleur avec un projet déjà en tête : une terrasse, une faïence ou une salle de bain. Nous relions ces intentions à des pages précises et à votre secteur. Des réalisations légendées donnent de la substance à la visibilité locale. La fiche Google, les avis existants et les coordonnées du site restent cohérents, sans inventer un showroom ou des agences dans chaque commune.', queries: ['carreleur Lorient', 'pose faïence salle de bain Le Mans', 'devis carrelage terrasse', 'pose grand format Morbihan'] },
    channels: { seo: 'Des pages qui détaillent vos poses et une galerie bien organisée constituent une base utile pour le référencement. Il s’agit de répondre aux questions du projet, pas de publier un catalogue de matériaux que vous ne posez pas.', ads: 'La publicité peut cibler les demandes de pose dans votre zone. Les recherches d’achat de carrelage seul, de tutoriels et de matériel sont à distinguer. Une campagne terrasse ne doit pas aboutir à une page qui ne montre que des salles de bain.', decision: 'Nous suivons les demandes correspondant à vos compétences et à votre calendrier. La présence de mètres carrés dans un formulaire ne rend pas automatiquement un prospect pertinent : le type de pose et les contraintes restent déterminants.' },
    qualification: { title: 'Savoir ce qu’il faut poser, avant de parler de prix.', fields: ['Sol, mur, douche ou terrasse', 'Surface et format indicatifs', 'Carreaux fournis ou à choisir', 'Commune et état de l’existant'], text: 'Un formulaire progressif peut demander les informations propres à une terrasse ou à une salle de bain. Il prépare le rendez-vous ; il ne valide ni la préparation nécessaire ni les contraintes techniques sans examen sur place.' },
    budget: 'Le site demande surtout une sélection d’images détaillées et une organisation par type de pose. Une galerie filtrable, des vues comparatives ou un formulaire à choix conditionnels ajoutent du travail au-delà d’une vitrine simple. Nous chiffrons ce périmètre, les contenus et le suivi local à partir des offres Litus plutôt qu’un tarif inventé pour votre métier.',
    preparation: ['Les types de poses et matériaux maîtrisés', 'Des photos nettes de vues générales et de finitions', 'Votre pratique de la fourniture et de la pose', 'Les questions qui préparent réellement votre visite'],
    journey: ['Recherche : pose faïence salle de bain Le Mans', 'Page faïence et salle de bain', 'Détails de poses et périmètre d’intervention', 'Surface et fourniture précisées', 'Visite pour établir le devis'],
    cases: [], related: ['renovation-interieure', 'peintre', 'plombier'],
    faq: [
      { question: 'Quel budget pour un site internet de carreleur ?', answer: 'Site Essentiel est affiché à 99 €/mois chez Litus. Le tarif de votre projet dépend ensuite du nombre de galeries, des pages de pose et des fonctionnalités nécessaires. Les offres publiques permettent de situer le budget, puis le devis fixe le périmètre.' },
      { question: 'Faut-il une boutique en ligne pour montrer les carrelages ?', answer: 'Non, une galerie ou une présentation des matériaux peut suffire. Un e-commerce n’a de sens que si vous vendez réellement en ligne et pouvez assurer le parcours commercial associé. Montrer votre savoir-faire n’exige pas un panier d’achat.' },
      { question: 'Peut-on séparer fourniture et pose dans le formulaire ?', answer: 'Oui. Cette information aide à comprendre si le client a déjà choisi ou acheté ses carreaux. Elle peut être complétée par le format et la surface indicative, sans prétendre produire un devis final automatiquement.' },
      { question: 'Comment mettre en valeur les joints et les coupes ?', answer: 'Avec des images détaillées et nettes, accompagnées d’une vue générale de la pièce. Le site doit charger rapidement malgré les photos : dimensions adaptées et compression évitent de sacrifier la lisibilité sur mobile.' },
      { question: 'Comment trouver des chantiers sans dépendre uniquement de plateformes ?', answer: 'Le site, la fiche Google et les recommandations de partenaires constituent des canaux directs à travailler ensemble. Les pages précises et les réalisations permettent au client de comprendre votre offre avant de vous demander un devis.' },
      { question: 'Puis-je promouvoir les terrasses séparément des salles de bain ?', answer: 'Oui. Les deux intentions peuvent avoir leurs pages et leurs campagnes, avec des photographies et des questions adaptées. Le budget de publicité suit votre disponibilité et la qualité des demandes reçues.' },
    ], cta: 'Montrons ce que vos finitions changent dans un projet.',
    sources: ['https://julienchretien.com/site-internet-carreleur', 'https://webartiz.fr/creation-site-internet-carreleur/', 'https://costructor.co/blog/trouver-chantier-carrelage/'],
  },
  {
    slug: 'macon', name: 'Maçon', subject: 'une entreprise de maçonnerie', style: 'technical',
    title: 'Création de site internet pour maçon',
    description: 'Gros œuvre, extension et rénovation : un site de maçonnerie qui présente vos chantiers, rassure les propriétaires et prépare des devis qualifiés.',
    intro: 'Une extension, une ouverture ou une rénovation ne se confie pas à partir d’un slogan. Nous construisons un site qui explique votre périmètre, montre les étapes de vos chantiers et prépare un premier échange sérieux.',
    promise: 'Des projets solides commencent par des informations claires.',
    photoAlt: 'Maçons travaillant à la construction d’un mur en briques', photoCredit: 'Photographie d’illustration · Pexels',
    problem: { title: 'Le propriétaire cherche une équipe fiable pour un projet qu’il maîtrise mal.', paragraphs: [
      'Le gros œuvre engage plusieurs étapes et souvent plusieurs interlocuteurs. Le client veut savoir quels travaux vous réalisez, comment le projet est étudié et qui coordonne la suite. Un site trop général laisse ces questions sans réponse et peut attirer des demandes hors de votre spécialité.',
      'Nous faisons apparaître votre rôle : maçonnerie générale, extension, rénovation ou ouvrages extérieurs. Les travaux structurels sont présentés comme des projets à étudier, sans publier une solution technique universelle. Les références montrent le contexte et le périmètre réellement exécuté par votre entreprise.',
    ] },
    priorities: [
      { title: 'Un périmètre précis', text: 'Neuf, rénovation, pierre ou béton : vos spécialités sont présentées distinctement. Le visiteur comprend les travaux que vous prenez en charge et ceux qui nécessitent d’autres intervenants avant de vous contacter.' },
      { title: 'Des chantiers racontés par étapes', text: 'Des photos de préparation, d’ouvrage et de résultat apportent davantage qu’une maison terminée sans explication. On précise votre intervention sans vous attribuer les travaux des autres corps de métier.' },
      { title: 'Un dossier exploitable', text: 'Le formulaire identifie l’avancement du projet, le type de bâtiment et la commune. Il peut prévoir des plans à partager après le premier échange, tout en conservant un accès simple depuis un téléphone.' },
    ],
    pages: [
      { name: 'Maçonnerie générale', purpose: 'Présenter vos ouvrages et le type de clientèle accompagnée.' },
      { name: 'Extension et agrandissement', purpose: 'Expliquer votre rôle dans les étapes et la coordination du projet.' },
      { name: 'Rénovation de bâti', purpose: 'Montrer des interventions sur des constructions existantes.' },
      { name: 'Ouvertures et reprises', purpose: 'Indiquer que les travaux sont étudiés avec les professionnels nécessaires.' },
      { name: 'Dalles et ouvrages béton', purpose: 'Décrire les prestations effectuées sans solution technique standardisée.' },
      { name: 'Murs et ouvrages extérieurs', purpose: 'Présenter les chantiers correspondant à votre spécialité réelle.' },
      { name: 'Chantiers documentés', purpose: 'Associer les photographies au périmètre et aux étapes de votre travail.' },
      { name: 'Étude et devis maçonnerie', purpose: 'Recueillir le projet, son avancement et les coordonnées du demandeur.' },
    ],
    local: { title: '« Maçon » désigne un métier : votre site doit lever toute ambiguïté.', text: 'Les recherches peuvent confondre le métier et la ville de Mâcon. Nous employons naturellement « entreprise de maçonnerie », vos ouvrages et votre zone réelle pour décrire clairement l’activité. Les références locales et les pages extension ou rénovation donnent du contexte. La fiche Google doit correspondre à votre entreprise et non à des adresses artificielles créées pour couvrir davantage de communes.', queries: ['entreprise de maçonnerie Le Mans', 'maçon rénovation pierre Morbihan', 'devis extension maison Sarthe', 'maçon pour ouverture de mur Lorient'] },
    channels: { seo: 'Les contenus sur les types de chantiers et leur préparation répondent à des recherches qui mûrissent parfois longtemps. Des études de cas explicites renforcent la crédibilité du site sans promettre une solution structurelle à partir d’une photo.', ads: 'Les annonces peuvent cibler les projets correspondant à votre équipe : extension, rénovation ou ouvrages définis. Nous distinguons la recherche d’un artisan des recherches de formation, d’emploi et de matériaux. Le formulaire prépare une demande d’étude, pas un achat instantané.', decision: 'Une acquisition pertinente tient compte du montant potentiel, mais aussi du calendrier et de votre capacité de production. On suit la progression vers un échange qualifié et un devis, sans traiter tous les formulaires comme des contrats.' },
    qualification: { title: 'Comprendre l’avancement du projet avant de programmer une visite.', fields: ['Extension, rénovation ou ouvrage précis', 'Commune et type de bâtiment', 'Projet au stade idée, plans ou consultation', 'Interlocuteurs déjà impliqués et calendrier'], text: 'Les documents techniques peuvent être transmis dans un échange sécurisé après qualification. Le site ne valide ni la faisabilité structurelle ni les démarches nécessaires : il permet de préparer la discussion avec les bons professionnels.' },
    budget: 'Le budget du site varie avec les domaines de travaux et la documentation disponible. Raconter une extension et présenter de petits ouvrages demandent des contenus différents. Une galerie par étapes, un dépôt de plans ou un suivi commercial connecté sont des postes à cadrer. Les offres Litus servent de repère, puis le devis précise ce qui est réellement prévu.',
    preparation: ['Vos ouvrages et spécialités prioritaires', 'Des chantiers documentés par étapes', 'Votre rôle par rapport aux autres intervenants', 'Les informations requises avant une étude'],
    journey: ['Recherche : entreprise maçonnerie extension Le Mans', 'Page extension de maison', 'Chantier comparable et rôle de l’entreprise', 'Description de l’avancement du projet', 'Échange puis étude et devis'],
    cases: [], related: ['couvreur', 'renovation-interieure'],
    faq: [
      { question: 'Combien coûte le site d’une entreprise de maçonnerie ?', answer: 'Litus publie Site Essentiel à 99 €/mois et plusieurs niveaux d’accompagnement. La documentation des chantiers, le nombre de pages par spécialité et les fonctionnalités de demande d’étude déterminent le périmètre à chiffrer.' },
      { question: 'Quelles photos de maçonnerie faut-il montrer ?', answer: 'Des vues qui expliquent le contexte et les étapes, en précisant ce que vous avez réalisé. Une maison finie seule peut masquer votre intervention. Nous distinguons vos ouvrages des travaux réalisés par les autres entreprises.' },
      { question: 'Faut-il proposer un devis immédiat pour une extension ?', answer: 'Pas si les informations ne permettent pas un chiffrage sérieux. Un parcours de demande d’étude est plus adapté : bâtiment, commune, stade du projet et documents disponibles préparent le contact sans annoncer un montant définitif.' },
      { question: 'Comment éviter la confusion entre maçon et Mâcon sur Google ?', answer: 'En décrivant clairement le métier : entreprise de maçonnerie, extension, gros œuvre et zone d’intervention. Le contenu doit rester naturel et ne pas se réduire à l’orthographe d’un seul mot-clé.' },
      { question: 'Peut-on recevoir des plans depuis le site ?', answer: 'Oui si ce besoin est prévu au devis, avec des limites de taille et des protections adaptées. Il est aussi possible de demander les documents après un premier échange afin de ne pas alourdir le formulaire initial.' },
      { question: 'Le référencement peut-il remplacer les partenaires du bâtiment ?', answer: 'Il les complète. Architectes, entreprises partenaires et recommandations restent des sources de contacts importantes. Le site permet aussi à ces interlocuteurs de retrouver vos spécialités et des références documentées.' },
    ], cta: 'Construisons une présence web aussi claire que votre périmètre de chantier.',
    sources: ['https://iliadedigital.fr/site-internet-macon/', 'https://webartiz.fr/creation-site-internet-macon/', 'https://www.fpstudio.fr/creation-site-internet-macon/'],
  },
  {
    slug: 'paysagiste', name: 'Paysagiste', subject: 'un paysagiste', style: 'visual',
    title: 'Création de site internet pour paysagiste',
    description: 'Valorisez jardins, terrasses et clôtures avec un portfolio paysagiste, des devis préparés et du SEO local. Découvrez le cas client West Clôtures.',
    intro: 'Un jardin se choisit avec les yeux, mais un projet se prépare avec des informations concrètes. Votre site doit montrer vos aménagements et distinguer création, entretien, terrasses et clôtures dès le premier écran.',
    promise: 'Donnez envie de transformer un extérieur. Facilitez le premier échange.',
    photoAlt: 'Terrasse éclairée et jardin paysager issus de l’univers du site West Clôtures', photoCredit: 'Univers visuel du site client West Clôtures & Paysage',
    problem: { title: 'Votre galerie peut donner envie sans expliquer ce que vous proposez.', paragraphs: [
      'Une belle photographie attire l’attention, mais le visiteur doit aussi savoir si vous créez des jardins, entretenez des espaces existants ou posez des clôtures. Ces demandes n’ont pas le même calendrier, le même périmètre ni la même organisation. Un portfolio sans chemin de contact laisse le projet en suspens.',
      'Nous construisons des pages où l’image explique un usage : une terrasse pour recevoir, une clôture pour délimiter, un jardin à réaménager. Le formulaire recueille le type de terrain et le besoin pour préparer une visite, sans prétendre chiffrer un extérieur à partir de sa seule surface.',
    ] },
    priorities: [
      { title: 'Un portfolio véritablement paysager', text: 'Vues d’ensemble, détails et avant/après racontent la transformation. Les projets sont classés selon vos prestations pour que le client trouve un extérieur comparable au sien sans parcourir une suite d’images sans légende.' },
      { title: 'Création et entretien séparés', text: 'Une demande de passage régulier n’est pas un projet d’aménagement complet. Les deux offres doivent avoir leur page et leurs questions, avec un secteur et des disponibilités cohérents avec votre équipe.' },
      { title: 'Une visite mieux préparée', text: 'Surface indicative, accès, usage souhaité et commune permettent un premier échange concret. Le client peut partager ses envies ; les contraintes du terrain et les choix techniques restent à examiner sur place.' },
    ],
    pages: [
      { name: 'Création de jardin', purpose: 'Présenter vos étapes de conception et de réalisation.' },
      { name: 'Entretien des espaces verts', purpose: 'Distinguer interventions ponctuelles et suivi régulier proposé.' },
      { name: 'Terrasses et circulations', purpose: 'Montrer les matériaux, les usages et les réalisations.' },
      { name: 'Clôtures et portails', purpose: 'Séparer délimitation, pose et aménagement environnant.' },
      { name: 'Plantations et engazonnement', purpose: 'Expliquer les prestations que vous réalisez dans votre secteur.' },
      { name: 'Aménagements avant/après', purpose: 'Faire découvrir un projet du besoin initial au résultat.' },
      { name: 'Équipe et zone d’intervention', purpose: 'Présenter votre organisation et vos déplacements réels.' },
      { name: 'Visite de terrain', purpose: 'Qualifier le projet extérieur avant un devis.' },
    ],
    local: { title: 'Un jardin proche de chez vous est une preuve plus forte qu’une page de ville vide.', text: 'Les projets documentés apportent du contexte au référencement : nature du terrain, prestation et secteur général, avec l’accord des clients. Nous relions les recherches aux pages création, entretien ou clôture plutôt qu’à une seule galerie. Votre fiche Google et les avis existants complètent la présentation ; la visibilité doit rester compatible avec votre rayon de déplacement et vos périodes d’intervention.', queries: ['paysagiste Lorient', 'création jardin Morbihan', 'pose clôture Le Mans', 'devis terrasse et aménagement extérieur'] },
    channels: { seo: 'Le référencement associe pages de prestations et projets illustrés. Des images optimisées et bien décrites permettent de montrer votre univers sans pénaliser le chargement mobile. L’entretien et la création sont traités comme des intentions distinctes.', ads: 'Les campagnes peuvent privilégier les devis d’aménagement, de terrasse ou de clôture quand ils correspondent à votre planning. Nous évitons de confondre achat de plantes, tutoriels de jardinage et recherche d’un professionnel pour un chantier.', decision: 'Le bon indicateur est une visite ou une demande de projet exploitable. Les périodes de diffusion et le périmètre sont ajustés selon vos disponibilités, plutôt que de rechercher du volume pendant une saison déjà complète.' },
    qualification: { title: 'Du jardin imaginé au projet que vous pouvez étudier.', fields: ['Création, entretien, terrasse ou clôture', 'Surface indicative et accès au terrain', 'Commune du projet', 'Usages souhaités et calendrier'], text: 'La demande peut être enrichie par des photos de l’existant. Elles servent au premier échange et ne remplacent pas l’examen des accès, du terrain et des contraintes du projet. Les devis restent à votre main.' },
    budget: 'Le choix et le traitement des photographies comptent particulièrement pour un site de paysagiste. Galeries par prestation, récits avant/après, formulaire de projet et pages locales constituent des postes distincts. Nous vous proposons un périmètre lié à vos activités réelles, avec un budget séparé pour les campagnes et leur diffusion.',
    preparation: ['Une sélection de jardins, terrasses et clôtures autorisée', 'La distinction entre création et entretien', 'Votre rayon et vos périodes de disponibilité', 'Les informations utiles avant une visite de terrain'],
    journey: ['Recherche : aménagement jardin Lorient', 'Page création de jardin', 'Projet extérieur comparable et méthode', 'Description du terrain et des usages', 'Visite puis proposition d’aménagement'],
    cases: ['west-clotures-paysage', 'le-bolay-paysagiste'], related: ['menuisier', 'macon'],
    faq: [
      { question: 'Combien coûte un site internet pour paysagiste ?', answer: 'Le Site Essentiel Litus est affiché à 99 €/mois. Pour un portfolio très visuel et plusieurs prestations, le devis précise les galeries, les textes et le suivi. Le prix n’est pas déduit du nombre de photos uniquement : leur organisation et le parcours de contact comptent aussi.' },
      { question: 'Mes photos de jardin au téléphone sont-elles utilisables ?', answer: 'Oui si elles sont nettes et autorisées. Une sélection cohérente avec des vues d’ensemble et des détails est préférable à une galerie très lourde. Nous distinguons les photos de vos chantiers des illustrations éventuelles.' },
      { question: 'Comment différencier entretien et création de jardin ?', answer: 'Avec des pages et des demandes distinctes. Pour l’entretien, on précise le besoin et la récurrence ; pour la création, le terrain, les usages et le calendrier. Cela évite de qualifier de la même façon un passage ponctuel et un aménagement complet.' },
      { question: 'Quel projet paysagiste avez-vous déjà accompagné ?', answer: 'West Clôtures & Paysage figure dans nos réalisations pour la refonte du site, le référencement local, les campagnes Google Ads et un outil de suivi métier. Le Bolay Paysagiste est également documenté dans le portfolio historique.' },
      { question: 'Peut-on lancer Google Ads uniquement sur les clôtures ?', answer: 'Oui, avec des recherches, une zone et une page dédiées à cette prestation. Il est préférable de définir les types de projets souhaités et les créneaux disponibles avant de fixer les dépenses publicitaires.' },
      { question: 'Faut-il publier un avant/après pour chaque jardin ?', answer: 'Seulement si les images existent et représentent le même projet. Une réalisation complète bien légendée fonctionne aussi. Nous ne fabriquons pas un avant/après en assemblant deux jardins sans rapport.' },
    ], cta: 'Votre prochain beau projet peut commencer par une recherche toute simple.',
    sources: ['https://start.wpmarmite.com/creer-site/artisan/paysagiste/', 'https://nolira-agency.com/site-internet-paysagiste/', 'https://www.laxo.fr/google-ads/paysagiste'],
  },
  {
    slug: 'renovation-interieure', name: 'Rénovation intérieure', subject: 'une entreprise de rénovation intérieure', style: 'visual',
    title: 'Création de site internet pour entreprise de rénovation intérieure',
    description: 'Rénovation complète, cuisine et salle de bain : un site qui explique votre coordination, montre les transformations et qualifie les projets. Cas Nos Travaux.',
    intro: 'Vos clients cherchent une transformation, mais aussi quelqu’un pour organiser les travaux. Nous présentons votre rôle, vos réalisations et les étapes d’un projet dans un site qui prépare des demandes vraiment exploitables.',
    promise: 'Montrer le résultat. Expliquer comment on y arrive.',
    photoAlt: 'Cuisine lumineuse en cours de rénovation avec matériaux et outils de chantier', photoCredit: 'Photographie d’illustration · Brett Jordan / Pexels',
    problem: { title: 'Le premier besoin est souvent de savoir par où commencer.', paragraphs: [
      'Un propriétaire peut avoir une idée précise de sa future cuisine mais aucune visibilité sur les étapes, les intervenants ou l’organisation pendant les travaux. Un autre veut rénover avant une mise en location. Une simple galerie de belles pièces ne répond pas à ces préoccupations.',
      'Nous expliquons votre périmètre réel : travaux exécutés, coordination, accompagnement et éventuels partenaires. Les projets sont racontés avec leur contexte, pas comme des transformations anonymes. Le site aide le client à décrire son logement et son calendrier sans faire croire qu’une surface suffit à fixer un prix.',
    ] },
    priorities: [
      { title: 'Des transformations racontées', text: 'Avant, étapes et résultat montrent ce qui a changé dans le logement. Les textes précisent les pièces et les interventions prises en charge. Une photographie de décoration n’est pas présentée comme une rénovation réalisée par votre équipe.' },
      { title: 'Un rôle clairement défini', text: 'Vous intervenez sur certains lots ou coordonnez un ensemble ? Nous le formulons explicitement. Le visiteur sait quel interlocuteur il peut contacter et comment se déroule l’étude avant les travaux.' },
      { title: 'Des demandes mieux cadrées', text: 'Type de logement, pièces, occupation, commune et échéance structurent le premier échange. Un projet encore au stade des idées n’est pas traité comme un chantier dont le dossier est déjà prêt.' },
    ],
    pages: [
      { name: 'Rénovation complète', purpose: 'Présenter votre périmètre, votre coordination et les étapes du projet.' },
      { name: 'Rénovation de cuisine', purpose: 'Montrer agencement, usages et travaux réellement pris en charge.' },
      { name: 'Rénovation de salle de bain', purpose: 'Expliquer les intervenants et le déroulement de l’étude.' },
      { name: 'Appartement et logement occupé', purpose: 'Rassurer sur l’organisation et les contraintes à anticiper.' },
      { name: 'Cloisons, sols et finitions', purpose: 'Détailler les lots proposés sans laisser croire à des compétences non exercées.' },
      { name: 'Projets avant/après', purpose: 'Associer transformation, contexte et rôle exact de votre entreprise.' },
      { name: 'Notre organisation', purpose: 'Identifier le contact, les validations et les étapes de suivi.' },
      { name: 'Préparer mon projet', purpose: 'Recueillir les pièces, le calendrier et l’avancement avant rendez-vous.' },
    ],
    local: { title: 'Répondre à une pièce, à un logement et à une zone d’intervention.', text: 'La rénovation recouvre des intentions très différentes. Les pages cuisine, salle de bain et rénovation complète doivent apporter leurs propres exemples et explications. Nous travaillons votre visibilité à partir des projets et des communes réellement servis, avec une fiche Google cohérente. La confiance se construit aussi dans les réponses sur l’organisation du chantier, pas seulement dans l’affichage d’une ville.', queries: ['entreprise rénovation intérieure Le Mans', 'rénovation cuisine Lorient', 'devis rénovation appartement Sarthe', 'rénovation salle de bain Morbihan'] },
    channels: { seo: 'Le site accompagne une réflexion parfois longue. Les réalisations, les explications par pièce et les étapes du projet aident à préparer un premier échange. Nous évitons les pages de travaux quasi identiques qui ne font que changer une commune.', ads: 'Les campagnes peuvent viser une demande de rénovation complète ou un lot précis. Une page d’arrivée cohérente aide à recueillir un projet et son état d’avancement. Les recherches de tutoriels, d’emploi ou de décoration seule sont distinguées des demandes de travaux.', decision: 'Les contacts doivent être rapprochés des visites, des propositions et des projets réellement engagés. Un volume élevé de formulaires peu documentés peut masquer une acquisition mal ciblée : la qualification compte autant que le coût.' },
    qualification: { title: 'Une première trame de projet, pas un formulaire interminable.', fields: ['Logement, commune et pièces concernées', 'Travaux envisagés et état de l’existant', 'Logement occupé ou libre', 'Calendrier et niveau de préparation'], text: 'Le parcours peut évoluer selon la pièce et le type de rénovation. Les documents et photos complètent ensuite l’échange. Un budget indicatif peut aider à cadrer les priorités, mais n’est pas transformé automatiquement en prix de travaux.' },
    budget: 'Un site de rénovation peut demander plusieurs parcours par pièce, des études de cas riches et une qualification progressive des demandes. Le travail de rédaction doit aussi clarifier votre rôle parmi les intervenants. Nous définissons le périmètre à partir de vos activités et de vos documents, puis distinguons site, contenus, suivi et acquisition dans la proposition.',
    preparation: ['Vos lots et votre rôle de coordination', 'Des projets documentés avec droits de publication', 'Le déroulement de l’étude et des validations', 'Les questions qui permettent de préparer une visite'],
    journey: ['Recherche : rénovation cuisine Le Mans', 'Page rénovation de cuisine', 'Transformation documentée et organisation', 'Description du logement et du calendrier', 'Échange de cadrage puis visite'],
    cases: ['nos-travaux'], related: ['peintre', 'carreleur', 'menuisier', 'plombier'],
    faq: [
      { question: 'Quel prix pour le site d’une entreprise de rénovation ?', answer: 'La page Tarifs Litus présente Site Essentiel à 99 €/mois et les offres de suivi. Une architecture par pièce, des études de cas et un formulaire progressif demandent un cadrage spécifique. Nous ne présentons pas le prix de départ comme celui de toutes les fonctionnalités.' },
      { question: 'Peut-on montrer plusieurs corps de métier sur le site ?', answer: 'Oui, en précisant les travaux exécutés par votre entreprise, ceux coordonnés et les éventuels partenaires. Le site ne doit pas laisser croire que vous réalisez un lot qui sort de votre périmètre.' },
      { question: 'Comment présenter les avant/après d’un logement ?', answer: 'Avec des images du même projet, les droits nécessaires et une description de la transformation. Les vues comparables facilitent la lecture, mais les contraintes et les étapes apportent aussi de la crédibilité à la réalisation.' },
      { question: 'Avez-vous déjà créé un site pour la rénovation ?', answer: 'Oui, Nos Travaux est un projet Litus de création de site pour une entreprise de rénovation au Mans. La réalisation est accessible dans le portfolio avec les captures du site et le périmètre de notre intervention.' },
      { question: 'Un simulateur au mètre carré est-il indispensable ?', answer: 'Non. Il peut donner une fausse impression de précision si les travaux et l’existant ne sont pas étudiés. Un parcours qui qualifie les pièces, l’occupation et le calendrier est souvent un meilleur point de départ pour une demande sérieuse.' },
      { question: 'Comment éviter les demandes trop éloignées de notre activité ?', answer: 'En présentant votre périmètre et votre secteur avant le formulaire, puis en demandant le type de projet. Les pages et les campagnes sont adaptées aux travaux que vous souhaitez vraiment développer, pas à toutes les recherches de rénovation.' },
    ], cta: 'Faisons comprendre votre accompagnement avant même la première visite.',
    sources: ['https://evico.fr/creation-de-site-internet-pour-entreprise-de-renovation/', 'https://tepublico.net/fr/referencement-pour/entreprise-de-renovation/', 'https://nos-travaux.fr/'],
  },
];

export const getTrade = (slug: string) => trades.find(trade => trade.slug === slug);
