import type { ReactNode } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Check, Landmark, MapPin, Smartphone, ShieldCheck, Keyboard, FileText, Layers3 } from 'lucide-react'
import { ArtisansReveal } from '@/app/artisans/_components/ArtisansReveal'
import { civicPages, type CivicFaq, type CivicLink, type CivicSection, type CivicVisual } from '@/lib/collectivites/content'
import photos from '@/lib/collectivites/photos.json'
import { CivicCms, CivicProcedure } from './CivicInteractive'

export function CivicHeading({ label, title, children }: { label: string; title: string; children?: ReactNode }) { return <div className="civic-heading"><p className="civic-eyebrow">{label}</p><h2>{title}</h2>{children && <div className="civic-intro">{children}</div>}</div> }
export function CivicButton({ href = '/contact', children }: { href?: string; children: ReactNode }) { return <Link className="civic-button" href={href}>{children}<ArrowRight size={18} aria-hidden="true" /></Link> }
export function CivicTextLink({ link }: { link: CivicLink }) { return <Link href={link.href} className="civic-text-link">{link.label}<ArrowUpRight size={17} aria-hidden="true" /></Link> }

export function CivicPhoto({ name, priority = false }: { name: keyof typeof photos; priority?: boolean }) {
  const photo = photos[name]
  return <figure className="civic-photo"><Image src={photo.src} alt={photo.alt} width={photo.width} height={photo.height} sizes="(max-width: 800px) 92vw, 620px" priority={priority} loading={priority ? undefined : 'lazy'} /><figcaption>Photographie d’illustration · <a href={photo.source} rel="noreferrer" target="_blank">{photo.author} / Pexels<span className="sr-only"> (nouvel onglet)</span></a></figcaption></figure>
}

export function CivicVisual({ type }: { type: CivicVisual }) {
  if (type === 'cms') return <CivicCms />
  if (type === 'procedure') return <CivicProcedure />
  if (type === 'architecture') return <div className="civic-demo civic-architecture"><p className="civic-demo-label"><Landmark size={15} aria-hidden="true" /> Une information bien rangée <span>Exemple d’arborescence</span></p><div className="civic-architecture-grid">{[
    ['Vie quotidienne', 'Écoles & enfance', 'Culture & sport', 'Déchets & environnement'], ['Mon territoire', 'Communes & quartiers', 'Équipements', 'Projets du territoire'], ['Votre mairie', 'Élus & conseil', 'Publications', 'Horaires & contacts'], ['Démarches', 'État civil', 'Urbanisme', 'Prendre rendez-vous'],
  ].map(([title, ...items]) => <div key={title}><h3>{title}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></div>)}</div><p className="civic-demo-note">Une base à adapter à vos compétences et aux mots employés par les habitants.</p></div>
  if (type === 'migration') return <div className="civic-demo civic-migration"><p className="civic-demo-label"><Layers3 size={15} aria-hidden="true" /> La reprise, rendue visible <span>Exemple de méthode</span></p>{[
    ['Avant', 'Inventorier', 'Pages, PDF, outils et anciennes URLs.'], ['Pendant', 'Reprendre & valider', 'Un lot pilote, puis les contenus arbitrés.'], ['Après', 'Contrôler & suivre', 'Liens, démarches, indexation et publications.'],
  ].map(([label, title, detail]) => <div key={label}><span>{label}</span><div><h3>{title}</h3><p>{detail}</p></div><Check aria-hidden="true" /></div>)}<p className="civic-demo-note">Des étapes de validation, pas une migration automatique sans relecture.</p></div>
  if (type === 'accessibility') return <div className="civic-demo civic-a11y"><p className="civic-demo-label"><ShieldCheck size={15} aria-hidden="true" /> Penser tous les usages <span>Repères de conception</span></p><h3>Lire. Naviguer. Agir.</h3><div className="civic-a11y-sample"><Keyboard aria-hidden="true" /><span>Un focus visible</span><span className="civic-focus-example">Accéder à une démarche</span></div><div className="civic-a11y-items">{['Contrastes lisibles', 'Titres structurés', 'Erreurs expliquées', 'Documents utilisables'].map(item => <span key={item}><Check size={16} aria-hidden="true" />{item}</span>)}</div><p className="civic-demo-note">Illustration de principes, pas un résultat d’audit ou une déclaration de conformité.</p></div>
  if (type === 'territory') return <div className="civic-demo civic-territory"><p className="civic-demo-label"><MapPin size={15} aria-hidden="true" /> Plusieurs lieux, un accès clair <span>Schéma illustratif</span></p><div className="civic-territory-core"><Landmark size={28} aria-hidden="true" /><h3>Votre intercommunalité</h3><p>Des compétences et des services identifiés.</p></div><div className="civic-territory-nodes">{['Commune A', 'Commune B', 'Commune C'].map(label => <div key={label}><MapPin size={19} aria-hidden="true" /><strong>{label}</strong><span>Contacts & équipements</span></div>)}</div><p className="civic-demo-note">Communes fictives. Une liste textuelle complète une éventuelle carte interactive.</p></div>
  if (type === 'mobile') return <div className="civic-mobile-scene"><div className="civic-phone"><div className="civic-phone-camera" aria-hidden="true" /><p className="civic-demo-label"><Landmark size={16} aria-hidden="true" /> Votre commune</p><h3>L’essentiel,<br />à portée de main.</h3><div className="civic-phone-alert"><strong>Information pratique</strong><span>Les horaires actualisés au même endroit.</span></div><div className="civic-phone-links"><Link href="/collectivites/site-internet-mairie#habitants">Horaires & contact <ArrowRight size={15} aria-hidden="true" /></Link><Link href="/collectivites/demarches-en-ligne">Mes démarches <ArrowRight size={15} aria-hidden="true" /></Link><Link href="/collectivites/site-internet-mairie#contenus">Agenda & vie locale <ArrowRight size={15} aria-hidden="true" /></Link></div><span className="civic-phone-footer">Appeler · Se rendre à l’accueil</span><p className="civic-demo-note">Prototype, pas un service municipal.</p></div><span className="civic-mobile-tag"><Smartphone size={19} aria-hidden="true" /> Un vrai parcours mobile</span></div>
  return <div className="civic-demo civic-performance"><p className="civic-demo-label"><Smartphone size={15} aria-hidden="true" /> La sobriété, concrètement <span>Objectifs à mesurer</span></p><h3>Aller à l’essentiel.<br />Charger le nécessaire.</h3>{[['Images', 'Formats adaptés, dimensions utiles'], ['Code', 'Moins de scripts et de dépendances'], ['Contenus', 'HTML disponible dès le chargement'], ['Mesures', 'Tests en laboratoire + usages réels']].map(([label, detail]) => <div key={label}><strong>{label}</strong><span>{detail}</span></div>)}<p className="civic-demo-note">Aucun score fictif. Les performances dépendent du site, du réseau et du terminal.</p></div>
}

export function CivicSections({ sections }: { sections: CivicSection[] }) { return <>{sections.map((section, index) => <section key={section.id} id={section.id} className={`civic-section ${section.visual ? 'civic-split' : 'civic-editorial'} ${index % 2 ? 'civic-reverse' : ''}`}><div><CivicHeading label={section.label} title={section.title} /><div className="civic-prose">{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div>{section.points && <ul className="civic-checklist">{section.points.map(point => <li key={point}><Check size={17} aria-hidden="true" /><span>{point}</span></li>)}</ul>}{section.link && <CivicTextLink link={section.link} />}{section.source && <p className="civic-source">Source : <a href={section.source.href}>{section.source.label}</a></p>}</div>{section.visual && <ArtisansReveal className="civic-visual-reveal"><CivicVisual type={section.visual} /></ArtisansReveal>}</section>)}</> }

export function CivicCards({ exclude }: { exclude?: string }) { return <div className="civic-offers">{civicPages.filter(page => page.slug !== exclude).map(page => <Link className="civic-offer" href={`/collectivites/${page.slug}`} key={page.slug}><span className="civic-icon"><Landmark aria-hidden="true" /></span><h3>{page.short}</h3><p>{page.promise}</p><span className="civic-card-bottom">Explorer cette solution <ArrowUpRight size={19} aria-hidden="true" /></span></Link>)}</div> }

export function CivicFaqs({ items }: { items: CivicFaq[] }) { return <section id="questions" className="civic-section civic-faq"><CivicHeading label="Vos questions, simplement" title="Avant de faire le premier pas." /><div>{items.map(item => <details key={item.question}><summary>{item.question}<span aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section> }

export function CivicFinal() { return <section className="civic-final"><div><p className="civic-eyebrow">Litus · Lorient & Le Mans</p><h2>Parlons de votre territoire.<br /><em>Et de ceux qui y vivent.</em></h2><p>Votre site actuel, vos contraintes, les besoins de vos services : commençons par poser les bonnes questions.</p></div><div><CivicButton>Échanger sur votre projet</CivicButton><Link className="civic-final-phone" href="tel:+33744985521">07 44 98 55 21</Link><span>Un premier échange pour cadrer le besoin.</span></div></section> }
