import { pageMetadata } from '@/lib/seo/metadata'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Blocks, Check, ChevronDown, Code2, FileCheck2, Fingerprint, GitBranch, LifeBuoy, LockKeyhole, PanelTop, SlidersHorizontal, Unplug } from 'lucide-react'
import { ServiceHero } from '@/components/sections/services/ServiceHero'
import { BusinessSectionHeading, ServiceReveal } from '@/components/sections/services/BusinessService'
import { DevelopmentDemo } from '@/components/sections/services/TechnicalDemo'
import { ServicePageSeo, serviceMetadata } from '@/components/sections/services/ServicePageSeo'
import { ExpertiseServiceLinks } from '@/components/expertise/ExpertiseServiceLinks'
import '@/components/sections/services/technical-services.css'

const path = '/developpement-web-sur-mesure'
const name = 'Développement web sur mesure'
const description = 'Configurateur, réservation, module métier ou évolution technique : Litus développe les fonctionnalités web adaptées à votre activité et à votre site existant.'
export const metadata = pageMetadata("/developpement-web-sur-mesure", serviceMetadata({ path, name, title: 'Développement web sur mesure : modules & fonctionnalités | Litus', description, image: '/blog/photos/bureau-notes-analyse.webp' }))
const contact = '/contact?objet=D%C3%A9veloppement%20web%20sur%20mesure'
const questions = [
  { question: 'Quelle différence avec une application web sur mesure ?', answer: 'Le développement sur mesure peut ajouter une fonction précise à un site existant : configurateur, réservation, moteur de recherche ou administration. Une application web correspond à un produit plus complet, avec ses utilisateurs, ses écrans et ses parcours métier. Nous déterminons le bon périmètre ensemble.' },
  { question: 'Pouvez-vous intervenir sur un site développé par une autre agence ?', answer: 'Oui, après avoir étudié le code, l’hébergement, les accès et les licences disponibles. Cet état des lieux permet de distinguer ce qui peut évoluer, ce qui mérite une correction et les éventuelles limites de la base actuelle.' },
  { question: 'Faut-il tout refaire pour ajouter une fonctionnalité ?', answer: 'Pas nécessairement. Nous cherchons d’abord à intégrer le besoin dans le site existant. Si sa structure rend cette évolution trop fragile ou coûteuse, nous vous présentons les alternatives et leurs conséquences avant de développer.' },
  { question: 'Comment choisissez-vous les technologies ?', answer: 'Selon le besoin, l’existant, les volumes attendus, les contraintes d’hébergement et la capacité à maintenir le projet. Le choix peut combiner le CMS en place, un module dédié et des services externes. Il est expliqué au cadrage.' },
  { question: 'Que comprend le devis de développement ?', answer: 'Le périmètre fonctionnel, les écrans ou modules concernés, les intégrations, les critères de validation et les livrables. Les frais de services tiers, l’hébergement, la maintenance et les évolutions ultérieures sont précisés séparément selon le projet.' },
  { question: 'Que se passe-t-il après la mise en ligne ?', answer: 'Nous transmettons les accès et la documentation prévus au contrat, puis organisons la prise en main. Un suivi peut couvrir les mises à jour, les correctifs et de nouvelles fonctionnalités, avec un périmètre et un rythme convenus ensemble.' },
]
const uses = [
  { icon: SlidersHorizontal, title: 'Configurateurs & devis guidés', text: 'Faire préciser un besoin, appliquer vos règles de choix et transmettre une demande exploitable. Un parcours adapté à vos produits ou à vos prestations.', example: 'Exemple : options compatibles et récapitulatif avant contact.' },
  { icon: PanelTop, title: 'Réservation & parcours client', text: 'Présenter les disponibilités, gérer une demande de créneau ou suivre les étapes d’une commande. Relier l’interface à votre organisation réelle.', example: 'Exemple : réservation soumise à validation de votre équipe.' },
  { icon: Blocks, title: 'Modules & administration', text: 'Ajouter une recherche multicritère, des règles tarifaires ou un écran de gestion. Faire évoluer votre site sans empiler des outils déconnectés.', example: 'Exemple : mise à jour d’un catalogue depuis un espace dédié.' },
]

export default function DevelopmentPage() {
  return <div className="business-service technical-service-page">
    <ServicePageSeo path={path} name={name} description={description} questions={questions} />
    <ServiceHero id="developpement-title" eyebrow="Développement web · Sur mesure" title={'Des fonctionnalités web\nà la mesure de vos idées.'} accent="à la mesure de vos idées." description="Votre site a besoin d’aller plus loin ? Configurateur, réservation, module métier : nous développons les fonctionnalités qui manquent à votre parcours, en tenant compte de vos outils et de vos contraintes." primaryAction={{ label: 'Parlons de votre besoin', href: contact }} secondaryAction={{ label: 'Explorer les possibilités', href: '#fonctionnalites' }} visualBackground="/blog/photos/bureau-notes-analyse.webp" visual={<DevelopmentDemo />} proof={<ul className="business-hero-proof"><li><Fingerprint />Votre fonctionnement</li><li><GitBranch />Une évolution maîtrisée</li><li><LifeBuoy />Un suivi dans la durée</li></ul>} />
    <div className="business-content">
      <section className="business-section" aria-labelledby="developpement-enjeu"><div className="business-container"><BusinessSectionHeading id="developpement-enjeu" eyebrow="Quand le standard atteint ses limites" description="Un formulaire trop simple, une extension qui impose son fonctionnement, une opération qui reste manuelle. Nous partons du point de friction pour concevoir une solution proportionnée.">Votre besoin est précis.<br /><em>La réponse doit l’être aussi.</em></BusinessSectionHeading><div className="tech-intent-strip"><span><Check />Le parcours de vos utilisateurs</span><span><Check />Les règles de votre activité</span><span><Check />La réalité de votre site actuel</span></div></div></section>
      <section id="fonctionnalites" className="business-section business-section-soft" aria-labelledby="developpement-usages"><div className="business-container"><BusinessSectionHeading id="developpement-usages" eyebrow="Des fonctions qui rendent service" description="PME, équipes commerciales, prestataires ou e-commerçants : le sur-mesure devient utile lorsqu’une fonction standard ne répond plus correctement au besoin.">Le bon module.<br /><em>Au bon endroit.</em></BusinessSectionHeading><ServiceReveal className="business-grid">{uses.map(({ icon: Icon, title, text, example }) => <article key={title} className="business-card"><span className="business-icon"><Icon /></span><h3>{title}</h3><p>{text}</p><small className="tech-card-note">{example}</small></article>)}</ServiceReveal></div></section>
      <section className="business-section" aria-labelledby="developpement-existant"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">Votre existant, d’abord</p><h2 id="developpement-existant">Faire évoluer.<br /><em>Sans repartir par réflexe.</em></h2><p>Avant de choisir une technologie, nous regardons ce qui fonctionne déjà : contenus, parcours, CMS, composants et connexions. Le travail porte ensuite sur ce qui apporte une amélioration concrète.</p><p>Si votre besoin concerne surtout l’image, l’arborescence ou le référencement d’un site complet, une <Link href="/refonte-site-internet" className="business-text-link">refonte de site internet</Link> peut être plus adaptée.</p></div><div className="tech-decision-list">{[{ n: '01', title: 'Conserver ce qui tient', text: 'Réutiliser les fonctions et contenus qui répondent déjà aux besoins.' }, { n: '02', title: 'Développer ce qui manque', text: 'Construire le module utile et définir ses points de connexion.' }, { n: '03', title: 'Remplacer ce qui bloque', text: 'Isoler les limites techniques et planifier une reprise si nécessaire.' }].map(item => <article key={item.n}><span>{item.n}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div></section>
      <section className="business-section business-section-warm" aria-labelledby="developpement-architecture"><div className="business-container business-split"><div className="tech-architecture" aria-label="Les trois composantes du module développé"><div><PanelTop /><strong>L’interface</strong><span>Un parcours clair sur chaque écran</span></div><i aria-hidden="true" /><div><Code2 /><strong>Vos règles métier</strong><span>Conditions, calculs et validations</span></div><i aria-hidden="true" /><div><Unplug /><strong>Votre environnement</strong><span>Site, données et logiciels utiles</span></div></div><div className="business-copy"><p className="business-kicker">Visible à l’écran, solide derrière</p><h2 id="developpement-architecture">Un ensemble cohérent.<br /><em>Pas une fonction isolée.</em></h2><p>Une bonne interface ne suffit pas. Nous travaillons aussi les règles, les droits d’accès, la validation des données et les échanges avec les outils concernés.</p><ul className="business-check-list"><li><Check />États utiles : chargement, erreur, confirmation.</li><li><Check />Utilisation au clavier et adaptation mobile.</li><li><Check />Comportements testés sur les parcours convenus.</li></ul><Link href="/integrations-api" className="business-text-link">Relier le module à vos logiciels<ArrowRight size={15} /></Link></div></div></section>
      <section className="business-section business-section-dark" aria-labelledby="developpement-methode"><div className="business-container"><BusinessSectionHeading id="developpement-methode" eyebrow="Un développement que vous suivez" description="Vous voyez les écrans, essayez les fonctions et validez les étapes. Les arbitrages restent compréhensibles, même sans être technique.">Du besoin formulé<br /><em>à la fonction utilisée.</em></BusinessSectionHeading><ServiceReveal className="tech-method">{[{ title: 'Cadrer le besoin', text: 'Décrire le parcours, les utilisateurs, les règles et les contraintes de l’existant.' }, { title: 'Montrer avant de construire', text: 'Valider une maquette ou un prototype et les critères de réussite.' }, { title: 'Développer et essayer', text: 'Avancer par fonctions, contrôler les cas particuliers et recueillir vos retours.' }, { title: 'Mettre en service', text: 'Préparer le déploiement, vérifier le parcours et transmettre les éléments convenus.' }].map((item, i) => <article key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</ServiceReveal></div></section>
      <section className="business-section" aria-labelledby="developpement-suivi"><div className="business-container business-split"><figure className="business-photo"><Image src="/blog/photos/echange-tablette.webp" width={1400} height={938} sizes="(max-width:850px) 100vw, 50vw" alt="Deux personnes préparent un projet autour d’une tablette et d’un carnet" /><figcaption className="business-photo-note"><strong>Une fonction que votre équipe comprend.</strong><span>Des choix expliqués, un périmètre écrit.</span></figcaption></figure><div className="business-copy"><p className="business-kicker">Le projet continue après la livraison</p><h2 id="developpement-suivi">Du code, des accès.<br /><em>Et de la continuité.</em></h2><p>Nous définissons dès le départ les livrables, la documentation, les modalités d’hébergement et les conditions de maintenance. Votre équipe sait ce qu’elle reçoit et comment faire évoluer l’outil.</p><ul className="business-check-list"><li><LockKeyhole />Permissions et données prises en compte au cadrage.</li><li><FileCheck2 />Documentation et transmission prévues dans le périmètre.</li><li><LifeBuoy />Correctifs et évolutions organisés selon vos besoins.</li></ul><Link href="/creation-application-web" className="business-text-link">Vous avez besoin d’une application complète ?<ArrowRight size={15} /></Link></div></div></section>
      <section id="faq" className="business-section business-section-soft" aria-labelledby="developpement-faq"><div className="business-container"><BusinessSectionHeading id="developpement-faq" eyebrow="Vos questions">Le sur-mesure,<br /><em>avec un cadre clair.</em></BusinessSectionHeading><div className="business-faq">{questions.map(({ question, answer }) => <details key={question}><summary>{question}<ChevronDown /></summary><p>{answer}</p></details>)}</div></div></section>
      <section className="business-section"><div className="business-container"><div className="business-final"><div><p className="business-kicker">La prochaine fonction commence ici</p><h2>Quel parcours aimeriez-vous<br /><em>rendre plus simple ?</em></h2><p>Montrez-nous votre site, votre besoin et ce qui vous freine. Nous vous aiderons à définir une première étape utile.</p></div><div className="business-final-actions"><Link href={contact} className="site-cta-primary">Décrire mon besoin<ArrowRight size={18} /></Link><span>Premier échange · Sans engagement</span><a href="tel:+33744985521">07 44 98 55 21</a></div></div><nav className="tech-related" aria-label="Prestations complémentaires"><Link href="/creation-application-web">Application web</Link><Link href="/integrations-api">Intégrations & API</Link><Link href="/creation-outils-ia">Outils IA sur mesure</Link><Link href="/realisations">Nos réalisations</Link></nav></div></section>
    </div>
    <ExpertiseServiceLinks tools={['react', 'typescript', 'tailwind', 'vercel']} title="De l’interface à la production, des choix expliqués." description="Composants React, contrats TypeScript, intégration Tailwind et déploiement Vercel : découvrez les interventions concrètes derrière notre développement sur mesure." />
  </div>
}
