// Photographs only. File sources and licences verified on Wikimedia Commons and Pexels.
// Local copies resized and converted to WebP; CC BY-SA adaptations retain their licence.
export interface BlogPhoto { id: string; src: string; alt: string; caption: string; sourceUrl: string; credit: string; license: string; licenseUrl: string; width: number; height: number; tags: readonly string[]; capturedAt: string; originalWidth: number; originalHeight: number }

export const blogPhotos: readonly BlogPhoto[] = [
  {
    "id": "lorient-port-rohan",
    "src": "/blog/photos/lorient-port-rohan.webp",
    "alt": "Voiliers et quais du port de plaisance de Lorient après la pluie",
    "caption": "Le quai de Rohan à Lorient, photographié après la pluie.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Le_quai_de_Rohan_(Lorient)_apr%C3%A8s_la_pluie_-_panoramio.jpg",
    "credit": "Taratata",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "width": 1400,
    "height": 1046,
    "tags": [
      "Lorient",
      "Morbihan",
      "local",
      "port"
    ],
    "capturedAt": "Taken on 24 October 2011",
    "originalWidth": 2592,
    "originalHeight": 1936
  },
  {
    "id": "lorient-cite-voile",
    "src": "/blog/photos/lorient-cite-voile.webp",
    "alt": "La Cité de la Voile Éric Tabarly à Lorient",
    "caption": "La Cité de la Voile Éric Tabarly, dans le quartier de Lorient La Base.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_de_la_cit%C3%A9_de_la_Voile_Eric_Tabarly_%C3%A0_Lorient_DSC_0437.jpg",
    "credit": "Pline",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1400,
    "height": 933,
    "tags": [
      "Lorient",
      "Morbihan",
      "local",
      "activite"
    ],
    "capturedAt": "2021-05-21 18:34:32",
    "originalWidth": 6000,
    "originalHeight": 4000
  },
  {
    "id": "lanester-blavet",
    "src": "/blog/photos/lanester-blavet.webp",
    "alt": "La presqu’île de Saint-Guénaël et le Blavet à Lanester",
    "caption": "À Lanester, la presqu’île de Saint-Guénaël à la confluence du Plessis et du Blavet.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:481_Lanester.jpg",
    "credit": "Moreau.henri",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1400,
    "height": 820,
    "tags": [
      "Lanester",
      "Lorient",
      "Morbihan",
      "local"
    ],
    "capturedAt": "2019-09-29 14:18:54",
    "originalWidth": 4320,
    "originalHeight": 2530
  },
  {
    "id": "ploemeur-lomener",
    "src": "/blog/photos/ploemeur-lomener.webp",
    "alt": "L’anse de Stole à Lomener, sur la commune de Ploemeur",
    "caption": "L’anse de Stole à Lomener, sur le littoral de Ploemeur.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:0_Lomener_-_Anse_de_Stole.JPG",
    "credit": "Jean-Pol GRANDMONT",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "width": 1400,
    "height": 933,
    "tags": [
      "Ploemeur",
      "Lorient",
      "Morbihan",
      "local",
      "littoral"
    ],
    "capturedAt": "2019-09-03",
    "originalWidth": 5184,
    "originalHeight": 3456
  },
  {
    "id": "hennebont-blavet",
    "src": "/blog/photos/hennebont-blavet.webp",
    "alt": "Le quai du Pont-Neuf et le pont Jéhanne-la-Flamme à Hennebont",
    "caption": "Le quai du Pont-Neuf et le pont Jéhanne-la-Flamme sur le Blavet, à Hennebont.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:W5032_Hennebont_QuaiPtNeuf-PtJehanneLaFlamme2070XA1.jpg",
    "credit": "Llann Wé²",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1400,
    "height": 790,
    "tags": [
      "Hennebont",
      "Lorient",
      "Morbihan",
      "local"
    ],
    "capturedAt": "2018-05-18 12:48:35",
    "originalWidth": 5984,
    "originalHeight": 3376
  },
  {
    "id": "larmor-mairie",
    "src": "/blog/photos/larmor-mairie.webp",
    "alt": "La mairie de Larmor-Plage dans le Morbihan",
    "caption": "La mairie de Larmor-Plage, photographiée en 2009.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Larmor-Plage-Mairie.jpg",
    "credit": "Bruno Corpet (Quoique)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1400,
    "height": 931,
    "tags": [
      "Larmor-Plage",
      "Lorient",
      "Morbihan",
      "local"
    ],
    "capturedAt": "2009-09-23",
    "originalWidth": 3008,
    "originalHeight": 2000
  },
  {
    "id": "larmor-rue-fort",
    "src": "/blog/photos/larmor-rue-fort.webp",
    "alt": "La rue du Fort dans le centre de Larmor-Plage",
    "caption": "La rue du Fort à Larmor-Plage, en septembre 2019.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:0_Larmor-Plage_-_Rue_du_Fort.JPG",
    "credit": "Jean-Pol GRANDMONT",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "width": 726,
    "height": 1100,
    "tags": [
      "Larmor-Plage",
      "Lorient",
      "Morbihan",
      "local",
      "centre-ville"
    ],
    "capturedAt": "2019-09-01",
    "originalWidth": 3382,
    "originalHeight": 5127
  },
  {
    "id": "auray-saint-goustan",
    "src": "/blog/photos/auray-saint-goustan.webp",
    "alt": "Le port de Saint-Goustan et les maisons d’Auray",
    "caption": "Le port de Saint-Goustan à Auray, dans le Morbihan.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Auray_port_de_Saint-Goustan.jpg",
    "credit": "Myrabella",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1400,
    "height": 927,
    "tags": [
      "Auray",
      "Morbihan",
      "local",
      "commerce"
    ],
    "capturedAt": "2010-04-27",
    "originalWidth": 4218,
    "originalHeight": 2792
  },
  {
    "id": "vannes-remparts",
    "src": "/blog/photos/vannes-remparts.webp",
    "alt": "Les remparts et jardins du centre de Vannes",
    "caption": "Les remparts de Vannes, photographiés en août 2018.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Remparts_de_Vannes_-_Vannes,_France_-_August_19,_2018.jpg",
    "credit": "Giorgio Galeotti",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "width": 1400,
    "height": 934,
    "tags": [
      "Vannes",
      "Morbihan",
      "local",
      "centre-ville"
    ],
    "capturedAt": "2018-08-19 18:13:07",
    "originalWidth": 7360,
    "originalHeight": 4912
  },
  {
    "id": "le-mans-republique",
    "src": "/blog/photos/le-mans-republique.webp",
    "alt": "La place de la République et son tramway au Mans",
    "caption": "La place de la République au Mans, vue depuis la Visitation en 2009.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Place_de_la_R%C3%A9publique_(Le_Mans).JPG",
    "credit": "Le Mans",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "width": 1400,
    "height": 1050,
    "tags": [
      "Le Mans",
      "Sarthe",
      "local",
      "commerce",
      "centre-ville"
    ],
    "capturedAt": "2009-09-19",
    "originalWidth": 2272,
    "originalHeight": 1704
  },
  {
    "id": "le-mans-cathedrale",
    "src": "/blog/photos/le-mans-cathedrale.webp",
    "alt": "La cathédrale Saint-Julien du Mans depuis la place des Jacobins",
    "caption": "Le chevet de la cathédrale Saint-Julien du Mans, depuis la place des Jacobins.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Le_Mans_(Sarthe)_-_Cath%C3%A9drale_Saint-Julien_-_Chevet_vu_depuis_la_place_des_Jacobins.jpg",
    "credit": "Patrick",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "width": 1400,
    "height": 928,
    "tags": [
      "Le Mans",
      "Sarthe",
      "local",
      "patrimoine"
    ],
    "capturedAt": "Taken on 30 March 2019, 13:27:18",
    "originalWidth": 4724,
    "originalHeight": 3130
  },
  {
    "id": "le-mans-pont-yssoir",
    "src": "/blog/photos/le-mans-pont-yssoir.webp",
    "alt": "Le pont Yssoir et la rue Voltaire au Mans",
    "caption": "Le pont Yssoir et la rue Voltaire au Mans, photographiés en 2017.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Le_Mans_R01.jpg",
    "credit": "Marc Ryckaert",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1400,
    "height": 938,
    "tags": [
      "Le Mans",
      "Sarthe",
      "local",
      "centre-ville"
    ],
    "capturedAt": "2017-05-07 11:12:19",
    "originalWidth": 4814,
    "originalHeight": 3227
  },
  {
    "id": "allonnes-mairie",
    "src": "/blog/photos/allonnes-mairie.webp",
    "alt": "La mairie d’Allonnes dans la Sarthe",
    "caption": "La mairie d’Allonnes, dans l’agglomération mancelle, en 2013.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Allonnes_(Sarthe)_-_Mairie.JPG",
    "credit": "Stephvvv",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1400,
    "height": 1050,
    "tags": [
      "Allonnes",
      "Le Mans",
      "Sarthe",
      "local"
    ],
    "capturedAt": "2013-11-27 12:11:02",
    "originalWidth": 2880,
    "originalHeight": 2160
  },
  {
    "id": "coulaines-centre",
    "src": "/blog/photos/coulaines-centre.webp",
    "alt": "Vue du centre-ville de Coulaines depuis le sud",
    "caption": "Le centre de Coulaines, au nord du Mans, photographié en 2008.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coulaines_centre.jpg",
    "credit": "The original uploader was OldLion at French Wikipedia.",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "width": 1400,
    "height": 1050,
    "tags": [
      "Coulaines",
      "Le Mans",
      "Sarthe",
      "local"
    ],
    "capturedAt": "2008-06-28",
    "originalWidth": 2560,
    "originalHeight": 1920
  },
  {
    "id": "arnage-eglise",
    "src": "/blog/photos/arnage-eglise.webp",
    "alt": "Le monument aux morts au premier plan devant l’église d’Arnage",
    "caption": "Le monument aux morts et l’église d’Arnage, dans la Sarthe, photographiés en 2017.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Arnage_%C3%A9glise.jpg",
    "credit": "Antoine Garnier",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 733,
    "height": 1100,
    "tags": [
      "Arnage",
      "Le Mans",
      "Sarthe",
      "local"
    ],
    "capturedAt": "2017-08-15 16:47:57",
    "originalWidth": 2848,
    "originalHeight": 4272
  },
  {
    "id": "chapelle-saint-aubin-commerce",
    "src": "/blog/photos/chapelle-saint-aubin-commerce.webp",
    "alt": "Le centre commercial de La Chapelle-Saint-Aubin en 2007",
    "caption": "Vue d’archive du centre commercial de La Chapelle-Saint-Aubin, en octobre 2007.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Centre_commercial_de_la_Chapelle_Saint_Aubin_le_06.10.07.JPG",
    "credit": "Original uploader was Fantassin 72 at fr.wikipedia",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "width": 1400,
    "height": 1050,
    "tags": [
      "La Chapelle-Saint-Aubin",
      "Le Mans",
      "Sarthe",
      "local",
      "commerce"
    ],
    "capturedAt": "7 October 2007 (original upload date)",
    "originalWidth": 2816,
    "originalHeight": 2112
  },
  {
    "id": "yvre-leveque-placette",
    "src": "/blog/photos/yvre-leveque-placette.webp",
    "alt": "Une placette et ses façades à Yvré-l’Évêque",
    "caption": "Une placette du centre d’Yvré-l’Évêque, photographiée en juillet 2012.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Placette-%C3%A0-Yvr%C3%A9-l%27%C3%A9v%C3%AAque.jpg",
    "credit": "Danielclauzier",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1400,
    "height": 917,
    "tags": [
      "Yvré-l’Évêque",
      "Le Mans",
      "Sarthe",
      "local",
      "centre-ville"
    ],
    "capturedAt": "2012-07-24",
    "originalWidth": 2551,
    "originalHeight": 1671
  },
  {
    "id": "bureau-minimal",
    "src": "/blog/photos/bureau-minimal.webp",
    "alt": "Un bureau lumineux avec ordinateur et deux sièges",
    "caption": "Photographie d’illustration : un espace de travail simple et lumineux.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Clean_minimalist_office_(Unsplash).jpg",
    "credit": "Roman Bozhko romanbozhko",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 952,
    "tags": [
      "bureau",
      "PME",
      "site-web",
      "organisation"
    ],
    "capturedAt": "2017-05-04",
    "originalWidth": 7806,
    "originalHeight": 5304
  },
  {
    "id": "bureau-reunion-clair",
    "src": "/blog/photos/bureau-reunion-clair.webp",
    "alt": "Une table de réunion blanche devant un tableau mural",
    "caption": "Photographie d’illustration : une salle pour préparer et cadrer un projet.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:White_office_space_(Unsplash).jpg",
    "credit": "Breather breather",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "bureau",
      "reunion",
      "strategie",
      "cahier-des-charges"
    ],
    "capturedAt": "2016-11-15",
    "originalWidth": 5616,
    "originalHeight": 3744
  },
  {
    "id": "bureau-notes-analyse",
    "src": "/blog/photos/bureau-notes-analyse.webp",
    "alt": "Des notes et des outils de travail disposés sur un bureau",
    "caption": "Photographie d’illustration : organiser ses notes et ses priorités de travail.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Working_at_office_(Unsplash).jpg",
    "credit": "Javier Quesada quesada179",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "analyse",
      "strategie",
      "organisation",
      "cahier-des-charges"
    ],
    "capturedAt": "2017-03-14",
    "originalWidth": 3888,
    "originalHeight": 2592
  },
  {
    "id": "ordinateur-saisie",
    "src": "/blog/photos/ordinateur-saisie.webp",
    "alt": "Des mains saisissent du texte sur un ordinateur portable",
    "caption": "Photographie d’illustration : travailler le contenu d’un site sur ordinateur.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Typing_on_a_mac_(Unsplash).jpg",
    "credit": "Thomas Lefebvre imthebear",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "site-web",
      "contenu",
      "ordinateur",
      "SEO"
    ],
    "capturedAt": "2014-12-04",
    "originalWidth": 4705,
    "originalHeight": 3137
  },
  {
    "id": "code-ecran",
    "src": "/blog/photos/code-ecran.webp",
    "alt": "Du code informatique photographié sur un écran d’ordinateur",
    "caption": "Photographie d’illustration : du code sur un écran, pour évoquer le développement web.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Code_on_computer_monitor_(Unsplash).jpg",
    "credit": "Markus Spiske markusspiske",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "developpement",
      "site-web",
      "technique"
    ],
    "capturedAt": "2017-02-14",
    "originalWidth": 5760,
    "originalHeight": 3840
  },
  {
    "id": "ordinateur-developpement",
    "src": "/blog/photos/ordinateur-developpement.webp",
    "alt": "Un ordinateur portable utilisé pour programmer",
    "caption": "Photographie d’illustration : préparer et développer un site sur ordinateur portable.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Laptop_coding_programs_(Unsplash).jpg",
    "credit": "Tirza van Dijk tirzavandijk",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "developpement",
      "site-web",
      "ordinateur"
    ],
    "capturedAt": "2016-01-17",
    "originalWidth": 4047,
    "originalHeight": 2698
  },
  {
    "id": "developpeur-travail",
    "src": "/blog/photos/developpeur-travail.webp",
    "alt": "Une personne travaille sur un ordinateur dans un espace de bureau",
    "caption": "Photographie d’illustration : un professionnel au travail sur son ordinateur.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Programmer_at_work_(Unsplash).jpg",
    "credit": "Crew crew",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 1014,
    "tags": [
      "developpement",
      "site-web",
      "PME",
      "bureau"
    ],
    "capturedAt": "2016-01-10",
    "originalWidth": 4597,
    "originalHeight": 3330
  },
  {
    "id": "planning-bureau",
    "src": "/blog/photos/planning-bureau.webp",
    "alt": "Un carnet ouvert, un ordinateur et un téléphone sur une table blanche",
    "caption": "Photographie d’illustration : un carnet et des outils de travail pour préparer un projet.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:White_work_table_with_notes,_smartphone_and_laptop_(Unsplash).jpg",
    "credit": "JESHOOTS.COM jeshoots",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "strategie",
      "organisation",
      "cahier-des-charges",
      "budget"
    ],
    "capturedAt": "2017-03-08",
    "originalWidth": 4600,
    "originalHeight": 3067
  },
  {
    "id": "conception-bureau",
    "src": "/blog/photos/conception-bureau.webp",
    "alt": "Une règle et un ordinateur portable sur un bureau",
    "caption": "Photographie d’illustration : les outils de préparation et de conception d’un projet.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ruler_and_laptop_on_a_desk_(Unsplash).jpg",
    "credit": "Oli Dale olidale",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "site-web",
      "conception",
      "cahier-des-charges"
    ],
    "capturedAt": "2016-09-20",
    "originalWidth": 5472,
    "originalHeight": 3648
  },
  {
    "id": "carnet-projet",
    "src": "/blog/photos/carnet-projet.webp",
    "alt": "Un stylo posé sur un carnet fermé",
    "caption": "Photographie d’illustration : un carnet et un stylo pour noter les priorités d’un projet.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pen_on_a_notebook_(Unsplash).jpg",
    "credit": "Thomas Martinsen faceline",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 828,
    "tags": [
      "cahier-des-charges",
      "strategie",
      "organisation"
    ],
    "capturedAt": "2014-11-02",
    "originalWidth": 4811,
    "originalHeight": 2844
  },
  {
    "id": "reunion-cafe",
    "src": "/blog/photos/reunion-cafe.webp",
    "alt": "Des personnes autour d’une table de café, dont une tient un journal ouvert",
    "caption": "Photographie d’illustration en noir et blanc : une table de café et la lecture d’un journal.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meeting_at_the_Cafe_(Unsplash).jpg",
    "credit": "rawpixel.com rawpixel",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 934,
    "tags": [
      "reunion",
      "cafe",
      "lecture",
      "echange"
    ],
    "capturedAt": "2017-05-10",
    "originalWidth": 6000,
    "originalHeight": 4004
  },
  {
    "id": "echange-tablette",
    "src": "/blog/photos/echange-tablette.webp",
    "alt": "Deux personnes échangent avec un téléphone et une tablette",
    "caption": "Photographie d’illustration : consulter ensemble des informations sur tablette et téléphone.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Two_people_meeting_with_iphone_and_ipad_(Unsplash).jpg",
    "credit": "Alejandro Escamilla alejandroescamilla",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 938,
    "tags": [
      "reunion",
      "mobile",
      "strategie",
      "accompagnement"
    ],
    "capturedAt": "2013-05-27",
    "originalWidth": 4728,
    "originalHeight": 3168
  },
  {
    "id": "salle-echange",
    "src": "/blog/photos/salle-echange.webp",
    "alt": "Un espace de réunion convivial avec table et sièges",
    "caption": "Photographie d’illustration : un lieu de travail pour les échanges et les décisions d’équipe.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Casual_Meeting_Room_(Unsplash).jpg",
    "credit": "Dan Gold danielcgold",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 788,
    "tags": [
      "reunion",
      "PME",
      "bureau"
    ],
    "capturedAt": "2017-03-07",
    "originalWidth": 6000,
    "originalHeight": 3376
  },
  {
    "id": "mobile-en-main",
    "src": "/blog/photos/mobile-en-main.webp",
    "alt": "Un téléphone noir tenu dans une main, vu de dos",
    "caption": "Photographie d’illustration : un smartphone tenu en main.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Black_smartphone_in_hand_(Unsplash).jpg",
    "credit": "Dennis Cortés cortes",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "mobile",
      "responsive",
      "site-web",
      "parcours-client"
    ],
    "capturedAt": "2016-10-09",
    "originalWidth": 6000,
    "originalHeight": 4000
  },
  {
    "id": "mobile-ordinateur",
    "src": "/blog/photos/mobile-ordinateur.webp",
    "alt": "Une personne utilise un smartphone devant un ordinateur portable",
    "caption": "Photographie d’illustration : passer du téléphone à l’ordinateur dans son travail quotidien.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Man_with_smartphone_and_laptop_(Unsplash).jpg",
    "credit": "Alejandro Escamilla alejandroescamilla",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "mobile",
      "responsive",
      "PME",
      "ordinateur"
    ],
    "capturedAt": "2013-05-27",
    "originalWidth": 5616,
    "originalHeight": 3744
  },
  {
    "id": "atelier-menuiserie",
    "src": "/blog/photos/atelier-menuiserie.webp",
    "alt": "Un atelier de travail du bois avec établi et outils",
    "caption": "Photographie d’illustration : un atelier de menuiserie et ses outils.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Woodworking_workshop_(Unsplash).jpg",
    "credit": "s w wengenroad",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 898,
    "tags": [
      "artisan",
      "menuisier",
      "atelier",
      "metier"
    ],
    "capturedAt": "2015-10-07",
    "originalWidth": 3872,
    "originalHeight": 2482
  },
  {
    "id": "artisan-bois",
    "src": "/blog/photos/artisan-bois.webp",
    "alt": "Un artisan travaille le bois dans son atelier",
    "caption": "Photographie d’illustration : le travail du bois dans un atelier.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Woodworker_in_a_workshop_(Unsplash).jpg",
    "credit": "Ian Schneider goian",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 935,
    "tags": [
      "artisan",
      "menuisier",
      "atelier",
      "metier"
    ],
    "capturedAt": "2016-05-12",
    "originalWidth": 6016,
    "originalHeight": 4016
  },
  {
    "id": "atelier-etabli",
    "src": "/blog/photos/atelier-etabli-v2.webp",
    "alt": "Des outils à main disposés à plat : marteau, hachette, cutter et lampe",
    "caption": "Photographie d’illustration : le contenu d’une boîte à outils, disposé à plat.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Toolkit_and_tools_(Unsplash).jpg",
    "credit": "Todd Quackenbush toddquackenbush",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1355,
    "height": 1100,
    "tags": [
      "artisan",
      "atelier",
      "metier",
      "preparation",
      "outils"
    ],
    "capturedAt": "2014-08-01",
    "originalWidth": 5663,
    "originalHeight": 4599
  },
  {
    "id": "atelier-perceuse",
    "src": "/blog/photos/atelier-perceuse.webp",
    "alt": "Un artisan utilise une perceuse à colonne dans un atelier",
    "caption": "Photographie d’illustration : un artisan à la perceuse à colonne.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Workshop_(Unsplash).jpg",
    "credit": "Adi Goldstein adigold1",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 980,
    "tags": [
      "artisan",
      "atelier",
      "metier",
      "outil"
    ],
    "capturedAt": "2017-05-13",
    "originalWidth": 6685,
    "originalHeight": 4678
  },
  {
    "id": "chantier-vue-dessus",
    "src": "/blog/photos/chantier-vue-dessus.webp",
    "alt": "Un chantier de construction vu depuis les étages",
    "caption": "Photographie d’illustration : l’organisation d’un chantier de construction.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_Above_Construction_Site_(Unsplash).jpg",
    "credit": "chuttersnap chuttersnap",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 935,
    "tags": [
      "chantier",
      "batiment",
      "artisan",
      "organisation"
    ],
    "capturedAt": "2017-02-19",
    "originalWidth": 6016,
    "originalHeight": 4016
  },
  {
    "id": "chantier-travaux",
    "src": "/blog/photos/chantier-travaux.webp",
    "alt": "Des équipements industriels et des escaliers métalliques jaunes",
    "caption": "Photographie d’illustration : un espace industriel et ses escaliers d’accès.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Construction_work_area_(Unsplash).jpg",
    "credit": "Samuel Zeller samuelzeller",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "industrie",
      "equipement",
      "atelier",
      "PME"
    ],
    "capturedAt": "2015-05-20",
    "originalWidth": 4870,
    "originalHeight": 3247
  },
  {
    "id": "commerce-disquaire",
    "src": "/blog/photos/commerce-disquaire.webp",
    "alt": "Les rayons d’un magasin de disques",
    "caption": "Photographie d’illustration : un commerce indépendant et la présentation de son offre.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vintage_record_store_(Unsplash).jpg",
    "credit": "Samuel Dixon samueldixon",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "commerce",
      "boutique",
      "offre",
      "local-commercial"
    ],
    "capturedAt": "2016-08-05",
    "originalWidth": 3000,
    "originalHeight": 2000
  },
  {
    "id": "commerce-vitrine",
    "src": "/blog/photos/commerce-vitrine.webp",
    "alt": "Une passante regarde une vitrine de boutique",
    "caption": "Photographie d’illustration : une vitrine attire le regard d’une passante.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Woman_looking_at_shop_window_(Unsplash).jpg",
    "credit": "Gyorgy Bakos thinkdeep",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "commerce",
      "boutique",
      "vitrine",
      "parcours-client"
    ],
    "capturedAt": "2017-05-10",
    "originalWidth": 3000,
    "originalHeight": 2000
  },
  {
    "id": "emballage-cadeau",
    "src": "/blog/photos/emballage-cadeau.webp",
    "alt": "Papiers kraft, ficelle, tampons et outils d’emballage disposés sur une table",
    "caption": "Photographie d’illustration : le matériel de préparation et de personnalisation des emballages.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Unique_Present_Packaging_(Unsplash).jpg",
    "credit": "Vítor Santos vtrsnts",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 1000,
    "tags": [
      "ecommerce",
      "emballage",
      "produit",
      "commerce"
    ],
    "capturedAt": "2016-02-04",
    "originalWidth": 4712,
    "originalHeight": 3366
  },
  {
    "id": "colis-cartons",
    "src": "/blog/photos/colis-cartons-v2.webp",
    "alt": "Une personne étiquette un colis en carton devant un ordinateur portable et un registre de commandes",
    "caption": "Photographie d’illustration : préparer et étiqueter une commande avant son expédition.",
    "sourceUrl": "https://www.pexels.com/photo/woman-sitting-at-the-table-and-packing-orders-7857532/",
    "credit": "Kampus Production / Pexels",
    "license": "Pexels License",
    "licenseUrl": "https://www.pexels.com/license/",
    "width": 1400,
    "height": 935,
    "tags": [
      "ecommerce",
      "emballage",
      "colis",
      "logistique",
      "commandes"
    ],
    "capturedAt": "Date de prise de vue non publiée sur la page source ; photographie attribuée à Kampus Production, Portugal.",
    "originalWidth": 6016,
    "originalHeight": 4016
  },
  {
    "id": "analyse-documents",
    "src": "/blog/photos/analyse-documents-v2.webp",
    "alt": "Une femme utilise un clavier devant un ordinateur de bureau, près de grandes fenêtres",
    "caption": "Photographie d’illustration : travailler sur ordinateur dans un bureau lumineux.",
    "sourceUrl": "https://www.pexels.com/photo/woman-sitting-in-front-of-computer-monitor-1181635/",
    "credit": "Christina Morillo / Pexels",
    "license": "Pexels License",
    "licenseUrl": "https://www.pexels.com/license/",
    "width": 1400,
    "height": 935,
    "tags": [
      "ordinateur",
      "bureau",
      "digital",
      "PME",
      "travail"
    ],
    "capturedAt": "Date non indiquée sur la page Pexels ; série photographique WOCinTech, crédit EXIF Mike Ngo Photography.",
    "originalWidth": 5743,
    "originalHeight": 3834
  },
  {
    "id": "mobile-cafe",
    "src": "/blog/photos/mobile-cafe-v2.webp",
    "alt": "Des mains tiennent un smartphone devant un ordinateur portable",
    "caption": "Photographie d’illustration : l’utilisation d’un téléphone devant un ordinateur portable.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:William_Iven_2015-02-11_(Unsplash).jpg",
    "credit": "William Iven firmbee",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 930,
    "tags": [
      "mobile",
      "parcours-client",
      "responsive"
    ],
    "capturedAt": "2015-02-11",
    "originalWidth": 4288,
    "originalHeight": 2848
  },
  {
    "id": "bois-matiere",
    "src": "/blog/photos/bois-matiere.webp",
    "alt": "Des blocs de bois aux textures naturelles",
    "caption": "Photographie d’illustration : les matières et textures du travail du bois.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wood_(Unsplash).jpg",
    "credit": "kindfolk kindfolk",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "artisan",
      "menuisier",
      "bois",
      "matiere"
    ],
    "capturedAt": "2014-08-03",
    "originalWidth": 4896,
    "originalHeight": 3264
  },
  {
    "id": "mobile-design",
    "src": "/blog/photos/mobile-design.webp",
    "alt": "Un smartphone posé sur une table avec le mot design à l’écran",
    "caption": "Photographie d’illustration : le design d’un parcours pensé pour le téléphone.",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Design_smartphone_definition_(Unsplash).jpg",
    "credit": "Edho Pratama edhoradic",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1400,
    "height": 933,
    "tags": [
      "mobile",
      "design",
      "site-web",
      "responsive"
    ],
    "capturedAt": "2016-10-13",
    "originalWidth": 4062,
    "originalHeight": 2708
  }
]
