import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BookOpen, Check, ChevronDown, CircleAlert, Database, FileCheck2, Files, KeyRound, Mail, MessageSquare, PlugZap, RefreshCw, ShoppingBag, UsersRound } from 'lucide-react'
import { ServiceHero } from '@/components/sections/services/ServiceHero'
import { BusinessSectionHeading, ServiceReveal } from '@/components/sections/services/BusinessService'
import { IntegrationDemo } from '@/components/sections/services/TechnicalDemo'
import { ServicePageSeo, serviceMetadata } from '@/components/sections/services/ServicePageSeo'
import '@/components/sections/services/technical-services.css'

const path = '/integrations-api'
const name = 'Intégrations & API'
const description = 'Litus développe vos intégrations API et connecteurs sur mesure : CRM, ERP, e-commerce, facturation et synchronisation de données, avec des échanges suivis et documentés.'
export const metadata = serviceMetadata({ path, name, title: 'Intégrations API & connecteurs sur mesure pour entreprise | Litus', description, image: '/blog/photos/bureau-reunion-clair.webp' })
const contact = '/contact?objet=Int%C3%A9grations%20%26%20API'
const questions = [
  { question: 'Quelle différence entre une intégration API et une automatisation ?', answer: 'L’intégration relie des systèmes et définit comment leurs données sont échangées. L’automatisation orchestre des actions selon des événements ou des règles. Un même projet peut combiner les deux : synchroniser une commande dans le CRM, puis déclencher une tâche de suivi.' },
  { question: 'Pouvez-vous connecter n’importe quel logiciel ?', answer: 'Nous vérifions d’abord les possibilités réelles : API disponible, documentation, droits d’accès, version du logiciel, quotas et conditions d’utilisation. En l’absence d’API, un échange de fichiers peut parfois convenir. Nous ne promettons pas une compatibilité sans cette étude.' },
  { question: 'Les informations sont-elles synchronisées en temps réel ?', answer: 'Cela dépend des systèmes et du besoin. Certains logiciels signalent les changements par webhook ; d’autres doivent être interrogés à intervalles réguliers. La fréquence est choisie selon vos usages, les quotas et le coût du traitement.' },
  { question: 'Comment évitez-vous les doublons ou les mises à jour contradictoires ?', answer: 'Nous définissons la source de référence, les identifiants de rapprochement et les règles de mise à jour. Les événements déjà traités sont identifiés lorsque le système le permet, et les conflits sont gérés selon des règles explicites testées avec vos données d’exemple.' },
  { question: 'Que se passe-t-il si une connexion échoue ?', answer: 'Selon le périmètre convenu, le connecteur conserve un journal, classe les erreurs et prévoit des reprises ou une alerte. Certaines erreurs demandent une correction humaine : accès expiré, donnée manquante ou règle métier non satisfaite. Le mode de suivi est précisé avant la mise en service.' },
  { question: 'Quel budget prévoir pour développer un connecteur ?', answer: 'Le devis dépend des systèmes, des objets échangés, du volume, de la qualité des données et du niveau de suivi attendu. Nous commençons par un flux prioritaire et distinguons le développement, les abonnements aux logiciels tiers et la maintenance.' },
]
const pairs = [
  { from: ShoppingBag, to: Database, title: 'Boutique → gestion', text: 'Transmettre les commandes, rapprocher les clients et remonter les statuts. Garder des règles claires pour les stocks et les références.' },
  { from: UsersRound, to: FileCheck2, title: 'CRM → facturation', text: 'Préparer les informations de facturation à partir d’un dossier validé, sans recopier chaque champ dans un autre outil.' },
  { from: Files, to: MessageSquare, title: 'Données → équipes', text: 'Réunir les informations utiles au pilotage ou transmettre une notification quand une situation demande une intervention.' },
]
const systems = [
  { icon: UsersRound, title: 'CRM & relation client', text: 'Contacts, entreprises, opportunités et historique utile.' },
  { icon: Database, title: 'ERP & gestion', text: 'Articles, commandes, stocks et statuts opérationnels.' },
  { icon: ShoppingBag, title: 'Sites & boutiques', text: 'Formulaires, comptes, commandes et catalogues.' },
  { icon: FileCheck2, title: 'Paiement & facturation', text: 'Événements de paiement et pièces associées au dossier.' },
  { icon: Mail, title: 'Messagerie & notifications', text: 'Informations ciblées, adressées à la bonne équipe.' },
  { icon: PlugZap, title: 'API & bases métier', text: 'Services spécifiques et données de votre organisation.' },
]

export default function IntegrationPage() {
  return <div className="business-service technical-service-page">
    <ServicePageSeo path={path} name={name} description={description} questions={questions} />
    <ServiceHero id="integrations-title" eyebrow="Intégrations API · Connecteurs sur mesure" title={'Connectez vos logiciels.\nSimplifiez les échanges.'} accent="Simplifiez les échanges." description="Votre boutique, votre CRM et vos outils de gestion ont besoin de se parler. Nous concevons les connexions qui font circuler les bonnes informations, avec des règles claires et un suivi des échanges." primaryAction={{ label: 'Étudier mes connexions', href: contact }} secondaryAction={{ label: 'Voir les cas d’usage', href: '#echanges' }} visualBackground="/blog/photos/bureau-reunion-clair.webp" visual={<IntegrationDemo />} proof={<ul className="business-hero-proof"><li><Database />Vos données reliées</li><li><KeyRound />Des accès maîtrisés</li><li><BookOpen />Un fonctionnement documenté</li></ul>} />
    <div className="business-content">
      <section className="business-section" id="echanges" aria-labelledby="integrations-usages"><div className="business-container"><BusinessSectionHeading id="integrations-usages" eyebrow="L’information doit suivre votre activité" description="Pour les équipes qui utilisent plusieurs logiciels, chaque export, recopie ou contrôle manuel ajoute une étape. Une intégration utile commence par identifier l’échange qui vous manque vraiment.">Une information.<br /><em>Plusieurs outils à jour.</em></BusinessSectionHeading><ServiceReveal className="api-pairs">{pairs.map(({ from: From, to: To, title, text }) => <article className="api-pair" key={title}><div aria-hidden="true"><span><From /></span><ArrowRight /><span><To /></span></div><h3>{title}</h3><p>{text}</p></article>)}</ServiceReveal></div></section>
      <section className="business-section business-section-soft" aria-labelledby="integrations-regles"><div className="business-container business-split"><div className="business-copy"><p className="business-kicker">Avant de connecter</p><h2 id="integrations-regles">Les mêmes mots.<br /><em>Les mêmes règles.</em></h2><p>Un « client » n’a pas toujours le même sens dans votre boutique et votre CRM. Nous définissons les correspondances, les champs obligatoires et le logiciel qui fait référence pour chaque information.</p><p>Ce cadrage évite de simplement déplacer les incohérences d’un outil à l’autre. Il sert aussi à traiter les changements de statut, les suppressions et les cas particuliers.</p><Link href={contact} className="business-text-link">Décrire les outils à relier<ArrowRight size={15} /></Link></div><div className="api-scope" aria-label="Exemple de règles de synchronisation"><div><span>Information</span><span>Règle à définir</span></div><div><strong>Identité du client</strong><span>Quel identifiant commun ?</span></div><div><strong>Adresse de livraison</strong><span>Quel outil fait référence ?</span></div><div><strong>Statut de commande</strong><span>Quand mettre à jour ?</span></div><div><strong>Événement déjà reçu</strong><span>Comment le reconnaître ?</span></div><p>Les règles sont validées sur vos cas d’usage avant le développement du connecteur.</p></div></div></section>
      <section className="business-section" aria-labelledby="integrations-systemes"><div className="business-container"><BusinessSectionHeading id="integrations-systemes" eyebrow="Votre environnement reste le point de départ" description="Nous étudions les API et les accès disponibles avant de confirmer une connexion. Le choix entre connecteur existant, plateforme d’automatisation et développement spécifique dépend du besoin.">Vos logiciels gardent leur rôle.<br /><em>Le lien fait la différence.</em></BusinessSectionHeading><ServiceReveal className="api-service-types">{systems.map(({ icon: Icon, title, text }) => <article key={title}><Icon /><div><h3>{title}</h3><p>{text}</p></div></article>)}</ServiceReveal><Link href="/automatisation" className="business-text-link">Orchestrer ensuite vos processus avec l’automatisation<ArrowRight size={15} /></Link></div></section>
      <section className="business-section business-section-dark" aria-labelledby="integrations-reprise"><div className="business-container"><BusinessSectionHeading id="integrations-reprise" eyebrow="Un échange qui se suit" description="Une API peut changer, un accès peut expirer et un logiciel peut être momentanément indisponible. La gestion de ces situations fait partie de la conception.">Connecter, oui.<br /><em>Comprendre ce qui se passe, aussi.</em></BusinessSectionHeading><ServiceReveal className="business-grid">{[{ icon: KeyRound, title: 'Limiter les accès', text: 'Prévoir les autorisations nécessaires, le stockage des secrets et leur renouvellement selon l’environnement retenu.' }, { icon: CircleAlert, title: 'Rendre les erreurs lisibles', text: 'Conserver les traces utiles, distinguer une donnée à corriger d’un incident temporaire et identifier la prochaine action.' }, { icon: RefreshCw, title: 'Organiser les reprises', text: 'Prévoir les nouvelles tentatives, le traitement des événements répétés et les alertes convenues avec votre équipe.' }].map(({ icon: Icon, title, text }) => <article className="business-card" key={title}><span className="business-icon"><Icon /></span><h3>{title}</h3><p>{text}</p></article>)}</ServiceReveal></div></section>
      <section className="business-section business-section-warm" aria-labelledby="integrations-methode"><div className="business-container"><BusinessSectionHeading id="integrations-methode" eyebrow="Un premier flux, bien cadré" description="Nous commençons par un échange prioritaire. La recette valide aussi les exceptions : doublon, champ manquant, interruption et modification d’une donnée.">De la cartographie<br /><em>aux échanges en service.</em></BusinessSectionHeading><ServiceReveal className="tech-method">{[{ title: 'Observer les échanges', text: 'Identifier les logiciels, les accès, les données et les manipulations actuelles.' }, { title: 'Écrire les règles', text: 'Choisir la source de référence, les correspondances et la fréquence de synchronisation.' }, { title: 'Connecter et vérifier', text: 'Développer sur un environnement de test et valider les parcours avec vos exemples.' }, { title: 'Déployer et suivre', text: 'Mettre en service progressivement, documenter le fonctionnement et convenir du suivi.' }].map((item, i) => <article key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</ServiceReveal></div></section>
      <section className="business-section" aria-labelledby="integrations-equipe"><div className="business-container business-split"><figure className="business-photo"><Image src="/blog/photos/bureau-notes-analyse.webp" width={1400} height={933} sizes="(max-width:850px) 100vw, 50vw" alt="Documents et outils de travail réunis sur une table pour préparer un projet" /><figcaption className="business-photo-note"><strong>Un fonctionnement partagé avec vos équipes.</strong><span>Des responsabilités et des étapes identifiées.</span></figcaption></figure><div className="business-copy"><p className="business-kicker">Le lien entre métier et technique</p><h2 id="integrations-equipe">Votre équipe sait<br /><em>où en sont les données.</em></h2><p>Nous échangeons avec les personnes qui utilisent les logiciels et, si nécessaire, avec leurs éditeurs ou vos équipes techniques. Les conditions d’accès, les coûts tiers et les limites des interfaces sont discutés avant engagement.</p><ul className="business-check-list"><li><Check />Un périmètre précis et un devis adapté aux flux retenus.</li><li><Check />Une documentation pour comprendre les échanges.</li><li><Check />Un suivi défini pour les évolutions des logiciels.</li></ul><Link href="/developpement-web-sur-mesure" className="business-text-link">Développer aussi la fonctionnalité qui vous manque<ArrowRight size={15} /></Link></div></div></section>
      <section id="faq" className="business-section business-section-soft" aria-labelledby="integrations-faq"><div className="business-container"><BusinessSectionHeading id="integrations-faq" eyebrow="Vos questions">Vos outils, vos données.<br /><em>Les bonnes réponses.</em></BusinessSectionHeading><div className="business-faq">{questions.map(({ question, answer }) => <details key={question}><summary>{question}<ChevronDown /></summary><p>{answer}</p></details>)}</div></div></section>
      <section className="business-section"><div className="business-container"><div className="business-final"><div><p className="business-kicker">Commençons par un échange concret</p><h2>Quels logiciels devraient<br /><em>mieux travailler ensemble ?</em></h2><p>Indiquez-nous les outils utilisés, l’information à transmettre et ce que vous faites encore à la main. Nous étudierons les possibilités.</p></div><div className="business-final-actions"><Link href={contact} className="site-cta-primary">Parlons de vos intégrations<ArrowRight size={18} /></Link><span>Premier échange · Sans engagement</span><a href="tel:+33744985521">07 44 98 55 21</a></div></div><nav className="tech-related" aria-label="Prestations complémentaires"><Link href="/automatisation">Automatisation de processus</Link><Link href="/creation-application-web">Applications web</Link><Link href="/creation-site-ecommerce">E-commerce</Link><Link href="/creation-outils-ia">Intégration d’outils IA</Link></nav></div></section>
    </div>
  </div>
}
