import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, MapPin, Phone, ClipboardList, Search, MousePointer2, Wrench } from 'lucide-react';
import type { Trade } from '@/lib/artisan/catalog';
import { getTrade } from '@/lib/artisan/catalog';
import { artisanSchema, JsonLd } from '@/lib/artisan/seo';
import { ArtisansReveal } from '@/app/artisans/_components/ArtisansReveal';
import { ArtisanCases, ArtisanCta, ArtisanFaq, ArtisanPricing } from './ArtisanShared';
import ArtisanGallery from './ArtisanGallery';

export default function TradeLanding({ trade }: { trade: Trade }) {
  const related = trade.related.flatMap(slug => { const item = getTrade(slug); return item ? [item] : []; });
  const demo = trade.cases.length === 0;
  return <div className={`artisans-page trade-page trade-style-${trade.style}`}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JsonLd({ data: artisanSchema(trade) }) }} />
    <div className="art-container"><nav className="trade-breadcrumb" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span>/</span><Link href="/artisan">Artisans</Link><span>/</span><span aria-current="page">{trade.name}</span></nav></div>
    <section className="trade-hero" aria-labelledby="trade-title"><div className="art-container trade-hero-grid">
      <div className="trade-hero-copy"><p className="art-kicker">Votre métier, votre présence en ligne</p><h1 id="trade-title">{trade.title}</h1><p className="trade-hero-intro">{trade.intro}</p><p className="trade-promise"><span aria-hidden="true" />{trade.promise}</p><div className="trade-hero-actions"><Link href="/contact" className="trade-button">Échanger sur mon projet <ArrowRight size={19} /></Link><a href="#budget" className="trade-text-link">Quel budget prévoir ? <ArrowRight size={17} /></a></div><p className="trade-hero-footnote">Lorient · Le Mans · Accompagnement à distance</p></div>
      <figure className="trade-hero-figure"><div className="trade-photo-wrap"><Image src={`/artisan/${trade.slug}-metier.webp`} alt={trade.photoAlt} width={1280} height={960} sizes="(max-width: 850px) 100vw, 48vw" priority className="trade-hero-photo" /><div className="trade-photo-note"><Wrench size={19} /><span>Du savoir-faire.<br /><strong>Une présence à sa hauteur.</strong></span></div></div><figcaption>{trade.photoCredit}</figcaption></figure>
    </div></section>
    <nav className="trade-subnav" aria-label="Dans cette page"><div className="art-container"><a href="#priorites">Vos priorités</a><a href="#contenus">Le site</a><a href="#visibilite">SEO & Google Ads</a><a href="#budget">Les tarifs</a><a href="#parcours">Le parcours client</a><a href="#questions">Vos questions</a></div></nav>
    <div className="art-content">
      <section className="art-section trade-problem" id="priorites"><div className="art-container"><div className="trade-two-column"><div><p className="art-kicker">Partir de la réalité du terrain</p><h2>{trade.problem.title}</h2></div><div>{trade.problem.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div></div><ArtisansReveal className="trade-priorities">{trade.priorities.map((priority, i) => <article key={priority.title}><span className="trade-step-index">0{i + 1}</span><h3>{priority.title}</h3><p>{priority.text}</p></article>)}</ArtisansReveal></div></section>
      <section className="art-section trade-content-section" id="contenus"><div className="art-container trade-content-grid"><div><p className="art-kicker">Le bon contenu, au bon endroit</p><h2>Un site qui répond<br /><em>aux vraies questions.</em></h2><p>Pour {trade.subject}, chaque page doit aider le visiteur à comprendre une prestation, vérifier si vous intervenez chez lui et préparer sa demande. Voici une architecture à adapter à vos services réels.</p><div className="trade-tech-links"><Link href="/creation-site-internet">Création de site internet <ArrowRight size={16} /></Link><Link href="/expertise/wordpress">WordPress <ArrowRight size={16} /></Link></div><p className="trade-small">Le choix technique suit le besoin : autonomie sur les contenus, galerie, formulaire ou fonctionnalités spécifiques. Il n’impose pas une technologie par défaut.</p></div><div className="trade-sitemap"><div className="trade-browser"><span aria-hidden="true">•••</span><span>Exemple d’arborescence · à personnaliser</span></div><ol>{trade.pages.map(page => <li key={page.name}><span className="trade-page-dot" aria-hidden="true" /><div><h3>{page.name}</h3><p>{page.purpose}</p></div></li>)}</ol></div></div></section>
      <section className="art-section" id="visibilite"><div className="art-container"><div className="trade-two-column"><div><p className="art-kicker">Être trouvé près de chez vous</p><h2>{trade.local.title}</h2></div><div><p>{trade.local.text}</p><p className="trade-small">Google explique que les résultats locaux dépendent notamment de la pertinence, de la distance et de la notoriété. Aucun prestataire ne peut garantir une position. <a href="https://support.google.com/business/answer/7091?hl=fr" target="_blank" rel="noopener noreferrer">Les critères de Google</a>.</p></div></div><div className="trade-search-panel"><Search size={21} aria-hidden="true" /><div><p className="trade-small">Exemples d’intentions de recherche, sans estimation de volume</p><ul>{trade.local.queries.map(query => <li key={query}>{query}</li>)}</ul></div></div><div className="trade-channel-grid"><article><Search size={25} /><h3>Le référencement naturel</h3><p>{trade.channels.seo}</p><Link href="/referencement-naturel" className="trade-text-link">Notre accompagnement SEO <ArrowRight size={17} /></Link></article><article><MousePointer2 size={25} /><h3>Les campagnes Google Ads</h3><p>{trade.channels.ads}</p><Link href="/google-ads" className="trade-text-link">Notre gestion Google Ads <ArrowRight size={17} /></Link></article></div><p className="trade-decision"><strong>Comment choisir ?</strong> {trade.channels.decision}</p></div></section>
      <section className="art-section trade-qualification" id="qualification"><div className="art-container trade-two-column"><div><p className="art-kicker">Moins de flou, plus de contexte</p><h2>{trade.qualification.title}</h2><p>{trade.qualification.text}</p><p className="trade-small">Sur mobile, les coordonnées et l’action principale restent faciles à trouver. Le formulaire demande seulement les informations utiles au premier échange, sans multiplier les étapes.</p></div><div className="trade-intake"><div className="trade-intake-heading"><ClipboardList size={24} /><div><h3>Préparer une demande utile</h3><p>Exemple de qualification, pas un formulaire à remplir ici.</p></div></div><ul>{trade.qualification.fields.map(field => <li key={field}><Check size={18} aria-hidden="true" />{field}</li>)}</ul><div className="trade-intake-bottom"><MapPin size={17} />Localisation de l’intervention <span>+</span><Phone size={17} />Coordonnées de rappel</div></div></div></section>
      <ArtisanGallery slug={trade.slug} />
      <ArtisanPricing context={trade.budget} />
      <section className="art-section" id="parcours"><div className="art-container"><div className="trade-heading-row"><div><p className="art-kicker">{demo ? 'Démonstration · pas un cas client' : 'Un parcours à construire ensemble'}</p><h2>De la recherche<br /><em>à la demande de devis.</em></h2></div><p className="trade-heading-aside">Un exemple de parcours pour {trade.subject}. Il illustre le fonctionnement proposé, sans inventer de client ni de résultat.</p></div><ArtisansReveal className="trade-journey">{trade.journey.map((step, i) => <div key={step}><span>{i + 1}</span><p>{step}</p>{i < trade.journey.length - 1 && <ArrowRight size={18} aria-hidden="true" />}</div>)}</ArtisansReveal></div></section>
      <ArtisanCases slugs={trade.cases} />
      <section className="art-section trade-method" id="methode"><div className="art-container trade-two-column"><div><p className="art-kicker">Une méthode simple</p><h2>Votre métier d’abord.<br /><em>La technique ensuite.</em></h2><ol className="trade-method-list"><li><strong>Comprendre.</strong> Vos prestations, votre zone, votre capacité à traiter de nouvelles demandes et les preuves disponibles.</li><li><strong>Construire.</strong> Une arborescence claire, des textes validés avec vous, des photos choisies et un parcours mobile soigné.</li><li><strong>Mettre en ligne.</strong> Vérifier les formulaires, les liens, les métadonnées et le fonctionnement des points de contact.</li><li><strong>Faire évoluer.</strong> Distinguer les visites, les demandes et les opportunités réellement pertinentes pour ajuster les actions.</li></ol></div><aside className="trade-preparation"><p className="art-kicker">Pour notre premier échange</p><h3>Ce qui nous aidera à avancer</h3><ul>{trade.preparation.map(item => <li key={item}><Check size={17} aria-hidden="true" />{item}</li>)}</ul><p>Pas besoin d’avoir un dossier parfait. Nous identifions ensemble ce qui existe et ce qu’il reste à préparer.</p><Link href="/contact" className="trade-text-link">Préparer mon projet avec Litus <ArrowRight size={17} /></Link></aside></div></section>
      <ArtisanFaq items={trade.faq} />
      <section className="art-section trade-related"><div className="art-container"><p className="art-kicker">Des activités qui se complètent</p><h2>Vous exercez <em>plusieurs métiers ?</em></h2><div>{related.map(item => <Link href={`/artisan/${item.slug}`} key={item.slug}>{item.name}<ArrowRight size={18} /></Link>)}<Link href="/artisan">Tous les métiers<ArrowRight size={18} /></Link></div></div></section>
      <ArtisanCta title={trade.cta} />
    </div>
  </div>;
}
